delmic/odemis

- src/odemis/acq/__init__.py
- src/odemis/acq/_futures.py
- src/odemis/acq/stream/__init__.py
- src/odemis/acq/stream/_base.py
- src/odemis/acq/stream/_live.py
- src/odemis/acq/stream/_sync.py
- src/odemis/gui/cont/acquisition.py
- src/odemis/gui/cont/microscope.py
- src/odemis/gui/cont/settings.py
- src/odemis/gui/cont/streams.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/model/__init__.py
- src/odemis/util/driver.py
Briefly the changes included:
- Use of prepare method: This method takes care of any actions required to be taken before the stream becomes active e.g. performing spot alignment for AlignedSEMStream or setting the corresponding path for optical path manager in Sparc
- We automatically hide the misaligned streams and give a warning whenever two misaligned streams are displayed.
- We display a status message while spot alignment is in progress.
> Delphi alignment interface

- src/odemis/acq/stream/__init__.py
- src/odemis/acq/stream/_base.py
- src/odemis/gui/comp/canvas.py
- src/odemis/gui/comp/miccanvas.py
- src/odemis/gui/comp/viewport.py
- src/odemis/util/img.py
- src/odemis/util/test/img_test.py
Fixes for the support for pyramidal data in one viewport related changes
> Fixes for the Milestone 5a bugs

- src/odemis/driver/symphotime.py
- src/odemis/driver/test/symphotime_test.py
> Symphotime Driver

- src/odemis/driver/symphotime.py
- src/odemis/driver/test/symphotime_test.py
- src/odemis/model/_dataflow.py
> Symphotime tc-detector-live driver

- install/linux/usr/share/odemis/sim/secom-flim-sim.odm.yaml
- src/odemis/acq/path.py
- src/odemis/acq/stream/_helper.py
- src/odemis/acq/stream/_live.py
- src/odemis/acq/stream/_sync.py
- src/odemis/acq/test/flim_test.py
- src/odemis/acq/test/path_test.py
Includes some additional testing files that may not need to be tracked later on.
> Acquisition mode: scanned fluorescence-lifetime and optical path manager

- src/odemis/driver/npmc.py
- src/odemis/driver/test/npmc_test.py
Although not fully tested yet, here is the driver for the delay stage.
> Delay stage

- doc/develop/plugins.rst
- plugins/tileacq.py
- plugins/timelapse.py
- src/odemis/gui/plugin/__init__.py
- src/odemis/gui/test/plugin_test.py
…t settings from changing during acquisition.
> Pause/Resume Settings and Streams in Acq Plugins

- src/odemis/model/_vattributes.py
- src/odemis/model/test/vattributes_test.py
> Memory leak fix

- src/bugreporter/odemis_bugreporter.py
Don't fail if some command fail.
If it fail, log it.
Store all the files directly in the root of the archive, as we used to
do.
Still some issues with storing the report directories...
> bugreporter: make the compress_file more reliable

- src/odemis/acq/stream/_projection.py
- src/odemis/dataio/csv.py
- src/odemis/gui/cont/export.py
- src/odemis/gui/util/img.py
- src/odemis/gui/util/test/img_test.py
> export: Temporal spectrum and projection export to PNG, TIFF, and CSV

- debian/control
- src/odemis/dataio/__init__.py
- src/odemis/dataio/_base.py
- src/odemis/dataio/catmaid.py
- src/odemis/dataio/test/catmaid_test.py
* only show the url in the gui when filepath is a url
* in find_fittest_converter return catmaid when a url instead of a filename is passed
> added catmaid support in dataio

- src/odemis/acq/stream/_projection.py
- src/odemis/gui/cont/export.py
- src/odemis/gui/util/img.py
- src/odemis/gui/util/test/img_test.py
Temporary fix for spectrum line export, but requires refinement.
> Spectrum Line Export Fix

- src/odemis/driver/test/tmcm_test.py
- src/odemis/driver/tmcm.py
Sometimes the first value was considered high, while in other places, it
was considered low.
Also, revert the changes on led_do_prot, so that the values given in the
argument are actually the "reported value" of do_axes. It should
hopefully simplify a little bit the reading of the YAML file. Anyway, we
need do_axes, as we need to know how long to wait.
> driver tmcm: fix high/low value confusion on do_axes

- src/odemis/driver/rigol.py
Minor fixes for small issues I noticed when looking through the Rigol driver.
> driver rigol: Small fixes

- src/odemis/acq/align/autofocus.py
- src/odemis/acq/align/test/autofocus_test.py
- src/odemis/driver/simcam.py
- added 1 line autofocus tests to autofocus_test
- testing for slit image and initial simulator image
- Measure1d measures the focus for a 1 line ccd based on a gaussian fit
- initial sigma estimate from 100 to 10 because sigma will be small for the good focus position
> added functionality to test simulating a 1 line ccd autofocus

- src/odemis/driver/nfpm.py
- src/odemis/driver/nfpm_netscan.py
* send bytes to driver
* attributes should be unicode strings
* copy .items into list instead of using iterator because elements can be deleted inside loop
* use correct python interpreter
> python3 migration: nfpm driver

- install/windows/viewer.spec
- requirements.txt
I think we installed pyinstaller 3.5.3, but pip --list showed 3.5
> Windows installer v2.10

- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
and setting and receiving different parameters
> client code to support communication with a microscope server

- scripts/ebeam_scan_to_multiprobe.py
- In practice you always run this script with the backend running to get the live view of the diagnostic ccd.
- Added diagnostic-ccd as a default value for the role.
- Cleaned up doc strings.
> ebeam scan to multiprobe script changed to always need a backend to run.

- src/odemis/driver/ueye.py
For SENSOR_UI527xSE_M the camera output is now 12 bit, because this is the highest possible for that sensor. For all other sensors the camera output is still 8 bit.
> ueye gige camera output to 12 bit

- src/odemis/acq/stream/_sync.py
- src/odemis/acq/test/stream_test.py
- src/odemis/driver/andorcam2.py
For spectrum, AR, and temporal spectrum
> Live update acquistion 

- src/odemis/driver/actuator.py
If the axis was already referenced, it would try to move to the "current" position,
but that was without including the offset. It would cause an actual move, unneeded,
and sometimes even prevent initialisation, if the current position of the child is outside the
range.
=> Don't move if there is no need to move.
Also clean-up a little the log messages.
> driver actuator LinearActuator: don't move at init if already referenced

- scripts/ebeam_scan_to_multiprobe.py
- added auto option to cli, if set to True alignment will be done automatically
- added code to automatically align ebeam scan to multiprobe
> Ebeam scan to multiprobe script automated.

- install/linux/usr/share/odemis/hwtest/clspots-sem-diagnostic.odm.yaml
- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
@pieleric could you have a look to see if what I'm doing with the SEM, Scanner and Stage objects is correct?
> XTclient add hwcomponents

- src/odemis/gui/cont/tabs.py
First draft - is this hack fulfilling the requirements for now?
> tab analysis: Added dialog box to select AR or Spectrum streams

- scripts/galvo_phase_gain_calibration.py
- fit a sine to the image and display this on the image
> Live view script added for galvo phase and gain alignment

- scripts/galvo_scan_to_multiprobe.py
- added script to align galvo scan to multiprobe manually or automatically.
> Galvo scan to multiprobe script created

- src/odemis/driver/pigcs.py
Do not really scan the devices if using FakeBus.
Do not try to scan the disabled axes, as they tend to fail.
If the scan of a device fail, don't completely fail, but just continue with the next one.
> driver pigcs: Improve device scan

- install/linux/etc/odemis.conf
Put some nicer default, such as bumping logging level to DEBUG, which is the only
one which sufficient to properly understand what happened when something wrong and unexpected happened.
> config: update the default odemis.conf

- plugins/cli_rgb.py
When cancelling, instead of stopping the progress bar but leaving the acquisition on, now
we explicitly try to stop the current part of the acquisition. If the
user is trying to cancel because the dwell time was too long, it's
really useful to not let an acquisition run the background, and messup
all the future acquisitions.
> plugins cli_rgb: attempt to immediately stop the acquisition when cancelling

- src/bugreporter/odemis_bugreporter.py
When using just the future.result() timeout, on timeout the command output
is not provided at all, and the command is not stopped.
So now, we explicitly stop the command after the timeout, which allows to get the
output back.
Especially useful for odemis-hw-status.txt which can sometimes block on one component,
but the rest is still interesting.
> bugreporter: add a timeout to the external commands

- src/odemis/driver/andorshrk.py
Still a work in progress. Main issue is that if an error occurs during startup, it seems like we connect to the wrong andor hardware (serial number 'x').
The reconnect takes 2 minutes, which is a bit excessive.
> Andor usb compliance

- src/odemis/acq/stream/_static.py
Normally for every polarization, we acquire every positions. However,
there are two reason this doesn't happen:
* Something went wrong the acquisition file
* Some positions are slightly different (due to floating point error),
and not detected as similar.
The stream doesn't really mind, but if a non-existing combination is
requested, it's obviously going to fail. So let's try to warn it early,
and if that due to the second case, we might eventually try to make a
more clever code.
> acq stream StaticARStream: warn if a combination of pos+polarization is missing

- src/odemis/acq/stream/_helper.py
If the the user changes the binning of the image while the stream is
playing, some images will have different shape than others. This causes
failure to do the sum.
In addition to preventing the image update, this also ends the histogram
update.
=> In such case, discard the older images which are not compatible
> acq stream helper: fix integrating images of live stream when image shape changes

- src/odemis/acq/path.py
We tried to check for the presence of the pass-through filter, but a
typo prevented from ever finding it (choices -> choices.values()).
Anyway, the function needs to also account for the possible different
role of the ccd (eg, ccd0).
So instead of having a dedicated function, just detect the case *in* the
code that is in charge of the move to the right filter. This avoids
having to code twice the same thing in two different ways.
> acq path: fix the check for pass-through filter

- src/odemis/driver/hamamatsurx.py
In Python 3, the network sockets send and receive bytes.
Also adjust a couple of extra places in the message handling.
In particular, the CameraInfo now behaves a little bit less special, and
each line is return as a separate return value instead of one value
containing a list.
These changes haven't be tested on the hardware yet.
> driver hamamatsurx: Migrate to using bytes for Python 3

- src/odemis/gui/cont/export.py
When pressing "Export" with a view which has no stream (shown), an error
would be raised. That's was a bug added by the polarimetry export, which
assumed there is always at least one stream.
=> Check whether there is a stream.
=> Instead checking if the export button should be shown based on the
the global streams, check the streams of the view.
> gui cont export: only enable "Export" button when there is something to export

- src/odemis/acq/stream/_projection.py
I think this is the fix.
Tested:
- Export of PNG and CSV
- Test cases
> projection: modified mean projection to use floating point values

- src/odemis/driver/ueye.py
It's not true anymore, as it's changed.
> driver ueye: remove comment

- src/odemis/driver/picoquant.py
Inspired by the improvements in the avantes driver, now also clarify the
picoquant driver.
No behaviour change.
> driver picoquant: clean-up

- src/odemis/acq/align/delphi_man_calib.py
The overview image is only used for the stage alignment, and still only
really useful for the very first time. In many cases, this causes an
extra 2 minutes to the calibration.
=> allow to not do that, at least on the command line
> acq align delphi_man_calib: add --keep-loaded argument to avoid loading/unloading

- src/odemis/gui/util/img.py
The projection size depends on the input size. On small input size, the
output image ends up really tiny (eg 128px), which makes all the legend
and spider web almost unreadable. In the GUI, it's fine, as the image is
scaled to the view.
=> Force the output image to be at least 800px.
Also move the outer circle to exactly touch the image (instead of being
spaced by a 1.5 tick). Otherwise it gives the feeling that some data is missing.
Also clean-up a little the code to make it a little bit more direct and
explicit.
> gui util img: make AR export image at least 800px

- src/odemis/gui/cont/tabs.py
Two (weird) user behaviours were not well handled:
1. The user quickly toggle/untoggle the manual focus button (a couple of
times). In such case, every click would be executed, at the same time.
Eventually the right (last) thing would happen, but for a while
the gauge would get crazy.
=> Cancel the previous manul focus action before starting a new one.
2. The user starts manual focus, and immediately after presses auto
focus. It would result in both running, then the auto focus taking
control.
=> Immediately disable the auto focus button when the user toggles
the manual focus. It's now possible to also immediately change the
grating and detector. That's fine.
> gui cont Sparc2AlignTab: Handle better cancelation of manual focus

- src/odemis/util/spot.py
Created a separate pull-request for this as requested.
> Small changes to spot.py to improve readability and have consistent numpy behavior

- src/odemis/gui/comp/miccanvas.py
As DataArrays cannot be directly used as keys in a dict, because they
are not hashabel, we used id() to proxy them. Although id() can NOT collide
with other objects currently allocated, it can collide with previous
objects.
When opening a new acquisition file (in the analysis tab) this caused sometime
the image shown to be the one from a previous stream instead of the new
stream, because that new stream create a DataArray at the same space in
memory as the previous stream. This might have caused a lot more issues
with the pyramidal stream because they keep reusing memory space for
tiles... however a bug prevented the code from ever using the cache.
=> Use weakref's. It's less convenient as they cannot be put in a dict,
but it ensures they are never mixed up.
Also clear the cache when …
> gui comp miccanvas: fix RGBA DataArray caching

- src/odemis/util/test/filename_test.py
Testcase fails when tested at midnight
> util-filename: bugfix testcases

- src/odemis/util/spot.py
- src/odemis/util/test/transform_test.py
- src/odemis/util/transform.py
I wrote a new Transform class that supports the 'Anamorphosis transform'. Useful to model stigmator effects.
> Anamorphosis

- src/odemis/driver/tmcm.py
It's not absolutely necessary, but for the case we want to ensure that a
TSV file is loaded at start-up, it's nice to be able to use *any* file,
even if it has global params.
> driver tmcm: also allow to update the global parameters from the TSV file

- src/odemis/gui/comp/overlay/world.py
The dragging of the end or start of the line used to always associate the cursor
position to the line position. On the ruler (a simple line), it doesn't
differ too much from the original position of the cursor, and that's
kind of expected anyway.
On the label, if someone starts the dragging from the text area,
this can mean a shift of 100 or 200 px (if the text is long).
When trying to adjust slightly the position of the label, or trying to
click on the text but moving by 1 or 2 px, it's quite irritating.
=> Do not use directly the cursor position as a new position, but
shift that original position by the amount of dragging.
This way, a move of 1 px by the mouse always corresponds to the move
of one pixel in the end point.
Also fix a tiny bug related to the selection. Now that the tools …
> gui comp overlay LabelGadget: fix large movement when draging from the text

- src/odemis/model/_core.py
Updated for new instructions on building Odemis in Windows with python 3.6.8
> Setup Python Dev in Windows

- plugins/cliccd.py
- plugins/la_spec.py
- plugins/secom_cl.py
- src/odemis/acq/stream/_base.py
- src/odemis/acq/stream/_sync.py
- src/odemis/acq/test/stream_test.py
- src/odemis/gui/cont/acquisition.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/model/__init__.py
provides live image
works for: CL, SEM, ARMDstream, streak camera
orange next pixels work
however has a blue NON-transparant background
Still 9 points to discuss with Eric [See TODO K.K. ERIC]
> live update of acquisition

- src/odemis/gui/cont/tabs.py
…ame in all views and to only show the first non-empty view in full screen
> Modify analysis tab to show 1x1 when all views are the same.

- plugins/export_spec_3d_csv.py
Allows to export to a CSV a (3D) spectrum data.
As requested by some users.
> plugins: new export_spec_3d_csv

- src/odemis/driver/simcam.py
- src/odemis/gui/log.py
- src/odemis/gui/model/__init__.py
shows an pop up message if an error occurred or if an recovery from an error is made.
TODO is change all the error messages for subsystems to a (maybe) more meaningful message, which includes the next actions to be taken. So for example notify user that a recovery is made.
> Os error msg pop up

- src/odemis/acq/stitching/_registrar.py
The registered positions are saved in the global shift for use in the field correction code for calibration of FUMO Beta.
The comments for debugging hint that one can select only a part of the input image (if for example the last column is black but should not be black the measured shift is wrong, by not selecting the last column this can be fixed).
The last change made was removal of unnecessary spaces. PyCharm has a strong tendency to delete those at the end of the line (I have tried multiple times to stop doing that), but maybe this is also a nice cleanup of the code?
> Registered positions for field corrections (+ comments for debugging)

- plugins/tileacq.py
It would automatically stop as soon as it finds one acquisition stream.
If there are multiple streams, it should just acquire *all* of them.
Also show the last tile acquire at the end of the acquisition, instead
of not showing anything, if no stitching is done.
Also show a popup message, to confirm everything went fine, instead of
just closing the window.
> plugin tileacq: on SPARC, acquire all the streams

- doc/develop/dataio.rst
Now that we've written code that does the conversion, and realise how
unclear it was... so let's document it.
> doc dataio: add formula to convert from pixel coordinates to physic coordinates

- src/odemis/driver/smaract.py
- src/odemis/driver/test/smaract_test.py
No need to wait for an axis to end referencing before starting the next
one, there are independent.
Also add better simulation of the referencing.
Also fix missing property key for simulator.
Update the test cases to test this.
> driver smaract: MCS2 supports synchronous axis referencing

- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
- Remove python3 imports 
- Remove unused imports
> Fix linked actuator python2 compatibility 

- src/odemis/driver/xt_client.py
Added channel names for checks is_autostigmating, is_running_auto_contrast_brighness and is_autofocussing…trast_brighness and is_autofocussing
> Added channel names for checks is_autostigmating, is_running_auto_contrast_brighness and is_autofocussing

- src/odemis/driver/tmcm.py
The new support for the CANopen hardware came at the price that every
installation needs to have python-canopen installed. That's a little
unconvenient, especially as it's not packaged for Ubuntu 16.04.
=> Make it an error iif loading the CANController.
> driver tmcm: allow to load without canopen module

- src/odemis/odemisd/start.py
Stop using deprecated functions.
We don't support wxPython 3 anymore.
> odemisd start: Remove wxPython 3 compatibility code

- src/odemis/acq/align/spot.py
- src/odemis/util/spot.py
Added comments and updated docstrings, I hope this clarifies things.
> Added clarifying comments to FindGridSpots and related functions.

- src/odemis/acq/stream/_live.py
While setting up the excitation and emission, no image is being
acquired. As the emission actually exposes the sample, it's best to
set it up last, so that if the excitation setup is long, it's not
exposed.
Also ensure that setting the emission power is done in one step, instead
of first turning off everything and then turning on a channel.
It shouldn't have much effect, just a tiny bit faster.
Also fix the brightfield power setup to not always set the power to the
maximum when starting to play the stream. Also adjust all the channels
when changing the power, not just the first one.
Note that this is more a theoretical issue, as currently all the
hardware for brightfield only have 1 channel.
> acq stream live: Improve light power control

- plugins/zstack.py
It's much easier to pick good Z just based on the image.
Also don't fail if the focus actuator doesn't provide a .speed VA.
> plugins zstack: Update zstart based on the current focus position

- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
- pitch, stigmators, dc coils en switch multi/single beam, get scan mode
> xtclient: new functionalities required for multibeam

- src/odemis/driver/test/xt_client_test.py
Make sure almost all code is covered by unittests and at the end of each test the values are set back to their initial value.
> Xtclient add missing unittests

- src/odemis/gui/cont/tabs.py
When activating the tab, if L1 is not far from the FAV_POS (eg, it just
referenced), and the optical path is still being moved from a previous
tab change, then it could have some time to update the position, which
the tab would use as new FAV_POS, until it finally asks to move the
optical path. In such case, the FAV_POS would stay at an incorrect
position.
=> Do as for the fiber aligner: only update when the optical path is
fully ready. So we know that by that time the L1 position is not
updating due to a move from the OPM.
Also fix a potential rare bug causing the GUI to crash when switching to
fiber align mode.
> gui cont tabs SPARC2Align: only update L1 FAV_POS_ACTIVE when optical path is ready

- src/odemis/util/test/transform_test.py
- src/odemis/util/transform.py
Can be used to convert an index into a 2-dimensional array into physcial
coordinates.
> Added a function to_physical_space

- install/linux/lib/udev/rules.d/99-pi-fixed.rules
> config udev: add PI E-709 to the udev rule

- src/odemis/acq/stream/_projection.py
- src/odemis/acq/stream/_sync.py
- src/odemis/driver/lakeshore.py
- src/odemis/driver/piezomotor.py
The regular batch of fixes for exceptions with a , instead of % for the
message formating.
> fix exceptions formatting

- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
- src/odemis/model/_metadata.py
The goal of this wrapper is to automatically adjust the underlying stage movement based on the movement of its axes. As the sample is tilted by ~45° (along Y), whenever moving the stage in Y, the distance of the sample to the optical objective changes. This wrapper compensate for this change by linearly mapping the dependant axes.
> METEOR Linked Axes Actuator

- src/odemis/driver/tmcm.py
Another missing b...
Also add a user config in the simulator, so that the code can be tested.
> driver tmcm: fix reading user config in Python 3

- src/odemis/acq/calibration.py
- src/odemis/acq/test/calibration_test.py
- src/odemis/gui/cont/settings.py
On Python 2 it was recommended to open the file in binary, but it
actually worked as text. On Python 3, the csv module needs to use the
text mode.
=> Use the text mode.
Move the whole writing to a separate function, so that it can be
tested... and add a test.
> odemis acq calibration: fix reading/writing streakcam calibration on Python 3

- src/odemis/driver/test/tfsbc_test.py
- src/odemis/driver/tfsbc.py
- src/odemis/model/_metadata.py
First attempt at offset controller driver.
Do you think it makes sense to write a simulator and testcases for this driver? If so, what would you test for? We don't get any values back from the hardware if I understand it correctly, so there's not much we can do.
> Sonic beam offset controller

- src/odemis/util/test/transform_test.py
- src/odemis/util/transform.py
Utility function to convert from physical coordinates to pixel indices.
> Added to_pixel_index function

- src/odemis/driver/technolution.py
- src/odemis/driver/test/technolution_test.py
New PR for the ASM technolution wrapper since the old one did not function properly.
I propose to first finish this review before I start implementing simulator 3.0 otherwise these PR remain a bit unhandable (become to big with to much issues and hard to see the forest for the trees).
Since the Setpoints are still in discussion the exact implementation will be a new PR
Furthermore this wrapper does hold some TODO's which can be solved after we can use newer simulators/API's from technolution
The old PR can be found at:
https://github.com/delmic/odemis/pull/1420
> Technolution wrapper

- src/odemis/driver/smaract.py
- src/odemis/driver/test/smaract_test.py
driver smaract: updated cancellation of all running moves and state change on failed reference on init
> Smaract feature update

- src/odemis/driver/tescan.py
- src/odemis/driver/test/tescan_test.py
Use FetchImage instead of FetchArray
Handle flush
Update testcases
> Update tescan driver

- src/odemis/driver/tescan.py
Disable the flushing as it doesn't seem to help, and only cause extra
issues.
Also do not change the blanker value if it's set to auto.
> driver tescan: small fixes

- src/odemis/gui/cont/tabs.py
Some debug code was left over.
> gui cont tabs: only show the CryoSECOM tab for the CryoSECOM

- src/odemis/driver/xt_client.py
add info that beam shift is nothing else but setting the current on the DC coils (true for normal and multibeam SEM).
> xt driver: beam shift is DC coils

- plugins/cli_rgb.py
Since that the filter is a local axis, the plugin didn't work, as any
change of the filter was reverted by the local axis.
=> Use the local axis to change filter.
Also use user-friendly display of the filter name.
> plugins cli_rgb: fix filter not applied

- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
- Add check that relative move is still in focus range in _doMoveRel()
- Replace unit test linked stage/focus to be taken from model.getComponent()
- Use single value for movement target to simplify real HW testing
> Fixes to CryoSECOM Linked Focus stage after HW testing

- src/odemis/gui/cont/tabs.py
Some left over from adjustments.
> gui cont tabs SecomAlign: remove unused variable

- src/odemis/acq/drift/test/shift_test.py
Changed file name, change test class removed some unused lines.
> Corrected file name and test name in shift_test.py (tests MeasureShift)

- install/linux/usr/share/odemis/sim/optical-sim.odm.yaml
- install/linux/usr/share/odemis/sim/secom-sim-pretty.odm.yaml
- install/linux/usr/share/odemis/sim/secom-sim.odm.yaml
New power API, so need to have a list.
The simplest way is to remove the property, to make sure it's not turned
on at init.
> install: fix secom-pretty

- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
- added time estimation for image acquisition
- added get and set resolution from xtadapter
- added Detector and Dataflow
- xt image acquisition with threads
- moved commented out code in Scanner to end of class
> XT client add support for acquiring SEM images

- src/odemis/driver/technolution.py
Please merge this one first in the row of PR's for the tech_wrapper.
> Prevent stopping the calibration loop while it is inactive.

- src/odemis/driver/technolution.py
- src/odemis/driver/test/technolution_test.py
Please merge this one second in the row of PR's for the tech_wrapper.
> Update the external storage URL formatting in setter and tests

- doc/develop/backend-api.rst
A few new VAs, and some clarifications.
> doc: update a little bit the API description

- util/groom-img.py
Remove unused code, which fixes running the script with Python 3 as
one of the unused import has changed names.
Simplify/clarify a little bit the code too.
> util groom-img: modernize

- plugins/zstack.py
Changing the filter-wheel for the emission can take several seconds.
That's typically way longer than a FM acquisition and moving the focus.
So if there are several streams, acquired serialy for each focus
position, the Z stack can get very slow.
=> Detect that there is a filter wheel, and in this case acquire each
stream seprately for the entire focus range.
> plugin zstack: in case of filter-wheel, acquire stream separately

- src/odemis/gui/cont/tabs.py
- src/odemis/gui/util/__init__.py
…he tab components based on stage position (imaging, loading..)
Subscribe to stage position on alignment tab and call enable_cryo_tab_on_stage_position
> Enable Cryo tabs on Imaging Mode

- install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
- src/odemis/acq/stitching/_tiledacq.py
- src/odemis/acq/stitching/test/tiledacq_test.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/test/comp_slider_test.py
- src/odemis/gui/win/acquisition.py
- src/odemis/gui/xmlh/xh_delmic.py
- src/odemis/model/_metadata.py
- Add an extra parameter zsteps for the focus.z positions
- Create zstack for the given focus levels
- Compress all the zstack into a single image, using “maximum intensity projection”
> Support "compressed Z-stack" acquisition in TiledAcquisitionTask

- src/odemis/gui/comp/buttons.py
Essentially a backport of a fix from wxPython 4.0.7 .
> gui comp buttons: avoid some assertions error when double clicking on ImageButtons

- src/odemis/driver/actuator.py
> driver actuator: fix Exception with extra parameters

- src/odemis/cli/main.py
We used the user friendly version. However, the standard user doesn't
look at this metadata, in the first place. So it's nicer to have
something that matches the microscope files and the Python code.
> cli: use the standard MD_* names for the metadata

- src/odemis/gui/model/dye.py
Now the data also contains some &amp; and &quot;.
Let's convert them too.
> gui model dye: Also fix the other HTML characters in the fluodb

- src/odemis/gui/util/img.py
No behaviour change, just rename variables to clarify that there aren't
really any differences between "image" and "background", they are just
image A and image B.
> gui util img: clarify merge_tiles()

- src/odemis/acq/move.py
- src/odemis/acq/test/move_test.py
Move lens aligner to its DEACTIVE position before the following cases:
- Stage referencing
- Moving to coating
- Moving to milling
> ENZEL: Ensure lens safety by moving aligner to its DEACTIVE position 

- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
- Fix linked focus direct relative shift value
- Add unit tests for direct focus abs and rel moves
- Add additional unit test for cancelling linked stage
> Small fixes to Linked Focus movements 

- src/odemis/gui/comp/text.py
With the addition of the combo-box to select the colourmap, the text
got quite small. It's pretty much impossible to read anything in the
dropdown, especially as it has a bigger text.
=> Force to have min width. 300 px works well in test.
> gui comp text SuggestTextCtrl: make the dropdown at least 300px width

- src/odemis/driver/tfsbc.py
Metadata are given in a different order from the xt server. It's easier to use the same order here.
> tfsbc.py: modify order of transform function arguments

- src/odemis/driver/xt_client.py
- assert always returned True, fixed the assert and added a message
- the SEM returns the pitch in um the VA is in m, fixed this in the updateSettings
> Fix pitch in the MultiBeamScanner

- doc/develop/enzel-roles.svg
- doc/develop/microscope.rst
@lazem I added the text description of enzel components and the enzel diagram. I also listed the metadata of each components as suggested in the task specifications. I tested it by compiling to the HTML and pdf formats. Will appreciate feedback!
> Pull request for adding enzel model to the developer documentation 

- plugins/cli_rgb.py
Avoids the user to reselect the filter every time Odemis is restarted.
This also gives a good example of how to use a config file in a plugin.
> plugins cli_rgb: store filter settings in config file

- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
I am planning to test this one extra time on the 11th of March.
This PR needs to be merged simultaneously with: https://bitbucket.org/delmic/xtlib-adapter/pull-requests/28
> Change pitch to deltaPitch and update docstring of delta pitch

- scripts/spot-grid.py
- Supports to load image from command line
- Indicator of first spot in the image
- 'Snake' to indicate order of spots
> Updated spot-grid.py script

- install/linux/usr/share/odemis/sim/sparc2-tc-hh400-sim.odm.yaml
- src/odemis/driver/picoquant.py
- src/odemis/driver/test/picoquant_test.py
Provided by Eric Liu and Jacob Ng from ORNL.
> driver picoquant: add support for HydraHarp 400

- install/linux/usr/share/odemis/hwtest/focustracker.odm.yaml
- src/odemis/driver/FocusTracker.eds
- src/odemis/driver/focustracker.py
- src/odemis/driver/test/focustracker_test.py
Only one VA: .position
It listens to the device updates, so receives the position as soon as
it's generated.
Also handle connection issues.
Extend the simulator to generate TPDOs
> driver focustracker: update to simplified device

- src/odemis/acq/acqmng.py
> acqmng: fix sorting FM stream order

- src/odemis/driver/pmtctrl.py
- src/odemis/driver/test/pmtctrl_test.py
* During the live update, horizontal stripes are observed due to the activation of pmt protection while acquiring.
* By delaying a little bit the protection, it is not set when the stream stops and starts quickly. The pmt protection is activated when the acquisition is completed.
> Bug fix: Delay pmt protection to avoid activating it during the acquisition

- src/odemis/gui/comp/miccanvas.py
- src/odemis/gui/comp/overlay/base.py
- src/odemis/gui/comp/overlay/view.py
- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/comp/viewport.py
- src/odemis/gui/test/comp_overlay_test.py
- src/odemis/gui/test/dev_rotknob_test.py
For FastEM, it's easier to use a VA, so the ROI controllers can subscribe to it.
> gui overlay: make .active a BooleanVA

- plugins/ar_spectral.py
It wouldn't work when called from another tab (eg, analysis).
Fixed it to probably work from any tab, but it gets confusing anyway,
and untested, so request the user to select the acqusition tab.
> plugins ar_spectral: check the Acquisition tab is selected

- src/odemis/gui/cont/tabs.py
* Untoggled Manual Focus button --> pause the streams before calling Sparc2ManualFocus
> Bug fix: Pause the streams before opening the slit in Manual Focus

- src/odemis/driver/zeiss.py
Sometimes the SEM takes a bit of time to answer (eg, 3s). We would wait
at most 1s (and weirdly, always wait for an extra second).
This could cause incorrectly errors.
In addition, if this ever happened, the answer which would eventually
come wouldn't be flushed, causing the responses to be read after the
wrong command.
=> always try to read a whole line, and on error, flush the input.
Also change the simulator to use a separate thread, in order to be able
to simulate such error, and therefore check that the code works.
> driver zeiss: handle better delay in answer

- src/odemis/acq/fastem.py
Specification of the gui/acqmng interface
> FastEM acquisition model and fake acquire function

- src/odemis/gui/comp/text.py
If the text search is not found at the beginning of a the choices,
try to find the first choices which contains the text *somewhere*.
> gui comp text SuggestTextCtrl: try harder finding the text

- src/odemis/gui/cont/tabs.py
As the stage can move from outside the chamber tab, we need to prevent its progress bar from updating when the movement is not originating from its provided position switching controls. Also make start, end, target and current positions private.
> ENZEL: Prevent chamber tab progress bar from updating on outside movement

- src/odemis/gui/cont/tabs.py
Don't try to rename the previous folder, just create a new one.
The only exception is if the previous folder is empty.
Also fix the issue that the automatically generated folder name was
inside the previous folder.
> gui cont tabs CryoChamberTab: on new project, just create a new folder

- src/odemis/driver/xt_client.py
The maximum scale depends on the minimum resolution. Putting a scale
bigger fails, so let's limit it.
Also make sure the pixel size is recomputed every time the FoV changes.
> driver xt_client: fix max scale and pixel size computation

- src/odemis/driver/technolution.py
- src/odemis/driver/test/technolution_test.py
> driver technolution: rename openapi_server -> technolution_asm

- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
With XTToolKit, it's possible to change the immersion mode using the
compound_lens_focusing_mode.
> driver xt_client: add immersion mode support

- src/odemis/driver/test/xt_client_test.py
Use the same was as the orsay test case: add an extra state to
TEST_NOHW=sim. This indicate we are testing agains the simulator.
In such case, all test cases are safe to run, so run them all.
Also fix a few test cases to be compatible with the simulator.
> driver xt_client test: extra option to run with the adapter simulator

- src/odemis/driver/test/xt_client_test.py
- src/odemis/gui/cont/acquisition.py
ValueError string argument needs to be passed with '%' not ','.
> driver-xt_client_test/cont-acquisition: bugfix error message

- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
Allows to set different (less frequent) referencing, even disable it.
> driver actuator RotationActuator: add argument ref_on_move_count to override the default 5

- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
When the underlying actuator provide these VAs, it's handy to have them.
Also fix the .reference() function to pass the right axes names.
> driver actuator ConvertStage: add .speed and .referenced

- src/odemis/driver/andorshrk.py
> driver andorshrk: fix log message

- src/odemis/driver/andorcam3.py
We sort of pretend that the temperature can be changed between -10 and
25°C, but in practice on some hardware, like the Zyla, we end up picking either -10 or 25.
With the latest SDK (3.15.30045.0), it's also possible to select 0°C.
=> At least, log that only some temperatures are actually working.
Also make sure we return the actual target temperature.
Also indicate in the automatic temperature logging the cooling status.
> driver andorcam3: improve temperature control

- src/odemis/driver/smaract.py
A timeout error can happen if the movement of some axes pulled others slightly out of their position, and because they are not expected to move by the kinematics (e.g. the x-positioners in  case of a pure y movement), they go back to their position very slowly, causing the movement event to time out. As a fix for this, the same movement will be tried again.
> Fix Smaract 5DOF stage timeout issue internally

- install/linux/usr/share/bash-completion/completions/odemis-cli
- src/odemis/cli/main.py
- src/odemis/cli/test/main_test.py
Some users find that thinking in degrees is easier than radians... so
let's accomodate them.
> cli: show angles also in degrees, and support movement in degrees

- src/odemis/gui/comp/viewport.py
The bug would show up when zooming in the overview window during the acquisition
> viewport: bug fix  

- install/linux/usr/share/odemis/hwtest/orsay.odm.yaml
- src/odemis/driver/orsay.py
- src/odemis/driver/test/orsay_test.py
All changes made to code that was already merged based on the hardware tests
> Orsay hardware test results

- src/odemis/driver/piezomotor.py
As we read .position directly, but the internal position was already
inverted (for inverted axes), the values didn't match. When computing
the distance between current and target positions, if the move happened
to be near its opposite position (eg, moving from 0.01 to -0.01), it
would seem that the distance is very short, so the duration short too.
The actual move could also be moved incorrectly, in relative move only.
=> Read the position and apply the inversion to compare the same type of
values.
Also simplify the code by passing the shifts, which is what we really
care.
Also support computing the estimated duration on open-loop.
Also make sure to stop all the axes from moving as soon as possible in
case of cancellation (instead of stopping just one).
> driver piezomotor: fix timeout on inverted axes moves

- scripts/spot-grid.py
* New cli option --magnification
* If no magnification is specified, try to use lens magnification
* If lens cannot be found, fall back to 50
* In case a magnification is specified which is NOT the lens specification, a warning will be logged (but we will still use the cli-specified value)
> spot_grid.py: options to select magnification

- src/odemis/driver/technolution.py
- src/odemis/driver/test/technolution_test.py
* illegal character -> actually allowed characters
* fix bug in characters: capital characters are also allowed for megafield id according to API
* add method to add subdirectories on external storage (such as project and date folders) - This is needed by the GUI, which will automatically create a folder with the current date to store all data. Additonally, the project name is stored on this VA by the GUI.
* add testcases for subdirectory
* raise ValueError when wrong characters are detected - let the caller decide how to handle the error
* raise ValueError for incorrect input when checking if a megafield exists. Otherwise, it is hidden whether now the megafield does not exist or just a wrong input was provided.
* improve test cases for ftp url: make sure every if statement is actuall …
> technolution wrapper: some updates and fixes

- src/odemis/gui/cont/acquisition.py
If an acquisition is started successfully after a failed acquisition, the label still showed "Acquisition failed" during the entire process. Instead, after pressing the acquire button, it should return to showing the estimated time.
> fastem-gui-overview: bugfix time estimate label

- src/odemis/acq/stitching/_simple.py
We should also be able to use this feature with the high-level function.
> stitching: add adjust_brightness argument to weave() function

- src/odemis/acq/stream/_live.py
> streams: syntax error in exception

- src/odemis/gui/cont/microscope.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
* better icon for ebeam button
* chamber button: don't show pressure on the button, it's confusing
> fastem-gui: chamber tab improvements

- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/cont/acquisition.py
- src/odemis/gui/cont/streams.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/model/__init__.py
* bugfix ROC: couldn't be selected at high zoom level
* only enable calibration buttons for scinitallators selected in chamber tab
* use storage path from asm
> Fastem acquisition tab: diverse improvements

- scripts/ar_to_csv.py
This is a script to convert raw AR data to Theta/Phi data in CSV format.
Requested by a user, but also a nice example on how to open data, and
export it.
> scripts: new ar_to_csv script

- src/odemis/acq/acqmng.py
- src/odemis/acq/test/acq_test.py
- src/odemis/gui/cont/acquisition.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/util/comp.py
- src/odemis/util/driver.py
- src/odemis/util/test/comp_test.py
This PR contains all the acquisition panel including the zstack capability. All the code related to the zstack acquisition is only in the second commit (3951cfa).
> Enzel acquisition panel with zstack acquisition manager 

- src/odemis/gui/cont/streams.py
Some plugins may use the SPARC stream, without having a spotStream.
Playing the stream for now causes an error. Instead, allow it, even if
there is not active SEM spot, so it's not super useful, it's better
than failing.
> gui cont streams: don't fail to start/stop stream if no spotStream

- src/odemis/gui/comp/stream.py
- src/odemis/gui/comp/text.py
- src/odemis/gui/cont/streams.py
Also, names only have to be unique within a project.
> streams: only allow whitelisted characters for fastem ROAs

- src/odemis/gui/cont/acquisition.py
It should show the date of the current day if the gui was open overnight.
> gui: update path in FastEMAcquisitionController

- src/odemis/gui/cont/tabs.py
This PR contains the adjustments made for localization tab of meteor, and a change that had to be made during the hardware test.
> Adjust localization tab for meteor

- doc/develop/microscope.rst
- install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
- src/odemis/acq/stitching/_tiledacq.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/win/acquisition.py
- src/odemis/gui/win/test/acquisition_test.py
- src/odemis/model/_metadata.py
I made this separate branch out of master for the commits related to the overview acquisition. I cherry-picked the relevant commits from the PR #1880 and the PR  #1901. Basically, this PR could be merged separately. But  i think it would be a good idea to run the same test cases on meteor system once the PR of meteor chamber tab is merged.
> Adjust overview window

- src/odemis/gui/comp/miccanvas.py
- src/odemis/gui/comp/overlay/view.py
- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/test/comp_overlay_test.py
Extend CrossHairOverlay to handle showing only horizontal & vertical lines + allow the size of the line to be given (not just the crosshair size)
> Extend CrossHairOverlay 

- src/odemis/acq/test/acq_test.py
- src/odemis/util/comp.py
- src/odemis/util/test/comp_test.py
These are fixes for the errors found in the last test cases run.
> Test case bugs fixes

- src/odemis/driver/smaract.py
- src/odemis/driver/test/smaract_test.py
I ran the test cases, they ran without errors. 
I added one test case. Kind of a trick test. I am not sure if it is effective, and if it guarantees that the test on hardware will work fine.
> auto update focuser position

- src/odemis/util/test/spot_test.py
SciPy 0.19 is provided by Ubuntu 18.04 and SciPy 1.3 is provided by Ubuntu
20.04. Original commit was tested against Scipy 1.6.2.
> Bugfix unittest compatibility SciPy 0.19 and 1.3

- src/odemis/driver/rigol.py
It's typically not an issue, but convenient in the test cases.
Because the simulator would start multiple times. If the previous one is
not closed fully, the next one cannot start, which gives false
positives.
> driver rigol: terminate simulator more reliably

- src/odemis/gui/cont/tabs.py
We ask before moving to FM, let's do the same when requesting to move to SEM.
> gui cont tabs CryoChamberTab: on METEOR also ask confirmation to move to SEM

- src/odemis/acq/move.py
- src/odemis/acq/test/move_test.py
- src/odemis/gui/cont/tabs.py
The code was very hard to confirm that every case would be handled.
Now, it's clear what happens.
In particular, it should now handle cases where the current position is
UNKNOWN.
Also merge METEOR and ENZEL constants.
> acq move: simplify _doCryoSwitchSamplePosition() and related functions

- install/linux/usr/share/odemis/sim/meteor-sim.odm.yaml
Adjust positions so that the initial position (0,0,0,0,0) happens to be
the SEM position. That's not very realistic, but typically on a real
system, when Odemis start the stage is already in the SEM position.
Also much more handy for testing.
> config: update meteor sim

- src/odemis/driver/semcomedi.py
We used to run the garbage collector between two acquisitions.
For short acquisitions (eg, 10ms), as a GC run takes about 15 ms, that
would be quite costly. Especially, during a GC run, the entire Python
interpreter is non-responsive. So if during that time came a request
just to read or write any VA, that request would be blocked.
This caused the SPARC acquisition to get ~15ms overhead after every
acquisition.
=> Run the GC while we are waiting for the hardware. During that time,
we really have not much to do. Also limit the number of collections, and
if the acquisition is short, only do a simple collection.
> driver semcomedi: run the garbage collector while waiting the for the acquisition

- src/odemis/acq/stream/_sync.py
No need to update the image *every* time we receive one. It'll only be
displayed from time to time anyway. It would cause ~ 2ms extra time
per frame. That's not a lot, but with a short exposure time such as 10ms,
that's worthy to save.
> acq stream SEMCCDMCStream: reduce frequency of CCD live update

- src/odemis/acq/fastem.py
- src/odemis/acq/fastem_conf.py
- src/odemis/acq/stream/_live.py
- src/odemis/acq/test/fastem_test.py
- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
- src/odemis/gui/cont/acquisition.py
Megafield, overview, and livestream acquisitions need different settings of the scanner. The new function sets these values based on keyword arguments which can be passed through a dictionary.
> fastem: hardware configuration

- src/odemis/gui/cont/microscope.py
Automatic movement of the stage depending on the pressure is very
specific to the Delphi, so move the code to the Delphi class.
This mostly solves issue with opening the GUI when starting a SECOM/SEM/FM
with pressure control.
> gui cont microscope: move Delphi code to DelphiStateController

- src/odemis/acq/align/spot.py
Change of class attribute lookup to instance attribute lookup
> Bugfix introduced in PR #1898

- src/odemis/acq/move.py
Fix issue introduced in PR #1929
> METEOR: Fix mirroring equation using dict axis keys instead of index number

- src/odemis/driver/andorcam2.py
Separate the "Stopped" and "Acquiring" states into two functions.
Most importantly, this simplifies the code to stop the camera, and fixes
the fact that the camera never stopped acquiring due to the wrong
indentation level for the stop code.
> driver andorcam2: fix camera constantly acquiring and refactor acquisition loop

- src/odemis/driver/smaract.py
If the axis is not connected to the controller, the driver would fail
with a SA_CTLError, which would stop the whole backend.
Instead, raise a HwError, so that the backend knows it could try again,
if the user connects the axis.
> driver smaract: raise HwError if axis is not connected

- src/odemis/acq/move.py
Add cryoSwitchAlignPosition future as a sub-future to cryoSwitchSamplePosition so it'd be cancellable when called from there.
> Make cryoSwitchAlignPosition cancellable

- install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml
- src/odemis/acq/test/fastem_conf_test.py
This file seems to have gotten lost for pr #1884 (maybe when squashing commits).
> fastem acquisition: configure scanner test cases

- src/bugreporter/odemis_bugreporter.py
In case of failure: make it clearer what are the alternatives.
In case of success: fix the pop up message appearing only a 10th of a
second.
> bugreporter: improve messages after sending the bug

- src/odemis/acq/test/fastem_test.py
- src/odemis/driver/technolution.py
150us have proven to be enough for the flyback, so change the default value on the VA.
> technolution driver: update the flyback time

- src/odemis/acq/fastem.py
- src/odemis/acq/test/fastem_test.py
- src/odemis/gui/cont/acquisition.py
Split off calculating the position of the first tile, so it does not get calculated for each field, but only once.
> Added image translation pre-align and autofocus before ROA acquisition.

- plugins/timelapse.py
The main difference is that the name of the tab is different.
Also, the .acquisitionStream attribute is slightly different.
This is enough to get the plugin working.
> plugins timelapse: add support for ENZEL and METEOR

- src/odemis/gui/test/comp_canvas_test.py
The test cases assumed that when a green and a blue stream were added the resulting image would be 1/3 green, 2/3 blue, while it is half green and half blue.
In test_pyramidal_zoom added a precision for checking the mpp. The precision still needs to be checked, because I am not sure what the correct prescision is, but the test only passes with places=6.
> Fixes for comp canvas tests.

- src/odemis/model/_futures.py
When the batch future was used to represent the progress of multiple futures, only for the first future the progress in the overall progress was correctly shown. As soon as the first future was finished, the updated end of the batch future was incorrectly calculated. The same start of the future was used plus adding the remaining time for the not yet finished futures. Thus, the end time of the batch future moved closer to the start in time. As a result, the GUI displayed always "a few seconds left" for the remaining futures that still needed to be executed.
> batch future: fix the progress update

- src/odemis/driver/semcomedi.py
Update the state if the DAQ board cannot be recovered.
This helps to adjusts the user expectations, instead of letting him/her
find out that no SEM image will every come.
Also try a gentle recovery first. Mostly because the current
reset_device() code seems to sometimes cause more damage than help.
Unfortunately, this type of comedi error happens very rarely, so it's
very hard to reproduce.
> driver semcomedi: report that the DAQ board has an error

- src/odemis/acq/align/delphi.py
- src/odemis/util/__init__.py
- src/odemis/util/spot.py
- src/odemis/util/test/util_test.py
Based on the discussion during the code golfing.
> util: improve *_almost_equal() functions

- src/odemis/util/mock.py
Add .shape, .readoutRate, .pixelSize, and metadata, to simulate everything needed by
the align.find_overlay functions.
Also needed for the coming MDUpdater test cases.
> util mock: Extend FakeCCD to be more realistic

- install/linux/usr/share/odemis/sim/fastem-sim.odm.yaml
> config: fix error in fastem-sim

- src/odemis/driver/smaract.py
The rotational ranges are passed in rad, but internally, degrees are
used. So the ranges have to be converted.
This caused some very small rotations to fail with
ERROR_POSE_UNREACHABLE.
> driver smaract: fix MC5DoF simulator range for rotational axes

- install/linux/usr/share/odemis/sim/sparc2-pl-sim.odm.yaml
This new module cannot be used from the GUI yet, but it's already working from the command line.
> config: add SPARCv2 simulator with PL module

- src/odemis/acq/align/fastem.py
- src/odemis/acq/fastem.py
> fastem-improvements-acq-calib

- src/odemis/gui/cont/tabs.py
- src/odemis/gui/model/__init__.py
Only check the stage-bare on METEOR, as that's the only place it exists.
Handle the new THREE_BEAMS position properly.
> gui: fixes for ENZEL

- src/odemis/driver/zeiss.py
Some system report magnification up to 2M x. For now, on such system,
starting Odemis when the magnification is > 500K would fail.
=> Change the default range to 2M x, and allow to change the range
further just from the microscope file.
> driver zeiss: increase magnification range

- src/odemis/gui/cont/fastem_acq.py
Bug introduced in commit 43b86fe85ffb41b48a2937b7abccb8d225dc7f17
> FASTEM: bug fix acquisition (don't pass detector rotator anymore in caller)

- install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
- src/odemis/acq/test/move_test.py
- src/odemis/dataio/test/stiff_test.py
- src/odemis/dataio/test/tiff_test.py
- src/odemis/driver/test/andorshrk_test.py
- src/odemis/gui/util/test/img_test.py
@Sabrina85 @pieleric It seems both of you where involved in one of these files this PR changes.
> Fixing test cases, 5 small commits for different failing test cases.

- src/odemis/acq/drift/test/shift_test.py
Force the "randomness" to always be the same one so that the tests
always pass or fail, independent of when you're running them.
> acq drift test: improve reliability

- src/odemis/acq/align/coordinates.py
Just small code simplification, to make it clearer.
> acq align coordinates: direclty use .max() and .min()

- doc/develop/microscope.rst
> doc: Add METEOR roles and update ENZEL

- src/odemis/util/units.py
From code golf session (only kepts the non-crazy part)
> util units: simplify round_down_significant and improve docstring

- install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
- src/odemis/acq/align/test/z_localization_test.py
- src/odemis/acq/align/z_localization.py
- src/odemis/gui/cont/acquisition.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/model/__init__.py
To select the stigmator angle, start a localization, and report the
result to the user.
Also add the actual procedure as a Future, in odemis.acq.align.z_localization.
> gui: add Z localization widgets

- src/odemis/acq/fastem.py
- src/odemis/acq/test/fastem_test.py
- src/odemis/driver/technolution.py
- src/odemis/driver/test/technolution_test.py
- src/odemis/gui/cont/fastem_acq.py
> Technolution add custom calibration metadata

- src/odemis/driver/orsay.py
- src/odemis/driver/test/orsay_test.py
Two TODO are left because they should be improved in the future.
> Getting the orsay test cases to pass again

- src/odemis/util/angleres.py
We used one pixel too little on each side.
Also fix the comment to reflect the actual ranges used.
> util angleres: fix discontinuity in AR projection around phi=0

- src/odemis/model/_vattributes.py
> FIX Missing "s"/letter in startswith causing an error at startup of the back-end

- src/odemis/driver/test/technolution_test.py
Added a check if technolution packages are available, if not skip the test.
> add check on importing required packages in technolution_test

- src/odemis/acq/stitching/_weaver.py
- src/odemis/acq/stitching/test/weaver_test.py
Split up getFullImage() into three functions: get_bounding_boxes, weave_tiles and update_md.
get_bounding_boxes and update_md are the same for each different Weaver class, therefore I moved them to the base class.
Each class now has a weave_tiles function, which only contains the code that is actually specific for that class.
This clean up will make it easier to update the code and add support for rotated tiles.
> Acquisition stitching: Cleaned up weaver code and test cases.

- src/odemis/odemisd/test/main_test.py
- src/odemis/util/test/util_test.py
Added test cases for the functions that does not have tests yet in util.__init__.py
> add missing tests

- src/odemis/driver/orsay.py
- src/odemis/driver/test/orsay_test.py
- src/odemis/model/_metadata.py
Because of rebasing the old PR onto another branch became unreadable. Since Odemis_adjust_new_api is now merged this PR can also be directly merged into master.
The old PR can be found here: https://github.com/Kleijwegt/odemis/pull/3
> Aperture Orsay driver

- src/odemis/util/dataio.py
- src/odemis/util/test/dataio_test.py
Refactored _splitplanes to improve readability and make the code shorter. This was part of a software knowledge coding exercise.
Added test cases to ensure the code still behaves as expected.
> util dataio: refactored _split_planes and added test cases

- install/linux/usr/share/odemis/sim/meteor-sim.odm.yaml
- src/odemis/acq/stitching/_weaver.py
- src/odemis/acq/stitching/test/weaver_test.py
- src/odemis/gui/win/acquisition.py
- src/odemis/util/img.py
- src/odemis/util/test/img_test.py
This PR is based on https://github.com/delmic/odemis/pull/2156 , so that PR should be reviewed first
> Rotated tiles overview image

- src/odemis/driver/test/smaract_test.py
Update from loaner stage to actual stage.
> driver smaract test: update for actual SmarPod HW model

- src/odemis/dataio/csv.py
- src/odemis/dataio/test/csv_test.py
added test case for missing functionality
> csv export function refactor for readability of code

- src/odemis/acq/acqmng.py
- src/odemis/acq/align/autofocus.py
- src/odemis/acq/stream/_base.py
- src/odemis/acq/stream/_static.py
- src/odemis/cli/main.py
- src/odemis/dataio/hdf5.py
- src/odemis/driver/semcomedi.py
- src/odemis/driver/simulated.py
- src/odemis/driver/spectrapro.py
- src/odemis/driver/static.py
- src/odemis/driver/test/tlfw_test.py
- src/odemis/gui/acqmng.py
- src/odemis/gui/comp/legend.py
- src/odemis/gui/comp/slider.py
- src/odemis/gui/conf/util.py
- src/odemis/gui/cont/settings.py
- src/odemis/gui/cont/streams.py
- src/odemis/gui/model/__init__.py
- src/odemis/gui/util/widgets.py
- src/odemis/model/_core.py
- src/odemis/model/_vattributes.py
- src/odemis/odemisd/modelgen.py
- src/odemis/util/__init__.py
- src/odemis/util/conversion.py
- src/odemis/util/driver.py
- src/odemis/util/fluo.py
- src/odemis/util/test/fluo_test.py
- src/odemis/util/units.py
The former method is deprecated and support will be removed in python 3.10.
> Replace "from collections import ..." with "from collections.abc import ..."

- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
Let's make the precision to 4 numbers, as the user cares up to 0.1°C,
and the temperature is around -150°C.
> gui xrc: ENZEL temperature control should allow 0.1°C control

- src/odemis/driver/lakeshore.py
- src/odemis/driver/test/lakeshore_test.py
- util/lksconfig
Updated the lakeshore 335 simulator as 350. Added PID controller code and a utility for it, namely lksconfig.
> Lakeshore 350 simulator and PID controller

- src/odemis/driver/tescan.py
- src/odemis/driver/test/tescan_test.py
Safer relative move by computing the target position based on the
position when starting the move, not when requesting the move (which
could be a lot before if another move is running).
After asking to move, first wait a bit, to ensure it doesn't think
the move already finished.
Not sure if any of these will help the fact that sometimes an
(absolute) move request has no effect.
> driver tescan: improve move handling

- src/odemis/odemisd/start.py
Sometimes looking for the short message goes wrong, and hundreds of
lines are found. That make the whole message window too big.
=> Detect such case, and shorten the message by only showing the beginning
and end.
> odemisd start: Make sure that the short error message is always short

- src/odemis/driver/xt_client.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1159
> [update] added debug log for successful connection to xtadapter

- install/linux/usr/share/odemis/hwtest/orsay.odm.yaml
Add new components, and update roles based on the new names.
> config: update orsay microscope file

- src/odemis/driver/simsem.py
without raising error if not present
> checks for pixel size metadata in simsem.py

- src/odemis/acq/test/stream_test.py
The checks on the filter axis were confused. In particular, it assumed
that the current filter position was not the second position randomly
picked... which was sometimes incorrect. Also, the axis takes typically
1.1s to move. So 1s is too short to wait.
> acq stream test: fix SettingsStreamsTestCase.test_cl_ss

- src/odemis/acq/align/test/spot_test.py
> FindGridSpots: add unitest that checks the correct rotation is returned for rotated spots

- src/odemis/gui/doc/mimas_alignment.html
Part of the MIMAS alignment tab, but got forgotten during history
rewrite.
> gui doc: add mimas alignment description

- install/linux/usr/share/odemis/sim/mimas-sim.odm.yaml
Adjust the simulator to contain all the grid positions, which will be
used soon.
> config mimas sim: add grid positions

- src/odemis/util/cluster.py
- src/odemis/util/registration.py
* Moved k-means clustering code to separate file.
* Transparently handle k-means++ initialisation in wrapper function instead of in caller.
> Refactoring of k-means clustering code

- src/odemis/util/graph.py
- src/odemis/util/registration.py
- src/odemis/util/test/graph_test.py
* Added DisjointSetUnion data structure
* Added AntiSymmetricGraph class
* Added functions to determine the minimum and maximum spanning tree of a graph
* Added a function to iterate over all connected vertices in a graph in depth first order.
* Added a function to check if a graph is connected
* Made `iter_triangles` and `remove_triangles` functions instead of class methods.
> Refactoring and new functionality of odemis.util.graph

- src/odemis/odemisd/test/mdupdater_test.py
Simple test for the lens observer... more tests can come later.
> odemisd: add test for mdupdater

- src/odemis/util/graph.py
- src/odemis/util/registration.py
- src/odemis/util/test/registration_test.py
Updates to `odemis.util.registration` to improve estimation of grid orientation in case of an incomplete grid.
> Partial grid estimation

- src/bugreporter/odemis_bugreporter.py
Now that we have YAML files that can include other YAML files, it gets
really tricky to know which files to include. It's also not a big
issue to have a few more microscope files. That actually pretty much
always useful.
=> In addition to the MODEL or MODEL_SELECTOR content, also always
include all the YAML files from /usr/share/odemis/. It's still useful
to include MODEL and MODEL_SELECTOR in case they point to files out
of this directory.
> bugreporter: always store all the YAML files from /usr/share/odemis

- install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
- src/odemis/acq/align/roi_autofocus.py
- src/odemis/acq/align/test/roi_autofocus_test.py
- src/odemis/acq/stitching/_tiledacq.py
- src/odemis/acq/stitching/test/tiledacq_test.py
- src/odemis/gui/win/acquisition.py
- src/odemis/util/linalg.py
- src/odemis/util/raster.py
- src/odemis/util/test/linalg_test.py
add test cases to support autofocus overview acquisition
test cases for roi_autofocus_test.py
test cases for finding autofocus in _tiledacq.py
test cases to support plane fitting in linalg.py
add metadata in enzel sim microscope file
> Test cases to support autofocus functions

- src/odemis/acq/align/roi_autofocus.py
- src/odemis/acq/align/test/roi_autofocus_test.py
- src/odemis/acq/stitching/__init__.py
- src/odemis/acq/stitching/_tiledacq.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/win/acquisition.py
- util/generate_xrc.py
**Checked on Simulation**
Create autofocus chekbox iwhich runs autofocus in the given roi and provides fixed number of focus points to tiled acquisition. 
This can be only merged after the below PR has been merged.
https://github.com/delmic/odemis/pull/2342
> Implement GUI Autofocus checkbox 

- src/odemis/acq/millmng.py
- src/odemis/acq/test/millmng_test.py
Milling manager script with its test cases
> Milling manager

- scripts/spot-grid.py
- src/odemis/util/test/transform_test.py
- src/odemis/util/transform.py
Initial commit - to be tested and discussed
> Update callers of FindGridSpots

- src/odemis/acq/millmng.py
- src/odemis/acq/test/millmng_test.py
Only accept tuple of 2 floats.
Also improve the test cases to actually properly check the values are
set correctly.
> acq millmng: make MillingSettings more picky about pixel_size type

- src/odemis/driver/orsay.py
- src/odemis/driver/test/orsay_test.py
The actual beam shift has to
be adjusted for each probe current, so that the center of the FoV
corresponds to the same point. Also, every time the probe current is
changed, it's reset. We don't want to pass this trouble to the higher
level code. So the "base" shift for each probe current is stored (and
shared via MD_SCAN_OFFSET_CALIB), and it's hidden in the ion-beam.shift, so that a
shift of N µm always stays, even if the current changes.
The fib_beam.shift still allows to observe/affect the low-level value of
the shift.
> driver orsay: hide ion-beam.shift complexity

- src/odemis/acq/align/test/roi_autofocus_test.py
Fixing failing test case @sneepstefan 
roi_autofocus_test.py::RoiAutofocusTestCase::test_autofocus_in_roi on Ubuntu 20
> Stage switched to FM imaging mode

- src/odemis/gui/cont/streams.py
- src/odemis/gui/cont/tabs.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1126
> Sdev 1126 add contrast brightness sliders for overview acquisition

- scripts/cl_acquisition.py
Complete overall of the script to replace the old synchronization based
on the e-beam scanner trigger to a fully software-based synchronization.
It's slower but a lot more reliable, with any kind of hardware and
software.
Also copy a lot of the latest code from the standard SPARC acquisition
to simplify of make it more reliable.
> scripts cl_acquisition: update to use more standard acquisition method

- src/odemis/gui/comp/legend.py
- src/odemis/gui/comp/viewport.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1377
> added stage position legend

- src/odemis/acq/test/millmng_test.py
SWM-80 Fix failing milling manager test cases
> remove additional time, set the stage to loading before milling

- src/odemis/gui/comp/buttons.py
src/odemis/gui/test/comp_stream_test.py::FoldPanelBarTestCase::test_add_stream
/home/testing/development/odemis/src/odemis/gui/comp/buttons.py:1038: DeprecationWarning: NewId() is deprecated
> wx.NewID() to wx.Window.NewControlId() fix

- doc/develop/coding-guidelines.rst
Having a naming convention for pull requests, branches and commits helps the collaborators better understand the developer's changes
> [add] naming convention for pull requests, branches and commits

- plugins/tabs_enabler.py
Add plugin to enable tabs and add the function to enable alignment tab on enzel, sparc, secom and mimas through "Enable alignment tab" button under Help > Development on the top bar.
https://delmic.atlassian.net/browse/CSDM-1059
> [CSDM-1059] add tabs enabler plugin

- src/odemis/util/linalg.py
remove distance of focus points from the borders of given bbox in linalg.py. As focus points are on borders, the borders are also in focus.
> [perf] add focus points on the edges of bounding box in overview acquisition

- install/linux/usr/share/odemis/sim/meteor-zeiss-sim.odm.yaml
- plugins/meteor_engage_warn.py
- plugins/mimas_chamber_safe.py
- src/odemis/acq/align/test/roi_autofocus_test.py
- src/odemis/acq/millmng.py
- src/odemis/acq/move.py
- src/odemis/acq/path.py
- src/odemis/acq/test/millmng_test.py
- src/odemis/acq/test/move_test.py
- src/odemis/acq/test/path_test.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/model/__init__.py
- src/odemis/gui/util/__init__.py
- src/odemis/util/driver.py
Extend acq.move to detect which type of Meteor is used for moving
METEOR-624
Task -> https://delmic.atlassian.net/browse/METEOR-624?atlOrigin=eyJpIjoiMWM5YWZjODQ4Yjk0NDVkNWJjYzFlZjJhYjVlODJiZTEiLCJwIjoiaiJ9
> Modularize stage movement

- src/odemis/gui/comp/miccanvas.py
- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/cont/project.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1557
A video can be found attached in the ticket for proof.
> [SDEV-1557] the calibration 2 and 3 boxes can be moved only in the respective scintillator canvas area

- src/odemis/gui/comp/miccanvas.py
- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/comp/stream.py
- src/odemis/gui/cont/fastem_acq.py
- src/odemis/gui/cont/project.py
- src/odemis/gui/cont/tabs.py
Cleaned up code for the issue when sometimes calibration 2 and 3 ROC boxes pop up randomly in the canvas. Also when calibration or acquisition button are pressed disable any mouse events for calibration 2 and 3 ROC boxes.
https://github.com/delmic/odemis/pull/2504 needs to be merged first before reviewing this PR
> [SDEV-1556] refactor code 1

- src/odemis/acq/fastem.py
Previously when an acquisition was cancelled it would return without cancelling the pre-calibrations (in execution), this has been fixed.
Ticket: https://delmic.atlassian.net/browse/SDEV-1143
> [SDEV-1143] cancel the pre-calibration on acquisition cancel

- src/odemis/acq/fastem.py
- src/odemis/acq/fastem_conf.py
- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/cont/fastem_acq.py
- src/odemis/gui/cont/project.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/model/__init__.py
https://github.com/delmic/odemis/pull/2508 needs to be merged first before reviewing this PR
The refactoring in this PR is mostly based on making use of FastEMCalibration which contains calibration related attributes
> [SDEV-1556] refactor code 2

- src/odemis/gui/cont/fastem_acq.py
- src/odemis/gui/cont/project.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1277
https://github.com/delmic/odemis/pull/2509 needs to be merged first before reviewing this PR
> [SDEV-1277] region 1 missing will block the acquistion from starting on scintillator 2

- src/odemis/gui/comp/canvas.py
- src/odemis/gui/comp/overlay/world.py
- src/odemis/gui/comp/popup.py
- src/odemis/gui/cont/streams.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/util/widgets.py
All GUI configurations are tested on Ubuntu 22.04 and found bugs were addressed.
Tested configurations are:
- SECOM
- ENZEL
- METEOR
- SPARCv1
- SPARCv2
- FAST-EM
- MIMAS
- DELPHI
> [SWM-113] Ubuntu22 fixes GUI

- src/odemis/acq/fastem.py
- src/odemis/util/driver.py
- src/odemis/util/test/driver_test.py
add logging to monitor the duration of a stage movement
> [SDEV-1523] logging fastem acquisition: add stage logging

- .github/workflows/self_hosted_runner.yml
Ticket: https://delmic.atlassian.net/browse/SWM-120
> [ci] add ubuntu 22.04 vm to the self hosted runner matrix

- src/odemis/driver/test/technolution_test.py
Many of the ASMDataFlow test cases where failing because we were not properly waiting for images to be received. Now instead of sleeping an arbitrary amount of time the code waits until the data is received, if it is not receieved within a specified time the test case times out.
> [SDEV-1509] fix: technolution ASMDataFlow test cases

- src/odemis/acq/test/millmng_test.py
Update the functions calls for stage movement in millingmng_test.py
> [fix] use stage movement functions calls from posture manager

- src/odemis/util/test/img_test.py
Fixes DeprecationWarning in img_test.py random number generation
> [SWM-138] [fix] img_test.py DeprecationWarning: This function is deprecated

- install/linux/usr/share/odemis/sim/meteor-tescan-sim.odm.yaml
- src/odemis/acq/move.py
- src/odemis/acq/test/move_test.py
- src/odemis/driver/actuator.py
- src/odemis/driver/test/actuator_test.py
Support Tescan stage translation for Meteor
Major changes:-
- Create Tescan stage movement class in move.py
- Create more support for the rotation and shear for the Linked YZ in actuator.py
> [feature] Tescan meteor stage implementation

- src/odemis/driver/actuator.py
Indroduce 3D shear to be used by Covert3DStage class
> [fix] fix the conversion in ConvertStage actuator class 

- src/odemis/driver/test/xt_client_test.py
- src/odemis/driver/xt_client.py
aymore.
TFS removed reading and setting the aperture index from their interface. As we do not use it anyway, it is save to remove it. Also removed the TODO about the beamlet index updating when changing the multibeam, because the beamlet index is not updated when the multibeam mode is changed.
> [fix] xtclient remove aperture index as it is not supported by TFS 

- debian/control
- debian/odemis.postinst
- install/linux/lib/udev/rules.d/99-fastem-serial.rules
- util/ftdiprog
* Added utility to program EEPROM with custom manufacturer and product description.
* Added udev rules that use these for consistent USB enumeration.
> [feature] Improved handling of FTDI USB-to-serial converters

- plugins/meteor_engage_warn.py
- src/odemis/acq/move.py
- src/odemis/gui/cont/tabs.py
during stage switching from fm to sem imaging mode, previous rx value in sem imaging is restored
> [perf][METEOR-527] save tilt and rotation of sem position

- .github/workflows/syntax_check_cloud.yml
To automatically check for syntax errors and old style classes with GH instead of only echo these messages in the terminal.
> [feat] added syntax_check_cloud.yml to workflows

- util/release-odemis
This script is really ad-hoc for releasing Odemis on Ubuntu, but as it's
exactly what we do with Odemis, that's handy.
> [feature] add release-odemis utility

- .gitignore
- src/odemis/gui/cont/correlation.py
- src/odemis/gui/cont/export.py
- src/odemis/gui/cont/tabs.py
- src/odemis/gui/main.py
- src/odemis/gui/main.xrc
- src/odemis/gui/main_xrc.py
- src/odemis/gui/model/__init__.py
This PR adds:
- Correlation Tab
- Manual Overlay controls for correlation between images
- Export controller for exporting overlaid images.
> [METEOR-810] Manual overlay of FLM and SEM images (Correlation Tab)  

- plugins/fastem_roa_import_export.py
- src/odemis/gui/comp/stream.py
- src/odemis/gui/cont/project.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1761
> [SDEV-1761] odemis plugin to import export csv file with definitions of roas

- plugins/quickcl.py
- src/odemis/gui/cont/settings.py
- src/odemis/gui/cont/stream.py
- src/odemis/gui/cont/stream_bar.py
- src/odemis/gui/cont/tabs/analysis_tab.py
- src/odemis/gui/cont/tabs/correlation_tab.py
- src/odemis/gui/cont/tabs/enzel_align_tab.py
- src/odemis/gui/cont/tabs/fastem_acquisition_tab.py
- src/odemis/gui/cont/tabs/fastem_chamber_tab.py
- src/odemis/gui/cont/tabs/fastem_overview_tab.py
- src/odemis/gui/cont/tabs/localization_tab.py
- src/odemis/gui/cont/tabs/mimas_align_tab.py
- src/odemis/gui/cont/tabs/secom_align_tab.py
- src/odemis/gui/cont/tabs/secom_streams_tab.py
- src/odemis/gui/cont/tabs/sparc2_align_tab.py
- src/odemis/gui/cont/tabs/sparc2_chamber_tab.py
- src/odemis/gui/cont/tabs/sparc_acquisition_tab.py
- src/odemis/gui/cont/tabs/sparc_align_tab.py
- src/odemis/gui/plugin/__init__.py
- src/odemis/gui/test/comp_stream_test.py
- src/odemis/gui/win/acquisition.py
[refactor] create a streams subpackage in odemis.gui.cont, all the classes earlier in odemis.gui.cont.streams.py have been split into individual python files under the odemis.gui.cont.streams subpackage.
The refactoring will result in a better file structure.
NOTE: https://github.com/delmic/odemis/pull/2629 needs to be merged first before reviewing this PR
> [refactor] odemis gui cont streams.py file

- src/odemis/gui/cont/correlation.py
- src/odemis/gui/cont/tabs/cryo_chamber_tab.py
- src/odemis/gui/cont/tabs/localization_tab.py
- src/odemis/gui/main_xrc.py
- src/odemis/gui/xmlh/resources/panel_tab_correlation.xrc
Features:
- Sync correlation and localization streams
- Allows selection of feaures in combined clem map
> [METEOR-811] Add CLEM map to localization tab for feature selection

- src/odemis/gui/cont/correlation.py
[fix] check the availability of data at two places in correlation.py
> [fix] bugs in meteor for odemis v3.4 release

- src/odemis/util/img.py
- src/odemis/util/test/img_test.py
[fix] apply_flood_fill algorithm
remove the need for an overflow_counter and clean-up the code
> [SDEV-1822] fix flood fill algorithm

- .github/workflows/self_hosted_runner.yml
the logs are now generated locally on the ci server
> [ci] updated yaml file to parse the logs

- src/odemis/acq/move.py
- Fixes an issues where users couldn't swap between grids while in FM imaging mode. (https://support.delmic.com/scp/tickets.php?id=1453#reply)
> [fix] Error moving between grids while in FM imaging mode

- src/odemis/gui/cont/correlation.py
- src/odemis/gui/main_xrc.py
- src/odemis/gui/xmlh/resources/panel_tab_correlation.xrc
Minor improvements to Correlation Tab UI based on user feedback
- Consoldated dx, dy controls into a single Translation control
- Improved clarity of instructions and controls
> [fix][METEOR-1001] improve correlation tab instructions and controls

- src/odemis/gui/cont/correlation.py
- src/odemis/gui/model/tab_gui_data.py
Add the ruler tool to the correlation tab for measuring features
> [feat][meteor-1016] add ruler tool to correlation tab

- src/odemis/acq/align/test/z_localization_test.py
- src/odemis/acq/align/z_localization.py
- src/odemis/gui/cont/acquisition/cryo_z_localization.py
- src/odemis/gui/main_xrc.py
- src/odemis/gui/xmlh/resources/panel_tab_localization.xrc
> [feature][METEOR-727] select the z stream for the Localization z and cancel localization z

- src/odemis/acq/fastem.py
The pre-calibrations can fail due to some dirt on the sample, therefore retry it 3 times in a slightly different location, before failing completely.
> [refactor] Retry FAST-EM pre-calibrations 3 times in case of failure.

- src/odemis/gui/comp/overlay/ellipse.py
- src/odemis/gui/comp/overlay/polygon.py
- src/odemis/gui/comp/overlay/rectangle.py
- src/odemis/gui/comp/overlay/shapes.py
NOTE: https://github.com/delmic/odemis/pull/2701 must be reviewed and merged first
> [SDEV-1827] undo redo shape drawing action

- install/linux/usr/share/odemis/sim/sparc2-streakcam-sim.odm.yaml
- src/odemis/driver/keysight.py
- src/odemis/driver/test/keysight_test.py
This is a draft PR, will be updated soon.
> [TRCL-213] add keysight awg 33600 series driver

- src/odemis/acq/stream/_static.py
Add a static stream for FIB acquisitions
> [FEAT]: Add StaticFIBStream

- src/odemis/acq/feature.py
- src/odemis/acq/test/feature_acq_test.py
- src/odemis/acq/test/feature_test.py
- src/odemis/gui/cont/acquisition/cryo_acq.py
- src/odemis/gui/main_xrc.py
- src/odemis/gui/xmlh/resources/panel_tab_localization.xrc
- src/odemis/util/driver.py
- src/odemis/util/test/driver_test.py
This PR adds the ability to acquire images at the pre-selected feature sites. The stage will move to each feature site, set the focus and acquire using the current stream settings.
> [FEAT] [METEOR-863] Acquire at Feature Positions

- src/odemis/gui/cont/tabs/cryo_chamber_tab.py
Currently, when starting the odemis-gui for meteor it automatically creates a new project directory. User's have requested that we allow them to specify the new project or select an existing project to load.
> [METEOR-1208][REFACTOR] Allow the user to select whether to create or load a project on init

- src/bugreporter/odemis_bugreporter.py
- src/bugreporter/test/odemis_bugreporter_test.py
Currently, we often request data from user's after they have submitted a bug report. This PR adds the ability for the user to attach additional files (typically images) related to the bugreport
> [FEAT] Allow user to add attachments to bugreporter

- install/linux/usr/share/odemis/sim/meteor-sim.odm.yaml
- src/odemis/odemisd/mdupdater.py
In the yaml file - filter wheel has new metadata
> [feature][METEOR-1095] Integrate lateral chromatic correction metadata in Odemis

- src/odemis/acq/feature.py
- src/odemis/gui/cont/acquisition/cryo_acq.py
Fixes some minor issues with auto acquisition of features
- Z-stack checkbox not correctly implemented
- Add feature name and status to image description to for auto feature acquisition
> [FIX] Minor issues with auto feature acquisition

- plugins/chromatic_correction.py
Tune the parameters based on the hardware testing
> [perf] decrease the z slices acquisition for chromatic correction

- src/odemis/driver/piezomotor.py
JIRA Ticket: https://delmic.atlassian.net/browse/SDEV-974
> [perf] make use of ParallelThreadPoolExecutor so that stage moves in x and y simultaneously

- src/odemis/acq/fastem.py
With the volume EM changes the ROA name does not have to be unique anymore. Since the beamshift correction save path was only based on the ROA name, this caused all the images of a project to be saved in the same directory, and fields with the same id got overwritten. This fix extends the save path to include the project name, the roa name and the slice idx.
> [fix] Make the beamshift correction save path unique

- src/odemis/gui/comp/overlay/fastem.py
The _view_to_phys() call sometimes incorrectly converts the view coordinates to physical coordinates (different scale, shift in view) and as a result of this the calibration box size changes. Removing the _view_to_phys() call from on_left_down and on_left_up resolves it. On the other hand call _phys_to_view() call from on_left_up which will set the physical calibration box coordinates to view coordinates. Only on_motion is allowed to call _view_to_phys() when dragging is ongoing.
Ticket: https://delmic.atlassian.net/browse/SDEV-1930
> [fix] remove _view_to_phys() call from on_left_down and on_left_up

- install/linux/usr/share/odemis/sim/meteor-fibsem-sim.odm.yaml
- src/odemis/driver/autoscript_client.py
- src/odemis/driver/test/autoscript_client_test.py
- src/odemis/driver/xt_client.py
Adds an autoscript version of the xt-client for openfibsem based control of the fibsem
Server side: https://bitbucket.org/delmic/xtlib-adapter/pull-requests/84
> [METEOR-960][FEAT] Add autoscript client for openfibsem control

- src/odemis/gui/conf/licences.py
- src/odemis/gui/cont/acquisition/cryo_acq.py
Refactor licence file:
- Migrate to separate .py file
- Add flags for individual features
- Add expiry date to licence
> [refactor][METEOR-1254]Licence file refactor

- .github/workflows/unit_tests_cloud.yml
- scripts/meteor-interpolate-data.py
- src/odemis/util/interpolation.py
- src/odemis/util/test/interpolation_test.py
Adds the interpolation utility for z-stacks
[Specification](https://docs.google.com/document/d/1jBcJvvXyR41V0lCOaPBpqwRypYJ5xOTpkHsQYWiQa4c/edit?tab=t.0#heading=h.r7i4xprpd0oz)
> [feat][METEOR-1250] Add z-stack interpolation for METEOR data 

- install/linux/usr/share/odemis/sim/meteor-fibsem-sim.odm.yaml
- src/odemis/driver/autoscript_client.py
- src/odemis/driver/test/autoscript_client_test.py
- src/odemis/driver/xt_client.py
- src/odemis/model/_metadata.py
Minor client fixes/updates from hardware testing
> [fix][METEOR-960] Minor client fixes from testing

- src/odemis/gui/comp/miccanvas.py
Add control modifier for meteor focus control for large focus movements
> [feat] add control modifier for meteor focus

- src/odemis/acq/align/tdct.py
- src/odemis/acq/align/test/tdct_test.py
Adds a check to skip testing if tdct not installed
> [fix] check if tdct is installed, gracefully fail and skip tests

- src/odemis/gui/cont/acquisition/fastem_acq.py
This feature adds toggle buttons for calibration regions, this allows the user to show and hide calibration regions
FVEM-27
> [FVEM-27] [feat] Add visibility toggle for calibration regions

- src/odemis/acq/stitching/test/tiledacq_test.py
_____________________ CRYOSECOMTestCase.test_estimate_time _____________________
tiledacq_test.py:499: in test_estimate_time
self.assertTrue(min_total_time <= tiled_acq_task.estimateTime() <= 1.30 * min_total_time)
E   AssertionError: False is not true
> [fix] acquisition time in estimate_time test case for tiled acquisition

- src/odemis/driver/autoscript_client.py
Client side fix for server side change to FIB current API: https://bitbucket.org/delmic/xtlib-adapter/pull-requests/89/overview
> [fix] client side fix for fib beam currents

- src/odemis/acq/stitching/_weaver.py
- src/odemis/acq/stitching/test/weaver_test.py
For SEM-FM guided correlation, we want to use the stage-bare metadata to pre-transform the images. However, overview (stitched) images do not correctly store this metadata (it is currently set as the first tile metadata).
This PR adds a calculation to get the stage-bare position for the overview image as a whole, and add it to the metadata.
> [fix][METEOR-1332] Add stage-bare position to stitched image metadata

- src/odemis/driver/test/tescan_test.py
After updating Tescan's SharkSEM API to the latest version, we encountered a flaw in the cancelation process. The test suite was failing for both the old and new version of the API. Recent changes to the SharkSEM API (not visible in this PR) should fix the behavior. 
This regression test  verifies that of the Odemis side of things. A long duration acquisition is canceled quickly after starting, and then immediately a new shorter acquisition is started. If the duration of the second acquisition is less than the remainder of the initial acquisition, we know it's not blocked by an unsuccessful cancel of the first acquisition.
> [feat][METEOR-1340] Tescan 'cancelation' regression test

- plugins/fastem_import_roi.py
- src/odemis/gui/comp/fastem_project_manager_panel.py
NOTE: Please wait for https://github.com/delmic/odemis/pull/3074 to be merged first before reviewing this PR
- MetadataPage
- NpyPage
> [FVEM-6] load image coordinates as rois

- src/odemis/driver/autoscript_client.py
- src/odemis/driver/xt_client.py
Implement check version for the autoscript adapter
Tested on the hardware
> [METEOR-1425][fix] log autoscript adapter version in xt_client.py

- src/odemis/gui/comp/overlay/polygon.py
- src/odemis/gui/comp/overlay/rectangle.py
- src/odemis/gui/comp/overlay/shapes.py
Support ticket: https://support.delmic.com/scp/tickets.php?id=2106
> [fix] unable to draw shapes rectangle ellipse

- plugins/chromatic_correction.py
fix in chromatic aberration plugin
Unused channels were treated as strings but the value of unused channels were in list of floats
> [fix] treat unused channels as list of floats

- install/linux/usr/share/odemis/hwtest/tescan-fib.odm.yaml
- install/linux/usr/share/odemis/hwtest/tescan-sem.odm.yaml
- src/odemis/driver/tescan.py
- src/odemis/driver/test/tescan_test.py
- src/odemis/gui/conf/data.py
- src/odemis/gui/cont/settings.py
This pull request introduces full FIB support to the TESCAN driver, expands configuration options, and refactors core components to support both SEM and FIB modes more cleanly.
- Added a standalone configuration file for FIB.
- Removed legacy code from the SEM configuration.
- Switched to name-based detector selection for clarity and maintainability.
- Refactored SharkSEM API calls to route through a unified device handler.
- Made detector and scanner logic reusable across SEM and FIB.
- Improved acquisition stability by simplifying the cancellation flow and enforcing stricter use of the existing lock mechanism.
- Enabled bitdepth control through the VA system.
- Introduced presets for setting FIB voltage and current.
- Added a method to trigger automatic brightness and contrast …
> [MSD-47] [feature] Add FIB Support to TESCAN Driver

- src/odemis/odemisd/test/start_test.py
Also fixed _gui_thread deamon typo -> daemon
Previous raised exception
File "/home/testing/development/odemis/src/odemis/odemisd/start.py", line 726, in main
starter = BackendStarter(odemis_config, options.nogui)
File "/home/testing/development/odemis/src/odemis/odemisd/start.py", line 253, in __init__
self._notif = get_notify_object()
File "/home/testing/development/odemis/src/odemis/odemisd/start.py", line 141, in get_notify_object
notify2.init("Odemis")
File "/usr/lib/python3/dist-packages/notify2.py", line 95, in init
dbus_obj = bus.get_object('org.freedesktop.Notifications',
File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
return self.ProxyObjectClass(self, bus_name, object_path,
File …
> [fix] notify2 org.freedesktop.Notifications related dbus.exceptions.DBusException by patching it and mocking its methods

- install/linux/usr/share/odemis/sim/meteor-tfs3-sim.odm.yaml
- src/odemis/acq/move.py
- src/odemis/acq/test/move_test.py
- src/odemis/model/_metadata.py
Overrides PR #3202 , with small fixes
> Fix fm imaging fixed z on tfs
