delmic/odemis

src/odemis/driver/picoquant.py, src/odemis/driver/test/picoquant_test.py, src/odemis/gui/cont/tabs.py
Makes the pico harp at least working in simulation mode, for raw data (only),
and avoid hard coding the fiber alignment to the spectrometer.
=> Allow fiber alignment with the PicoHarp

src/odemis/gui/util/img.py
On some data with some specific metadata, the stream sorting would fail with such error:
ERROR   log:37: Failed to export a spatial view as PNG
:
File "/usr/lib/python2.7/dist-packages/odemis/gui/util/img.py", line 1843, in images_to_export_data
view_hfw[1], last_image.metadata['date'], streams_data, last_image.metadata['stream'] if (not rgb) else None, logo=logo)
File "/usr/lib/python2.7/dist-packages/odemis/gui/util/img.py", line 1395, in draw_export_legend
sorted_data = sorted(streams_data.items(), key=operator.itemgetter(1))
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8e in position 0: invalid start byte
It seems to only happen when multiple stream have the same acquisition time and the metadata was directly
set from an acquisition (instead of being read from a file).
I …
=> gui util img: fix legend export chopping on non UTF8 text

src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py, src/odemis/util/img.py, src/odemis/util/test/img_test.py
Update the function util.img.rescale_hq to support RGB images and images with more than 2 dimensions in general.
Added the support to generate pyramidal images. Added the dataio.tiff.write_image function.
=> Pyramidal write tiff pr

src/odemis/dataio/test/stiff_test.py, src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py, src/odemis/model/__init__.py, src/odemis/model/_dataio.py, src/odemis/model/_metadata.py, src/odemis/util/conversion.py, src/odemis/util/test/conversion_test.py
Extension of the odemis.dataio.tiff module to provide new API so that it's possible to
open a TIFF file containing pyramidal images and access just a sub-part of the data.
=> Random access in TIFF pyramidal data

src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py, src/odemis/model/_dataio.py
and AcquisitionData, and creation of DataArrayShadowTIFF class.
DataArrayShadow inherited much of the functionality from the
AcquisitionData class.
Public function of the new DataArrayShadow are:
getData: reads an entire image.
getTile: reads a tile, given a X, Y, and a zoom level.
The DataArrayShadowTIFF instance now has the handles of the tiff files.
=> Reorganization of DataArrayShadow and AcquisitionData

src/odemis/acq/stream/__init__.py, src/odemis/acq/stream/_base.py, src/odemis/acq/stream/_static.py, src/odemis/acq/test/stream_test.py, src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py, src/odemis/gui/comp/miccanvas.py, src/odemis/gui/cont/acquisition.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py, src/odemis/model/_vattributes.py, src/odemis/model/test/vattributes_test.py, src/odemis/util/dataio.py, src/odemis/util/img.py, src/odemis/util/test/dataio_test.py, src/odemis/util/test/img_test.py
The StaticStream class and the derived classes now can receive
DataArrayShadows.
The Stream class now has .rect and .mpp members. .rect stores the region
of the image that is being viewed by the GUI. .mpp stores meters per
pixel of the current viewer.
=> Extension of StaticStream objects to support pyramidal data update

src/odemis/acq/stream/_base.py, src/odemis/acq/stream/_static.py, src/odemis/acq/test/stream_test.py, src/odemis/util/img.py
Fix the generation of the rectangle that determines which tiles should be loaded from file.
The generation was not considering that, in physical coordinates, Y grows up, and in pixel coordinates, Y grows down.
=> Fix the generation of the rectangle that determines which tiles should be loaded from file.

src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py
Created DataArrayShadowPyramidalTIFF, and use DataArrayShadowTIFF.__new__ to decide which class to instantiate. It solves the issue of deleting the class on Windows.
=> Created DataArrayShadowTiledTIFF

src/odemis/acq/stream/__init__.py, src/odemis/acq/stream/_base.py, src/odemis/acq/stream/_static.py, src/odemis/acq/test/stream_test.py, src/odemis/dataio/tiff.py, src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/model/__init__.py, src/odemis/gui/test/comp_canvas_cairo_test.py, src/odemis/gui/test/comp_canvas_test.py, src/odemis/gui/test/comp_viewport_test.py, src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py, src/odemis/util/test/img_test.py
Extension of Viewport widget to support pyramidal StaticStreams.
The information of the field of view and meters per pixel is getting to the Stream classes. This information is used to calculate which tiles will be read from the TIFF files (or other types of tiles that implement tiling).
So far, there's only one Stream for all the viewports. So changes in the field of view and meters per pixel of one view port is still affecting all the others viewports.
=> Extension of Viewport widget to support

src/odemis/acq/stream/__init__.py, src/odemis/acq/stream/_base.py, src/odemis/acq/stream/_projection.py, src/odemis/acq/stream/_static.py, src/odemis/acq/test/stream_test.py, src/odemis/dataio/tiff.py, src/odemis/gui/comp/canvas.py, src/odemis/gui/cont/acquisition.py, src/odemis/gui/cont/streams.py, src/odemis/gui/model/__init__.py, src/odemis/util/dataio.py, src/odemis/util/img.py
The goal of the DataProjection is to separate the projection process of
the Stream from the data and settings.
Separate the projection from the Stream is specially useful on tiled
images, providing the possibility of having different projections with
different selection of tiles (different mpps and viewports), with the
same stream.
=> Inclusion of data projection classes

src/odemis/acq/stream/__init__.py, src/odemis/acq/stream/_projection.py, src/odemis/acq/stream/_static.py, src/odemis/dataio/test/tiff_test.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py, src/odemis/util/dataio.py
- Addition of custom listeners to VAs on RGBSpatialProjection. 
- Getting the inner stream from DataProjection on some places.
- Fixes on the automated tests.
- Moved the extraction of the image data from the DataArrayShadow on the constructors of Static2DStream and RGBStream
=> Fixes on the inclusion of a DataProjection

scripts/cl_acquisition.py
The cl_acquisition script was not running due to this bug. The center of the ROI was not computed correctly. Please check, but I believe this is the correct code.
=> Script bug: Corrected - to +

src/odemis/driver/test/cam_test_abs.py, src/odemis/driver/ueye.py
Follow a structure much closer to what the ueyedemo program does.
The uEye lib seems to handle all the thread issues by itself, as well
as most of the reconnections of the camera. The previous code attempted
to also handle the same issues (as it was based on similar code for
other camera libraries which don't handle such corner cases). It appeared
to cause extra issues. In particular, doing a fast stop/start of the DataFlow
would often result in stall of ~15s.
The new code might handle less properly event synchronisation, but for now
there is no user of this functionality in Odemis.
Tested on the Thorlab camera and the IDS camera used for the SPARC compact.
Also tested on a real SPARC compact, with a PMT board connected too.
=> driver ueye: Complete reorganisation of the acquisition function

src/odemis/acq/stream/__init__.py, src/odemis/acq/stream/_sync.py, src/odemis/gui/comp/grid.py, src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/cont/acquisition.py, src/odemis/gui/cont/streams.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/cont/views.py, src/odemis/gui/model/__init__.py
Fixes for FLIM.
Fixes
- SPARC, SECOM, Delphi are working. Further ongoing testing is still ongoing.
- Rep control moved to stream controller
- Dwell time VA does not affect ROA overlay
- Dead object errors fixed
- FLIM stream merge ratio  fixed
- Overview working
- Incompatible tool modes disabled on some displays
Some issues still persist:
- It is possible to set a pixel size and refresh it, but somehow the ROA recalculation still hampers the ease of use
- ROI selected by default in SPARC
=> FLIM Fixes

src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py, src/odemis/util/spectrum.py
When reading older files saved with Odemis, the image might have higher dimensions
with CTZ=1. When reading the MD Odemis will add MD_TIME_LIST and MD_WL_LIST,
which one value. When exporting the data again, this was raising an issue.
MD_TIME_LIST and MD_WL_LIST are only saved now, if there are actually
higher dimensions of the image.
=> streakcam: export tiff minor update

src/odemis/dataio/__init__.py
Removed the catmaid specific code in the previous PR but forgot to remove the import.
=> remove catmaid import from dataio init

src/odemis/dataio/test/csv_test.py
This fix works, since the test data had no dimension metadata and this is now needed (and provided by projections) to determine what data is exported.
=> Fix for CSV Test

src/odemis/driver/pigcs.py, src/odemis/driver/test/pigcs_test.py
- E709 has "Z" as axis name instead of an int, made changes so axis can also be a string
- fixed bug, set self._hasRefSwitch instead of self._hasLimitSwitches when HasRefSwitch throws a NotImplementedError
=> Updated pigcs driver to work with E709 controller

doc/INSTALL.txt
- comedi was previously hosted at comedi.org and is now hosted at github.com
=> Updated urls to comedi git repositories in install instructions.

src/odemis/acq/path.py
Previous bugfix wasn't working correctly. For each future, we must remember the axis in order to check if it has been referenced.
=> acq path: bugfix addendum

src/odemis/driver/omicronxx.py
In the (very rare) case that a recoverable error is detected on the
master node, a reset is attempted. However, the hack to always reset
the master went wrong, and afterwards, the master is set as "child 0",
which doesn't exists, and confuses the rest of the communication.
=> copy the previous channel value, so we are certain to restore it
properly.
It would be shown in such trace:
2019-05-07 10:45:22,642 (omicronxx) INFO: Device (on port /dev/ttyFTDI0) reports error 0x1 (latched 0x801), will reset it
2019-05-07 10:45:22,642 (omicronxx) DEBUG: Sending: '?RsC\r'
2019-05-07 10:45:22,658 (omicronxx) DEBUG: Received: '!RsC'
2019-05-07 10:45:22,658 (omicronxx) WARNING: Answer too short after setting RsC: RsC
2019-05-07 10:45:23,658 (omicronxx) DEBUG: Received: ''
:
2019-05-07 10:45:31,666 …
=> driver omicronxx: fix incorrect channel if reseting the master

plugins/ar_spectral.py, plugins/cl_tcorr_acq.py, scripts/monochromator-scan.py, src/odemis/acq/leech.py, src/odemis/acq/stream/_base.py, src/odemis/acq/stream/_helper.py, src/odemis/acq/stream/_live.py, src/odemis/acq/stream/_static.py, src/odemis/acq/test/stream_test.py, src/odemis/driver/andorcam3.py, src/odemis/driver/phenom.py, src/odemis/driver/semcomedi.py, src/odemis/driver/simcam.py, src/odemis/driver/simsem.py, src/odemis/driver/spectrometer.py, src/odemis/driver/tescan.py, src/odemis/gui/comp/slider.py, src/odemis/gui/conf/util.py, src/odemis/gui/cont/settings.py, src/odemis/gui/cont/streams.py, src/odemis/gui/model/__init__.py, src/odemis/model/_vattributes.py, src/odemis/model/test/vattributes_test.py, src/odemis/util/conversion.py, src/odemis/util/mock.py
* commit 96280d99eb6eb36a694b9e591aa4e8ee245fb0ef introduced some bugs due to unexpected behaviour of builtins.int
* the power operation is not working as it should in python2: 10 ** int(-9) = 0
* as a fix, we import past.builtins.long instead of builtins.int
=> python3 migration: long, part 2

src/odemis/driver/omicronxx.py
The sending of ad-hoc messages seems to only be governed by the "master"
device. However, that was the only one were we didn't disable it.
So it had no effect. In most cases, it's not a big issue, as the ad-hoc
messages are automatically discarded next time a response is read.
However, if many ad-hoc messages have been sent, they fill up the queue
of the serial port (in the Linux kernel), and prevent to get the
responce corresponding to the latest command.
=> driver omicronxx: also disable ad-hoc messages on the master

src/odemis/driver/npmc.py
Not tested yet.
Checks the identifier of the Newport to determine if it is the right device.
=> Newport ESP301 identifier fix

src/odemis/gui/comp/legend.py, src/odemis/gui/comp/viewport.py
Fixed:
* For the vertical legend, I'd suggest to change a little bit the rule
for displaying the "...". The problem currently is that it makes the
text really wide, and especially it tends to change when the character
is present or not (so the whole graph shifts). Instead of
appending/prepending the character, I'd suggest to just show that text
(and drop the original tick text).
* As soon as an axis is zoomed-in, the scale-lock should be activated.
Currently, if you zoom on a live stream, pretty much nothing happens,
because the scale automatically unzooms on the next data received. You
can notice it for instance with a sparc backend, when you play the live
spectrum (in the acquisition tab). If you zoom in, it automatically
zooms out.
* When dragging the mouse with the left button, the …
=> Spectrum zoom fixes

src/odemis/dataio/test/catmaid_test.py
The test was failing with ValueError: No stack info at this url https://fafb.catmaid.virtualflybrain.org/2/stack/2/info, check project id 2 and stack id 2
virtualflybrain.org moved the project from project id 2 to project id 1 and from stack id 2 to stack id 1
=> changed project id 2 to 1 and stack id 2 to 1 for virtualflybrain url

src/odemis/gui/evt/__init__.py
We had a "super clever" way to generate events.
So clever that the new "super clever" functions of wxPython 4 got completely confused,
and the attributes were lost.
=> Make everything explicit. It makes it work on wxPython 4, and it's also more obvious
so that you don't have to be "super clever" at the time that you read the code in order to understand it.
It should still be compatible with wxPython 3 (but untested)
=> gui evt: Fix Knob Events with wxPython 4

src/bugreporter/odemis_bugreporter.py, src/bugreporter/test/odemis_bugreporter_test.py
The zipfile.writestr() function requires "bytes" (ie, non-unicode) on Python 2
(on Python 3, strings are automatically encoded with utf-8).
This caused failure to send any bug report containing a non-ascii character. With
the name field, it's already pretty easy to trigger (eg, Éric).
=> Convert the string to bytes.
Also add a GUI test case to catch such issues.
=> bugreporter: Don't fail if description.txt contains non-ascii characters.

src/odemis/acq/align/find_overlay.py, src/odemis/acq/align/spot.py, src/odemis/acq/stream/_live.py, src/odemis/gui/cont/streams.py, src/odemis/gui/cont/tabs.py
Also make the hack even more hacky by only activating it on the SECOM.
On the SPARCs with blanker support, this would work "fine" for the SEM streams,
but as the MDStreams are not aware of the blanker, they would always leave it active.
Eventually, it's clear that this approach is not really right, and it's just a hack.
It should be changed to have the CompositedScanner to take care of automatically turning
on/off the blanker.
=> acq: automatically unblank the beam during calibration too

src/odemis/acq/stream/_helper.py
Little "thinko": we want the integrationTime to be the *smallest* between 24h and exposureTime * 10000
Currently, we used max(), so it was at least 24h, but in some cases, could be many days.
=> acq stream RepetitionStream: fix maximum integrationTime

src/odemis/acq/stream/_sync.py
Commit fba0061b31c8e (sync: Added live update during acquistion of MD streams) added live update
to many MDStreams but a typo broke SEMTemporalMDStream.
=> acq stream SEMTemporalMDStream: fix live update

src/odemis/acq/stream/_helper.py
Now that the GUI supports arbitrary long chronograms, no need to cropt the data.
It's actually useful to show extra data when the sync offset is large.
=> acq stream helper ScannedTemporalSettingsStream: don't crop the chronograms

src/odemis/gui/cont/streams.py
Same fix as done in commit 1003ae787bd (gui cont settings...)
This should be the last code with strftime("%c"...).
=> gui cont streams: Fix failure to show acquisition date on foreign locale

src/odemis/odemisd/modelgen.py
In case a driver fails to load because one of its import failed, the message
was (incorrectly) implying that the driver itself was missing.
=> pass the import error message as-is to be more precise in the log.
=> odemisd modelgen: on module import error, indicate which module failed to load

src/odemis/driver/hamamatsurx.py
Otherwise we get errors like:
ERROR: Hamamatsu streak camera TCP/IP image thread failed.
File "/home/sparc/development/odemis/src/odemis/driver/hamamatsurx.py", line 544, in _getDataFromBuffer
self.parent._delaybox._updateTriggerRate()
File "/home/sparc/development/odemis/src/odemis/driver/hamamatsurx.py", line 874, in _updateTriggerRate
triggerRate = int(triggerRate_raw[0])
ValueError: invalid literal for int() with base 10: '0.001'
Also update a little bit the log message to be clearer on which image we received
=> driver hamamatsurx: accept repetition triggers less than 1

src/odemis/gui/conf/data.py, src/odemis/gui/cont/tabs.py
On the time-correlator some of the main settings (ie, syncDiv) affect the output of the sub detectors (photo-detector*).
So show the syncDiv setting also on the alignment tab.
=> gui cont tabs: Sparc2Align tab should also show syncDiv setting for the labcube

util/piterminal
Also support ending with Ctrl+D (which is the default shortcut on bash and python shell)
=> util piterminal: Migrate to Python 3

plugins/tileacq.py
Commit c4aa101d ("fine alignment and other additions") modified the return value
of _get_acq_streams(). However, the caller was incorrectly adjusted. It caused
the memory check to not take into account the right streams. In some corner case, it would even fail.
=> Fix to use the "stitch_ss" part of _get_acq_streams()
=> plugins tileacq: fix memory estimation

src/odemis/gui/comp/text.py
None is not a number. It doesn't help anything to set a value to None.
Instead, all non valid text should be discared and reset to the previous value.
This avoids issues like:
File "/home/piel/development/odemis/src/odemis/gui/comp/slider.py", line 586, in _update_slider
Slider._SetValue(self, text_val) # avoid to update link field again
File "/home/piel/development/odemis/src/odemis/gui/comp/slider.py", line 457, in _SetValue
raise TypeError("Illegal data type %s" % type(value))
TypeError: Illegal data type <type 'NoneType'>
=> gui comp text: Don't set None as value if the text is empty

src/odemis/gui/log.py, src/odemis/odemisd/main.py
Use the same format for the GUI and the back-end.
Include the line number in the backend log too, as it's quite handy for debugging.
Use tabs, to separate and align the fields. It's easier to parse both for humans and machine.
Now the log looks like:
2019-10-25 10:27:15,433 WARNING actuator:1230:  Reporting axis x @ 0.0037107 (known position)
2019-10-25 10:27:15,534 DEBUG   tmcm:845:       Sending 1, 6, 8, 1, 0 (16)
=> Adjust log format

src/odemis/gui/util/img.py
It turned out that the metadata was properly exported... but the same colour as the background.
Typo introduced in commit 6a015fd7 (polarimetry: export for tiff, png and csv).
Can be backported to v2.10
=> gui util img: fix export of FM stream having no info in legend

src/odemis/gui/cont/acquisition.py
Only show the message after exporting, so if the export fails, the message is not shown.
=> gui cont acquisition SnapshotController: don't show a success message if saving failed

src/odemis/gui/cont/acquisition.py, src/odemis/gui/util/img.py
Commit 5e5fc732ba (implify code assuming that .raw is a list) changed the
way we store raw data of pyramidal data, from a tuple of tuple of raw tiles to
just a DataArrayShadow.
Some parts, related to the export were not updated. This caused saving snapshot
of pyramidal acquisition to fail.
=> Update the code to check for DataArrayShadow.
=> gui: handle pyramidal raw data properly

src/bugreporter/odemis_bugreporter.py
If the Odemis GUI has never run (because there's a bug?), then the config
directory is not present. The bug reporter wouldn't even start.
=> create the dir ourselves if needed.
=> bugreporter: don't fail if the config dir doesn't exists

src/odemis/driver/tmcm.py
It hasn't ever been properly tested. If a switch was on, it would actually
fail because some attributes are missing so early. In addition, it
would not even look for the correct switches (mixed up between axis number and
switch number).
=> The simulator now reports such a switch being turned on, to force the code
to be run during testing.
=> Move the code later in the init.
Also remove old TODO already implemented.
=> driver tmcm: fix to the reference switch initialisation

src/odemis/model/_futures.py
If several tasks finish at the same time, in some rare cases, there can be a race condition
which cause the _waiting_work.pop() to fail because the deque has already been emptied.
It show up like this:
2018-04-22 17:28:01,493 (_base) ERROR: exception calling callback for <Future at 0x7f460406f810 state=finished returned NoneType>
File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 300, in _invoke_callbacks
callback(self)
File "/home/sparc/development/odemis/src/odemis/model/_futures.py", line 200, in _on_done
self._schedule_work()
File "/home/sparc/development/odemis/src/odemis/model/_futures.py", line 139, in _schedule_work
w, f, dependences = self._waiting_work.pop()
IndexError: pop from an empty deque
=> Take the lock before …
=> model ParallelThreadPoolExecutor: fix (rare) IndexError when ending a task

src/odemis/gui/util/test/img_test.py
It appears to have been broken by commit c620e5d9760b (Distance tool),
but that's probably just because the change to the test cases caused
a reorder of the run. Now TestARExport is run early, before any other
test create a wx.App(). This is necessary as some of the export functions
use wxPython calls (which require an App to be available).
=> create explicitely a wx.App() at class start-up.
Also remove a few of these creations where it is not necessary anymore, as
the GuiTestCase already create one.
=> gui util img test: instantiate a wx.App() also for the TestARExport

src/odemis/gui/dev/powermate.py, src/odemis/odemisd/main.py, src/odemis/util/test/driver_test.py
The os module happens to import "sys", so the standard sys module can be used as "os.sys"... but it's just weird and confusing.
=> Don't use os.sys, but just sys

src/odemis/gui/comp/settings.py, src/odemis/gui/comp/stream.py
Commit e07417ad8 fixed setings.add_readonly_field(), but the code is
duplicated in the stream controller => also fix it there.
Also simplify the code, because unicode() can pretty much never fail
on random object... and if it fails it's not useful to have a message
that uses str(obj).
Also clarify a little the comment, as str is actually unicode, it's a
little confusing.
=> gui comp: also fix stream.add_readonly_field()

src/odemis/util/img.py
Simple numpy simlification/clarification... and it's twice faster :-P
More can be found with:
grep -IrE "len\(.*\.shape\)" src/
=> util img: len(array.shape) -> array.ndim

src/odemis/acq/test/stream_test.py
Now that there is the special integrationTime VA on the SPARC streams,
we have to be more careful on how the exposure time is set.
When exposureTime is not passed as detvas, integrationTime is
automatically created and used. So the raw detector .exposureTime is
*never* used, as we used to assume previously.
This caused many test cases to use the default exposureTime of 1s,
instead of way smaller values. So the test cases were very long to run.
Also merge/fix some of the live update test cases.
Also fix some of the integrationTime test cases.
Note: there is still a bug when live update is used at the same time at
integrationTime (on the metadata)
=> acq stream test: fix exposure time setting

src/odemis/acq/test/stream_test.py, src/odemis/driver/test/simcam_test.py, src/odemis/gui/test/comp_overlay_test.py, src/odemis/util/test.py
Unfortunately, numpy doesn't provide such function, and it's not really
obvious/easy to implement. We have at least 3 open-coded way to do it
now, so let's consolidate it.
=> util test: new assert_array_not_equal() helper function

src/odemis/acq/test/flim_test.py
The stream has been upgraded to use properly MD_TIME_LIST, instead of
the old hack MD_ACQ_DATE.
=> Need to also update the test case
=> acq test flim: fix test failing due to MD_ACQ_DATE

src/odemis/gui/comp/popup.py, src/odemis/gui/cont/acquisition.py
wxPython/GTK3 is broken with respect to the StaticText, which caused the
popup to only show the first few characters, cropped.
There might be way to fix/workaround these issues. However, the
wx.adv.NotificationMessage works very well now, so let's just use that.
=> gui comp popup: use the standard system message

src/odemis/gui/cont/streams.py
The optical path manager (OPM) is needed also for the
ScannedTemporalSettingsStreams, otherwise nothing in the optical path
is setup properly.
That's probably an omission from the very beginning when adding this
stream...
=> gui cont streams: Time Correlator stream should also have an OPM

src/odemis/driver/andorcam2.py
The error message is not in ex.strerr, but ex.strerror (which can be
abreviated anyway to ex). So whenever an unexpected error happened,
instead of logging it nicely and retrying, it would immediately fail
hard.
=> driver andorcam2: fix complete failure if unexpected error happens during acquisition

src/odemis/util/img.py, src/odemis/util/test/img_test.py
Very corner case. Still happened sometimes, causing such traces:
File "/usr/lib/python2.7/dist-packages/odemis/model/_vattributes.py", line 97, in notify
l(v)
File "/usr/lib/python2.7/dist-packages/odemis/util/weak.py", line 37, in __call__
return self.f(ins, *arg, **kwargs)
File "/usr/lib/python2.7/dist-packages/odemis/acq/stream/_base.py", line 969, in _onOutliers
self._recomputeIntensityRange()
File "/usr/lib/python2.7/dist-packages/odemis/acq/stream/_base.py", line 974, in _recomputeIntensityRange
self.auto_bc_outliers.value / 100)
File "/usr/lib/python2.7/dist-packages/odemis/util/img.py", line 111, in findOptimalRange
nval = cum_hist[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0
=> util img findOptimalRange: handle better empty histogram

src/odemis/gui/comp/canvas.py
It was an optimisation because typically if the canvas is disabled,
the user doesn't need to see the images... however that's not true.
For instance, in the SPARC we are going to get live update during
acquisition. During the acquisition the canvas is disabled, but we
still want to see the image.
=> Don't optimise, and always show images when the streams provide
new data.
=> gui comp canvas: Also update the display if the canvas is disabled

src/odemis/gui/comp/stream.py
Some widgets were added into the GridBagSizer with an incorrect span.
There should be 3 columns. However, sometimes we would add the widget
over 3 column, starting from the 2nd one. Apparently on GTK2, that
was no confusing, but now in GTK3, the GridBagSizer thinks we wanted
4 columns, and some widgets get placed weirdly.
=> gui comp streams: fix stream widgets not aligned on Ubuntu 18.04

src/odemis/gui/main.py, src/odemis/odemisd/main.py
Now that we support both Python 2 & 3, it'll probably come in handy to
know which interpreter was used when facing a bug.
=> Also log the Python interpreter version

src/odemis/driver/hamamatsurx.py
Without this, every time a new attempt to connect to the camera fails,
the connection thread would stay in the background waiting for some
message (which would never arrive).
=> driver hamamatsurx: close the connection on init failure

src/odemis/gui/comp/legend.py
It takes a little bit less screen real estate (which is lacking in the
legend). The drawback is that copy-pasting is not possible, but as it's
a fixed text, that's not useful anyway.
=> gui comp legend: use StaticText instead of RO TextCtrl for the label

src/odemis/gui/cont/tabs.py
The calibration light is turned during focusing.
It would normally be turned off automatically when cancelling the
autofocus. However, on the streak cam, if the manual focus was active,
the light would not be turned off.
=> When leaving the tab, reset the manual focus (so that when coming back to the tab
it doesn't look like we are in this mode), and turn off the light.
=> gui cont tabs SPARC2AlignTab: when leaving the tab, always ensure the calibration light is off

src/odemis/acq/stream/_sync.py
numpy.prod() returns a numpy.int, which is not considered an "int" in
Python 3. So all the other derived variables, like n_x and n_y would be
numpy.int, and eventually the VAs would complain that they don't get
ints.
=> acq stream _sync: force tot_num to be a int

src/odemis/gui/cont/tabs.py
Commit c620e5d976 (Distance tool) got a little bit too enthousiastic,
and added the ruler tool also in the alingment tab, for which it's not
useful, and the rest of the code doesn't support it.
=> remove it from the toolbar.
=> gui cont tabs: no RULER tool on the SECOM alignment tab

scripts/spot-grid.py
- flip the displayed rotation and translation, so the values
correspond to what they would be if the origin of the coordinate system is
in the bottom left of the image.
- update default spots to 8, 8 because that is what we now always use.
=> update spot grid: flip translation and rotation

src/odemis/model/_vattributes.py, src/odemis/model/test/vattributes_test.py
Numpy integers easly creep everywhere. Normally that's fine because they
quack like an int (except for the over- under-flows of course, but that
typically doesn't happen in the number we handle).
So let's accept them also in the VAs.
Note: in Python 2, numpy.int* were a subclass of int, so it worked
fine (not for numpy.uint* though). In Python 3, this "link" has been removed,
that's why we have to explicitly add it
=> model vattribute: also accepts numpy integers in IntVA and ResolutionVA

scripts/spot-grid.py
- In commit a2733d4 scaling was renamed to scale, this was not renamed where the scale is actually displayed.
=> Fix spot grid: rename scaling to scale everywhere

src/odemis/acq/stream/_projection.py, src/odemis/acq/test/stream_test.py
The same as 0D spectrum, it's useful to use float for the average of 1D
spectra.
Also fix the test cases to expect a float now.
=> acq stream projection: also use float for 1D spectrum

src/odemis/dataio/hdf5.py
Normally all future Odemis versions should support reading back the old
format, and we should use just the file structure and the
FileSpecificationVersion.
Nevertheless, it's useful for debugging to know which exact version of
Odemis generated the file.
=> dataio hdf5: store the odemis version directly in the metadata

doc/develop/extending.rst, requirements-py3.txt
Create a different requirements.txt, to avoid the user having to editing
too much the file.
=> doc: add instructions for Python 3.6 (on Windows)

src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py
Upgraded unit-test, made it a bit more fancier but not nicely depended on input data. Since mpp calculation and determination of pixels makes predicting the outcome size (resolution) of the export function complicated this is currently not done. Furthermore this is also complicated by the fact that a legend is added which results in big error margins in testing the ratio between the width and the height of the output image.
=> Export of pyramidal picture in higher resolution and update of unit-test

src/odemis/acq/stream/_projection.py
If a __new__ returns an instance of an object which is not of the same
class as the actual class, __init__ is not called. As
RGBSpatialProjection always returned RGBSpatialProjection as a fallback,
subclasses would still get a RGBSpatialProjection, which meant they were
not initialised.
In particular, this happened in the auto_align plugin, for AlignmentProjection.
=> As fallback, return the current class type.
=> acq stream projection: fix subclass of RGBSpatialProjection not initialised

src/odemis/driver/smaract.py, src/odemis/driver/test/smaract_test.py
Reading the DLL version and hardware name hadn't been tested, and it
countained bugs.
=> Fix them to use the proper API.
Also fix issues with the Exceptions on Python 3.
=> use the same style as in the other drivers (eg andorcam2, avantes).
If the device is not found, raise a HwError, so that the backend shows
a nice error message and suggests the user to try again.
Also do a few minor clean-ups.
=> driver smartact: fix MCS2 initialisation and Exceptions on Python 3

src/odemis/acq/align/delphi.py
The change from children to dependencies broke that part of the code.
A long long time ago, the stages where not directly available in the
model. So we had to rely on a hack, which consisted in looking on the
children of the main stage. The recent change to use depedencies broke
this part of the code.
=> Don't rely on this hack at all, and instead use the standard way to
search for components. That's what the manual calibration has been
doing, so it works on all systems, for sure.
=> acq align delphi: fix stages not found

src/odemis/gui/__init__.py, src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/overlay/world.py, src/odemis/gui/comp/slider.py
We used CURSOR_SIZNESW, because that's a closed hand on GTK (Linux).
For Windows, a different value is needed. So we used to have a if in
some places (eg, canvas), while some other places (eg, histogram) just
showed the wrong cursor.
=> Have a single place with the right cursor.
=> gui: define an explicit CURSOR_DRAG

src/odemis/acq/path.py, src/odemis/acq/test/path_test.py
Sometimes, for instance when changing quickly between chamber and
alignment tab, setPath() is called several times in a row.
Currently, every request is full-field, which can end up being very
slow. However, we only care about the latest requested position.
=> Discard move requests which haven't started yet.
We could be even more clever, and immediately stop the current moves,
but that's quite a lot more complicated, espcially because that means
all the callers need to handle CancelledError.
=> acq path: don't queue OPM setPath() calls

doc/develop/extending.rst
Fix the rc.local commands, to support 2 fake DAQ boards.
Remove duplicate line about conda in Windows.
=> doc extending: small fixes

src/odemis/gui/main.py
With the current behaviour of Pyro, the proxies are not reused in the
rest of the GUI, so the connections opened are immediately closed.
So instead of saving time, this causes extra delay.
When starting with a large backend, it ended up costing 1s extra, over 7s.
=> Remove "speed-up" hack.
Also move the first log to as early as possible to avoid confusing log
from the early start with the end of the previous log.
=> gui main: don't try to speed up Pyro connections

src/odemis/model/_core.py
The function was very optimistic, expecting that each VA needs only one
file opening. With a large back-end, the GUI end-up still reaching the
file limit.
In practice, all included, it seems that subscribing to a
VA (which was not proxy'd before) causes about 6 new files to be opened.
This is measured by using this command which reports the amound of files
currently opened by the GUI:
lsof -p $(pgrep -f odemis.gui.main) | wc -l
Comparing between the SettingsObserver activated or not, this showed
that for 102 VAs we need 686 more files.
=> Bump the file limit by 6 for each VA to be opened.
=> model core: prepare_to_listen_to_more_vas() increases the file limit by a larger amount

scripts/spot-grid.py, src/odemis/acq/align/spot.py, src/odemis/acq/align/test/spot_test.py
To see if the shape of the grid is perfectly square it is important to see the shear.
To keep the FindGridSpots function compatible with scripts outside odemis I decided to only return the shear if specifically requested.
=> Add the shear of the grid to the spot grid live visualization.

src/odemis/acq/path.py
The old version of the ThreadPoolExecutor (which is on Ubuntu 16.04)
doesn't have this argument. So drop it here. Noone actually uses it (in
Odemis).
=> acq path: Drop extra argument from OneTaskExecutor

src/odemis/gui/test/plugin_test.py
It's nice to know that the failure comes from the user's installation.
=> gui test plugins: if no plugin folder, indicate that's the reason the test case failed

src/odemis/acq/test/stream_test.py
Without this module, the projection cannot be computed, so it'll
obviously fail. However, in such case it fails with such generic error:
File "/home/philip/development/odemis/src/odemis/acq/test/stream_test.py", line 4287, in test_arpolarimetry
assert e.is_set()
AssertionError
=> Detect the module is missing and indicate how to install it.
=> acq stream test: test_arpolarimetry warn if arpolarimetry module is missing

requirements-py3.txt
It's "futures" which is already part of Python 3, so not available as a
package.A
=> config: fix dependency for Python 3

src/odemis/acq/stream/_live.py
Commit 5c839bba4f31 (don't try to shift more than the hardware supports)
put extra checks for MTD_EBEAM_SHIFT. However, it requires having .shift
VA.
For some bad reason, related to Pyro and proxies, the code previously
didn't break even if the emitter didn't have a .shift VA. It now got
officially broken.
=> Don't access .shift if not using MTD_EBEAM_SHIFT.
=> acq stream AlignedSEMStream: fix preparation with MTD_MD_UPD

src/odemis/gui/model/__init__.py
The SECOM and SPARC acquisition tabs had the new label tool.
However, it's typically not really useful during acquisition. In
addition, it's currently not possible to save them, and having them
in this tab could easily disapoint the user when opening the acquired
file and noticing no label was saved.
=> gui model: remove label tool from acquisition tabs

src/odemis/util/driver.py
We used to just rely on Pyro to quickly find out it's not possible,
however, this leaves an ERROR log. In practice this meant that almost
every start of the backend started with:
ERROR   core:401:       cannot connect: [Errno 2] No such file or directory
It's a little confusing for the user. Especially in case there is really
an error, it's easy to be mislead and think this is the problem (as it's
the first error of the log).
=> util driver: Never try to access the back-end if the file is not present

src/odemis/dataio/png.py
Do not rely on the scipy.imsave() function, which got deprecated in v1.0, and
removed in v1.3. This function actually called PIL, so it should be
really equivalent.
Also check more explicitly if the data passed is compatible.
=> dataio png: directly use PIL to save to PNG

src/odemis/acq/align/test/clspots_optical_autofocus_test.py
It should be in the "test/" subfolder of the code it checks.
Also it should run the test cases when run from the command line.
=> acq align test: move clspots autofocus test to the right place

src/odemis/acq/test/stream_test.py
commit d214e000f4a (acq stream projection: LineSpectrumProjection
clean-up) changed the behaviour of the projection to return (always) the
closest distance as first index.
The users in the GUI were updated, but not the test case, which got
worried.
=> acq stream test: Fix test_spectrum_1d complaining the projection is inverted

src/odemis/gui/cont/tabs.py
The GUI looks the same for streak and lens align mode, but the behaviour
is quite different. In streak mode, only one stream is played, and it
should be fixed.
Also, the axes control were disabled, which prevented the user from
doing anything.
=> gui cont tabs Sparc2AlignTab: fix manual focus on streak cam showing a new stream

src/odemis/acq/stream/_sync.py
Using the requested pixel size and SEM pixel size usually works, however
these values are indirectly computed. In some cases, there are floating
point errors which crip up and cause issues as the resolution accepted
by the ebeam scanner is not exactly the same.
For instance, in this (real) case, the resolution got clipped from 683
to 682 due to rounding error:
from odemis import model
em = model.getComponent(role="ebeam")
em.shape
Out[1]: (5760, 3840)
em.scale.value = (5.622254758418742, 5.622254758418742)
em.resolution.value = (1024, 683)
em.resolution.value
Out[2]: (1024, 682)
5.622254758418742 * 683
Out[3]: 3840.000000000001
Using the direct calculations, help. At least in this case.
For really being sure, we might need to put some extra cleverness in the
ebeam scanner. Especially, in …
=> acq stream MultipleDetectorStream: use more straightforward computation of the scale

src/odemis/dataio/hdf5.py, src/odemis/dataio/tiff.py, src/odemis/util/conversion.py, src/odemis/util/test/conversion_test.py
When exporting some Metadata ExtraSettings, if it contains a numpy
value, the whole data fails to be exported.
Example:
Failed to save ExtraSettings metadata, exception: Object of type 'int64' is not JSON serializable
=> Properly convert the numpy scalar/array into the right JSON
representation.
=> util conversion: new JsonExtraEncoder to export numpy types as JSON

src/bugreporter/odemis_bugreporter.py
It's handy to diagnose issues related to out-of-memory, or disk full.
=> bugreporter: also log memory and disk usage

src/odemis/driver/test/ueye_test.py, src/odemis/driver/ueye.py
On some camera (or version of libueye ?), the device capabilities
indicate that it's possible to change the shutter mode, and whenever
reading or writing it, it fails with a "NOT SUPPORTED" error.
=> Don't worry about this, and just conclude that finally it's not
supported.
Also log the hardware version at startup (handy for debugging).
Also fix the test cases which only worked when there was no hardware!
=> driver ueye: don't worry if the shutter mode cannot be changed

src/odemis/driver/andorshrk.py
The old firmwares used to report a COMMUNICATION_ERROR when calling this
function. This means that with the new auto-reconnction the hardware would
be rebooted every time this function is called. Chaos ensues.
=> driver andorshrk: don't autoreconnect for ZeroSlitPosition commands

doc/develop/acq.rst
It's a little bit messy, as the ebeam blankers have slightly different
options, and depending on the type of microscope, they are used
differently.
=> doc: document ebeam blanker current behaviour

src/odemis/acq/align/find_overlay.py
For the systems where the blanker can be controlled, but not
automatically, it's best to expclitily activate it during background
acquisition.
=> acq align find_overlay: use blanker during background acquisition if available

src/odemis/driver/andorshrk.py
A typo caused the relative moves of slit axes to silently discarded.
=> Fix the typo
Also raise an error if trying to move an axis which doesn't support
relative move.
=> driver andorshrk: fix relative move of slit axes

install/linux/usr/share/odemis/sim/sparc2-sim.odm.yaml, src/odemis/driver/semcomedi.py, src/odemis/driver/test/semcomedi_test.py
When the TTL has to be inverted for the scanning signal that doesn't
mean it should also be inverted when forced to True/False. It entirely
depends on what the signal means. For example, for an "external" signal,
we want it during for scanning, but still high when set to True.
=> Add another optional value in scanning_ttl
=> driver semcomedi: support scanning_ttl high_enabled option

src/odemis/driver/smaract.py, src/odemis/driver/test/smaract_test.py
A typo caused the reading of the referencing status to always be
reported as True.
This also caused the "ref_on_init" to never be executed.
=> Fix typo "|" => "&"
=> driver smaract: fix MCS2 always reporting axis is referenced

src/odemis/acq/align/autofocus.py, src/odemis/gui/cont/tabs.py
Now that we have several focus steams, the order matters.
Otherwise, we have 50% chance of ending with the stream corresponding to
the "other" detector, which also shows the slit, but not in the same way
as the standard image. Therefore the slit line doesn't match perfectly.
=> Always place the stream with the ccd as the first stream.
=> gui cont tabs Sparc2AlignTab: ensure the last autofocus stream has the ccd

src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py
The new logo is a little bit higher. This caused it to be shown lower.
=> Make it automatically centered.
=> gui xrc: re-center logo

src/odemis/gui/log.py
We were delaying the formatting of the string to when it would be shown,
which can be delayed by up to 0.2s. For complex variables (eg, list,
VA), this could mean that if the variable has been changed in-between.
This is quite confusing.
In such case, the log in the GUI wouldn't be the same as in the
odemis-gui.log file.
=> Format the string immediately when logged.
=> gui log: ensure the log shows the content of the variable when logged

src/odemis/gui/win/delphi.py
It was hard-coded to "python". However, that tends to be Python 2, and
if the rest of Odemis is running on Python 3, the manual calibration is
going to have a rough time.
=> Use explictily the same executable.
=> gui win delphi: Use the same version of Python for the manual calibration

src/odemis/driver/spectrapro.py, src/odemis/driver/static.py
Commit e608787e8 (model vattributes: check the content of the value at
init) "broke" these places which were incorrect.
=> driver static/spectrapro: fix initial VA value not fitting

install/linux/usr/bin/odemis-start
Need to export PYTHONPATH, as for every other scripts.
=> config: fix odemis-start using always system version

src/odemis/acq/align/autofocus.py
As power api refactoring task was directly after manual focus task, this emissions usage went unnoticed (also as there's no unit test for it). This gotta be the last usage of emissions in odemis, ironically it's by me! :-)
=> Remove emissions from manual focus

src/odemis/acq/align/autofocus.py
If the user cancels the autofocus when the grating changes, it will only
be cancelled after the end of the autofocusing, which can take up to a
minute.
=> check if the autofocus was cancelled before running the autofocus
again.
=> acq autofocus: earlier cancellation of the autofocus in some cases

src/odemis/driver/tmcm.py
The last change to the canopen simulator introduced a bug. In case of a duplicated mode, the canopen library raises an SdoAbortedError, which is caught in the __init__ of the driver. The simulator raised a ValueError which was not caught and therefore the testcases didn't run.
=> driver-tmcm: bugfix canopen simulator

src/odemis/driver/pigcs.py
The code to backtrack and reconsider a previous line as a begining of a
multi-line uses the already decoded text, so it's a string, not bytes.
On Python 3, this matters.
This was not detected in the test cases, with the simulator and
other hardwares, as it only happens for very few old version of the PI
controllers.
=> driver pigcs: fix Python 3 issue for hardware with weird multi-line

src/odemis/odemisd/start.py
On Python 3, the output of an external program is bytes, but we expected
a string. => Decode.
Also fix the display the the external program on the terminal. We now
don't cache it, so it's immediately shown.
=> odemisd start: fix model selector with Python 3 not working

install/linux/usr/share/odemis/sim/cryosecom-sim.yaml, src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/model/_metadata.py, src/odemis/util/__init__.py, src/odemis/util/test.py
The following is an implementation for the procedures to switch between loading/imaging/tilting position for the CryoSECOM stage. 
Two functions in `odemis.acq.move module`:
**cryoTiltSample**: Allows to switch between imaging ↔ tilted. 
**cryoLoadSample**: Allows to switch between imaging ↔ loading.
=> CryoSECOM position switching procedures

src/odemis/driver/test/actuator_test.py
Initializations of linked stage components were on setUpClass, which made their values get modified throughout the tests. => Move LinkedHeightActuator construction to setUp instead.
=> Fix LinkedHeightActuator setup

src/odemis/model/_components.py, src/odemis/model/test/remote_test.py
When writing Python code, due to the weird syntax of VAs, it's easy to
override a VA instead of actually setting a value. This should hopefully
catch a few bugs a bit earlier.
We could also do a similar behaviour on a Component, but there might be
some specific cases where this is acceptable. Maybe we could acccept
overriding a VA only with another VA... but for now I don't dare trying.
=> model component: forbid overriding VAs on a Proxy

src/odemis/driver/zeiss.py
GetVersion() returned bytes (on Python 3), which caused error when
comparing the string searched. It also caused a tiny bit wrong hwVersion
attribute.
This caused such error at startup:
File "/usr/lib/python3/dist-packages/odemis/driver/zeiss.py", line 84, in __init__
self._port, self._idn = self._findDevice(port)  # sets ._serial and ._file
File "/usr/lib/python3/dist-packages/odemis/driver/zeiss.py", line 187, in _findDevice
if not "smartsem" in idn.lower():
TypeError: a bytes-like object is required, not 'str'
=> driver zeiss: Fix finding device on Python 3

src/odemis/util/filename.py, src/odemis/util/test/filename_test.py
Only detect date patterns corresponding to *today*. If for some reason
the file has some numbers that look like date, we shouldn't replace it
by the date of today.
Also now detects short dates, with only the last two digit of the year,
as requested by some users.
=> util filename: improve date patterns

src/odemis/dataio/tiff.py
It would look like:
"Position metadata clipped to avoid negative position [100.0, 100.0, 100.000685]"
Of course, it's not negative.
=> dataio tiff: remove warning when position metadata has 3D

src/odemis/driver/andorshrk.py, src/odemis/driver/test/andorshrk_test.py
One spectrograph's slit had the reference switch not working.
As we don't need a very precise slit opening (because the user can
visually check), we can work around it by forcing the slit to go to the
maximum opening before every move. This has a similar effect as the
referencing as it allows to know where is the slit.
=> driver andorshrk: option to workaround slit reference issue

install/linux/usr/bin/odemis-mic-selector
There is typically always at least one optical module, so one EEPROM ID on a SPARC.
If no ID is found, it's a sign of something fishy, so it's best to
distinguish this case explicitly from the standard message "no matching
hardware found".
=> odemis-mic-selector: dedicated error message if no EEPROM IDs found

src/odemis/driver/tmcm.py
As the name of the function implies it should return a string, not
bytes. That is different in Python 3.
It didn't cause much problem as it's only use for debugging, but the log
output was weird looking.
=> driver tmcm: _instr_to_str() should return a string

src/odemis/acq/align/autofocus.py
Sometimes the image has so little feature that the gaussian fitting
fails to find any fitting. In such case curve_fit raises a RuntimeError.
=> Catch it and return a really low score.
This avoids randomly failing to autofocus with exceptions like this:
ERROR   log:44: Autofocus failed
File "/home/sparc/development/odemis/src/odemis/acq/align/autofocus.py", line 1296, in _DoAutoFocusSpectrometer
fp, flvl = future._subfuture.result()
File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/home/sparc/development/odemis/src/odemis/util/__init__.py", line 699, in bindFuture
result = fn(*args, **kwargs)
File …
=> acq align autofocus: Measure1D shouldn't fail on noise

src/odemis/driver/pvcam.py
That should help the driver on Python 3. Untested, and as the device
actually only works on Ubuntu 12.04 (for now?), this might stay like
this for a long time...
=> driver pvcam: String parameters need to be converted to Python string

src/odemis/driver/test/zeiss_test.py, src/odemis/driver/zeiss.py
One more issue of bytes vs string.
Actually, a move would always at least wait 1s, so for small moves, this
wouldn't be noticeable.
=> driver zeiss: fix move functions immediately returning on Python 3

src/bugreporter/odemis_bugreporter.py
A lot of systems use odemis-model-selector.log as name for the log of
the odemis-mic-selector, so let's handle it.
It's just too late to fix all these systems now.
=> bugreporter: odemis-model-selector.log is another name for odemis-mic-selector.log

src/odemis/driver/test/zeiss_test.py, src/odemis/driver/zeiss.py
Mostly handy to check if the scan rotation of the system has been
changed.
Also fix log of the focus component which said "stage".
=> driver zeiss: support for scan rotation

src/odemis/gui/plugin/__init__.py
As the button callbacks run in a separate thread, it can easily crash
the GUI if it ever calls a wxPython function. So it's handy to know if
a callback has started if a crash is followed.
=> gui plugin: add log when pressing a button

src/odemis/gui/plugin/__init__.py
The functions that they call directly manipulate the GUI, so the
simplest is to run the entire function in the main thread.
Also remove the calls to .enable() as actuall the .pause() and .resume()
already take care of doing this, and do it better.
=> gui plugin: .pauseSettings() and .resumeSettings() should be run in GUI main thread

src/odemis/gui/comp/viewport.py, src/odemis/gui/cont/tabs.py
With the new live view during acquisition, it's important to be able to
adjust the SEM/CL merge ratio. Ideally, we'd leave the entire viewport
enabled, with only restriction on the movement and zoom, but for now,
let's keep it simple, and just re-enable the bottom legend after
disabling the whole viewport.
=> gui SPARC: leave the bottom legend enabled during acquisition

install/linux/usr/share/odemis/sim/cryosecom-sim.yaml, src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/model/_metadata.py
Some further missing features in the `move` module for the CryoSECOM position switching procedures: 
- Add support for safe movement to coating position
- Add function returning current position label 
- Rename `getLoadingProgress` to `getMovementProgress`
- Refine `move_test` test cases
=> CryoSECOM position switching missing functions 

src/odemis/util/test/filename_test.py
On the 20-10-20, dateshrt was incorrectly guessed. Let's just use
dshrtrev, which is the first guess on such date.
=> util filename: fix test on dates where the day==year

src/odemis/gui/conf/data.py, src/odemis/gui/cont/streams.py
With the local axes changes, the tc-filter and tc-od-filter were not
anymore properly handled.
Especially, the CL intensity can also be affected by the tc-od-filter,
but it doesn't contain a band axis (it contains a "density" axis), so
this would prevent the stream from being created.
=> gui: fix support for time-correlator filters

src/odemis/gui/plugin/__init__.py
On Linux, the text colour used the foreground colour of the parent,
which was fine. However, on Windows, it seems it default to black, which
was unreadable.
=> Explicitly set the right (ie, almost white) colour.
=> gui plugin: fix description text colour on Windows

plugins/zstack.py
Some hardware provide a .speed VA, but it doesn't contain the info about
all the axes. If "z" is missing, then it's the same as the whole .speed
missing.
=> plugins zstack: also handle if the speed VA doesn't know about Z

src/odemis/driver/lakeshore.py
On Python 3, bytes and strings are different, so extra care is needed.
Also do a little bit of import clean-up.
Also improve the LakeshortError to behave more like a normal IOError,
and especially not fail if no status byte is passed.
=> driver lakeshore: fix encoding issues on Python 3

src/odemis/acq/stream/_base.py
If there is no data, recomputing the intensity range is not meaningful.
For now, it would try, and fail, leading to such error in the log:
File "/home/piel/development/odemis/src/odemis/model/_vattributes.py", line 97, in notify
l(v)
File "/home/piel/development/odemis/src/odemis/util/weak.py", line 37, in __call__
return self.f(ins, *arg, **kwargs)
File "/home/piel/development/odemis/src/odemis/acq/stream/_base.py", line 1124, in _onOutliers
self._recomputeIntensityRange()
File "/home/piel/development/odemis/src/odemis/acq/stream/_base.py", line 1135, in _recomputeIntensityRange
self.intensityRange.value = irange
File "/home/piel/development/odemis/src/odemis/model/_vattributes.py", line 1175, in _set_value
value = tuple(value)
TypeError: 'NoneType' object is not iterable
=> Detect there …
=> acq stream: don't raise error if changing BC outliers before any data is available

src/odemis/driver/simsem.py, src/odemis/driver/test/simsem_test.py
The shift is also taken into account to move the generated image within the whole raw image.
While the translation VA can never be set to go out of bound, the shift
VA can. In such case, we shouldn't fail to simulate, but just clip the
image.
=> driver simsem: don't fail to generate an image if the shift is large

src/odemis/model/_vattributes.py
__del__() is called even if __init__() didn't finish.
If it failed, for instance because the VA value is incorrect, then the
new code unregistering from the remote listeners would fail.
=> do the same as for the other attributes.
=> model vattribute: don't fail on __del__ if __init__ failed

src/odemis/driver/tmcm.py
The user config contained 3 axes, so on 1-axis simulated hardware, it
would fail.
=> Make a new user config with only 1 axis. It ought to work on any
simulated hardware!
=> driver tmcm: adjust simulator to not fail on 1-axis hardware

src/odemis/util/test/transform_test.py, src/odemis/util/transform.py
Usage of transform.apply() is now preferred.
=> Added DeprecationWarning to transform.__call__ method

src/odemis/gui/cont/acquisition.py
scaling_xy is a tuple, so cannot show it as a float.
=> show it as "x/y"
Reported by Ryan Lane.
=> gui cont acquisition: fix logging of scaling_xy

src/odemis/gui/cont/microscope.py
When inserting a sample holder which is not calibrated, a dialog box
appear to either eject the sample or calibrate it.
This happens on the first time the CLEM sample holder is inserted.
However, if the user also use a standard SEM sample holder, with the
standard Phenom GUI, while Odemis is running, this also happens.
Then, the dialog appear *every* time the sample holder is inserted.
This can cause many time the same dialog box to be shown. None of them
useful.
=> Automatically close the dialog window when the sample is ejected by
an other mean than the Odemis GUI. This way, it never shows more than
one dialog.
Can be tested on the simulator by removing the calibration file, and
then doing:
odemis-cli --set-attr chamber opened True
odemis-cli --set-attr chamber opened False
=> gui cont microscope: DELPHI first calibration dialog automatically closed when sample is ejected

src/odemis/driver/test/xt_client_test.py
small change in the test case to test if the correct autofuncionality is not running. [tested on EA]
=> correct xt_client test_apply_auto_contrast_brightness

src/odemis/gui/util/test/img_test.py
Some test cases had left-over debug code which broke them.
Some other test cases where affected by the small changes in the
changes of calc_img_buffer_rect(). So update them with the new expected
values (all +/- 1).
=> gui util img: fix test cases

install/linux/etc/odemis.conf
When no interpreter is set, now Python 3 is used, so let's also update
the default configuration to use Python 3.
=> install: change default interpreter to Python 3

src/odemis/driver/npmc.py
As usual, now that we have bytes we cannot compare them to a string.
=> As in other drivers, convert directly the responce from the device to
unicode.
=> driver npmc: fix instantiation on Python 3

src/odemis/gui/util/img.py
The min/max of the colourbar is not the min/max of the value, but the
intensity range, which is always a smaller range.
This also fixes the display when using pyramidal images.
=> gui util img: fix intensity range display in databar

src/odemis/util/test/transform_test.py, src/odemis/util/transform.py
Useful when converting a relative displacement (shift).
=> Made parameter `shape` optional in `to_physical_space` and `to_pixel_index`

src/odemis/gui/cont/actuators.py, src/odemis/gui/cont/tabs.py
The goal is to ensure that the optical lens is positioned as close as possible from the last known aligned position after a referencing (or a move to a safe position during 5DoF referencing).
=> CryoSECOM lens aligner active position

src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py
- In test_set_beam_shift a tuple was compared in assertAlmostEqual, I split it up in two comparisons for each value.
- For blank beam to work the scan mode must be full frame and the channel state unpaused.
=> driver xtclient fixed test cases for beam shift and blank beam

src/odemis/driver/tfsbc.py
It is quite useful for debugging purposes to also log the requested shift in the scan coordinate system (and not only the register values).
=> driver-tfsbc: log requested shift

src/odemis/gui/comp/legend.py, src/odemis/gui/util/img.py
When exporting data, the whole range should also be passed, to display
properly non-linear range.
Also fix time ticks not shown, because they go from top to bottom.
Fix mirror vertical ticks not properly placed.
Ensure that all ticks sufficiently spaced are shown.
=> gui img: fix tick display for plots

src/odemis/gui/cont/tabs.py
For "in" to work, we need an iterable.
"(x)" is not an iterable, it must be written "(x,)"
It actually kind-of worked because strings are some kind of iterables.
But that doesn't work with None.
=> gui cont tabs: fix viewer broken by cryosecom

src/odemis/driver/npmc.py
commit 59ed1a8f45 (fix instantiation on Python 3) tried to
fix the code for Python 3, but it didn't even work at init.
I guess I mistakenly only tested on Python 2...
Anyway, now it should be properly working.
=> driver npmc: fix the Python 3 fix not working on Python 3

install/linux/usr/share/odemis/hwtest/piezomotor.odm.yaml, src/odemis/driver/piezomotor.py, src/odemis/driver/test/piezomotor_test.py
* fixed bug in init (probably introduced during review process)
* added testcase for bug (was not caught when testing with single axis, so test with 2 axes, at least in simulator)
* added yaml file to hwtest because the driver parameters are sufficiently complicated
=> driver-piezomotor: bugfix and yaml file

src/odemis/driver/lakeshore.py, src/odemis/driver/test/lakeshore_test.py
The class needs to call the super() with **kwargs, in order to have the
component registered as a Pyro4 object, so that it's not directly
passed, but instead a proxy is passed.
=> driver lakeshore: fix instantiation in the backend

src/odemis/driver/andorcam2.py
It seems it's never called recursively, but with the recovering code,
in the andorshrk, it's best that locks are recursive.
=> driver andorcam2: use recursive lock

src/odemis/acq/_futures.py, src/odemis/driver/picoquant.py, src/odemis/driver/semcomedi.py, src/odemis/driver/simcam.py, src/odemis/driver/technolution.py, src/odemis/driver/tescan.py, src/odemis/driver/tfsbc.py, src/odemis/gui/acqmng.py, src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/combo.py, src/odemis/gui/comp/overlay/view.py, src/odemis/gui/comp/overlay/world.py, src/odemis/gui/comp/stream.py, src/odemis/gui/comp/text.py, src/odemis/gui/cont/streams.py, src/odemis/gui/log.py, src/odemis/gui/main.py, src/odemis/gui/util/img.py, src/odemis/gui/win/acquisition.py, src/odemis/util/img.py
All of the unused imports are actually used by other modules, which
typically are used at the same time, so it wouldn't change much.
Still, it cleans up the code.
=> remove unused imports

src/odemis/driver/technolution.py
The minimum of the cell resolution cannot be lower than the minimum effective cell resolution.
=> Update cellCompleteResolution minimum

src/odemis/driver/scanner.py
If the "internal" SEM, ie via API, allows to change the scan rotation,
it often affects also the external scan, so it can be handy.
=> driver scanner: use rotation also from internal if available

src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py
In commit e7789884b3 (add format_bgra_to_rgb() function), merge_screen()
was updated to make use of the new function, but that was incorrectly
done, as the original code was a little confusing.
It needs to return the update *background*, not the input im.
Also update the docstring and test cases to indicate now it returns a
RGBA (instead of RGB or RGBA). The actual calling code in Odemis doesn't
care.
=> gui util img: fix merge_screen() only returning original im

src/odemis/acq/stream/_projection.py
In the update to use the tint, we added the support for it when
exporting the data, but not when displaying it in the GUI.
=> Also use the tint in the GUI display.
=> acq stream ARRawProjection: use the tint

src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/util/img.py
They are also typically shown using tint, several of them together (eg,
using some RGB filters), and so it makes more sense to add the pixel
values, like for the FluoStreams, instead of averaging.
Note that in case there is only one CLStream, it's always shown first,
so it doesn't affect the behaviour in this case.
=> gui comp: Also show CLStreams using "screen" operator

src/odemis/acq/stream/_base.py
This data is mostly only for debugging purpose.
However, it's also used to display the acquisition time in the export.
If there is no date known, it's better to not show anything, than
display the current time.
=> acq stream base: don't put current time if acquisition not known

src/odemis/driver/simsem.py, src/odemis/driver/test/simsem_test.py
Commit 215b61b52 fixed a bug but introduced another one.
Instead of calculating the last index, we were computing the
pixel just after. This caused the "protection" code to do the
wrong thing.
Also add a test triggering the issue.
=> driver simsem: fix acquisition failure when no drift

util/tmcmconfig
From the fixed version of the 3110 manual: it's in 10ms.
=> util tmcmconfig: fix description of axis param 204

src/odemis/driver/piezomotor.py
Fixes odemis-cli calls to move functions.
If a future is returned from a function, there is a special trick to make pyro remote calls work, so we always need this decorator for all move functions.
=> driver-piezomotor: async decorator

install/linux/usr/share/odemis/hwtest/tmcm-can-ctrl.odm.yaml
* for single axis it doesn't matter, but for multiple axes it does
* rename to rz as it is a rotation
=> CanOpen HW yaml: fix axes parameter - needs to be list and not set

src/odemis/driver/tmcm.py
* allow relative path for datasheet
* make param_file optional
=> driver-tmcm: improved interface for configuration files of canopen driver

src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/util/img.py
For simplification, we had said that such image is always shown
all together (ie, merge ratio == 0.5). It might still be handy in some
cases to be able to change the display ratio finely between two images.
Note that if the ratio != 0.5 and the background is not black, the
background will be seen a little bit. As this only happens in some
internal debug mode, that shouldn't matter.
=> gui comp: allow changing merge ratio between two Fluo or CL streams

src/odemis/util/img.py
When several ImageIntegrators were used for the same data, the metadata
would be shared between the sum, which would cause incorrect dwell time
or exposure time to be reported.
=> At start, use a separate DataArray to store the final sum, and
also duplicate the metadata. From there on, everything is independent.
=> util img: Fix using multiple ImageIntegrators with the same data

src/odemis/driver/test/technolution_test.py
Please merge this one as third/last in the row of PR's for the tech_wrapper.
=> Add a waiting period in the tests to offload mega field images.

src/odemis/driver/simulated.py
When doing a relative move, it would only indicate by a warning that it
goes outside of the range. That's different from other real drivers,
which typically raise a Exception in such case.
=> Simulate better by raising an exception too.
=> driver simulated stage: fail to move outside of axis range

src/odemis/acq/align/autofocus.py
Passing a float still works on numpy 1.13, but it generates a
depecration warning. It will probably stop working in the future.
So let's explicitly pass an int, as it should be done properly.
=> acq align autofocus: numpy.linspace() should get int as steps

install/linux/usr/share/odemis/sim/clspots-optical-autofocus-sim.odm.yaml, src/odemis/driver/simcam.py
This was used by a single simulator, to make the blur "stronger" when
moving the focus.
In addition, every DigitalCamera has a .depthOfField VA, which is automatically
computed based on the LENS metadata. This VA has a similar meaning. So
it makes sense that the simulated camera follows this VA to adjust the
blur factor.
=> Use depthOfField, and update the simulator with metadata which makes
the blur equivalent.
=> driver simcam: remove blur_factor argument

src/bugreporter/odemis_bugreporter.py
It's normally only run on Python 3 nowadays, but let's not yet break
Python 2 support yet.
=> bugreporter: fix starting without config file on Python 2

debian/odemis.dirs, debian/rules
Commit eec959b85 (switch to Python 3 by default) should have made
sure that the shebang was not changed... but it wasn't properly tested.
It turns out that there are two places which tries to rewrite the
shebang, and we had only disabled one. For now, use the scripts
installed when installed via Python 3, so we get the right shebang.
=> config: Ensure the script shebang is Python 3

src/odemis/gui/comp/combo.py, src/odemis/gui/comp/stream.py
In case the .tint is changed, the combobox was updated, but not
the colour of the custom tint. So selecting a dye on a Fluorescence
Stream didn't update the colour.
=> Change the colour associated to the custom tint in such case.
=> gui comp stream: fix colourmap not updated when custom tint is used

src/odemis/acq/stream/_helper.py
During acquisition, the helper stream might update the "live" image in a
background thread while the acquisition thread has just reset the .raw
data, because a new e-beam position is used.
In such case, find_metadata() would fail. However, it's still updating
the projection based on the previous raw data, and the metadata is still
available. So use the metadata passed, instead of searching for it in
.raw again.
=> acq stream TemporalSpectrumSettingsStream: avoid errors when .raw is empty

plugins/ar_spectral.py
We use the raw CCD, although normally it's the spectrometer, which wraps
the CCD that has an axis invertion if the wavelengths are the opposite
direction. Due to difference between hardware and possible extra mirror,
there is no convention of wavelength on the CCD. In practice this means
that there is 50% chance the wavelengths are inverted.
=> Automatically look at the spectrometer, and invert the wavelengths if
it does that.
Also remove some incorrect metadata which caused the data to be
sometimes not properly be displayed on the spacial image.
=> plugins ar_spectral: fix spectrum being inverted on some systems

src/odemis/driver/test/technolution_test.py
Currently there is an error at the ASM side for long dwell times.
This was found because the check megafield (accidentally uses a long dwell time) however this test should not test a long scan but only check if the functionality of check_mega_field exists.
Therefore the dwell time for this test is set to the minimal allowed value.
=> Reduce the dwell time during check megafield to increase the testing speed

src/odemis/driver/technolution.py
If we update the MD only in the start of a megafield, each dataarray (field) returned would have the same stage position. Update the MD every time a new field is acquired, so that the dataarray returned has the correct stage position.
TODO: A proper fix would be to have a settingsMD which includes MD such as the dwell time. And in the next call we would call mergeMD and add the settingsMD via updateMD call. Thus, we make sure that the generic settings such as the dwell time is for all fields the one that was set in the beginning of the megafield acquisition, but the stage position is updated correctly per field.
=> ASM wrapper: update MD every time a new field image is acquired

install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
If the metadata is placed directly on the component, it's happily
discarded by the backend.
=> config: fix enzel sim without metadata on the align stage

src/odemis/driver/tfsbc.py
Use comma instead of '%' in logging messages to avoid problems with logging tuples.
It was working before via pyro, maybe because the values were passed as lists? Testing today in a script (without pyro) caused a logging message to fail.
=> driver-tfsbc: bugfix logging

install/linux/usr/share/odemis/sim/sparc2-ded-focus-test-sim.odm.yaml
Now that simcam uses the depthOfField value, the blurring started to
be less strong. This is not sufficient for the test cases.
=> Change NA and RI to provide blur similar to before.
=> config: update sparc2 focus simulator to adjust focus blur

src/odemis/driver/test/simcam_test.py
Now that the simulated stage doesn't allow going out of range, we need
to be a tiny bit careful.
=> driver simcam test: fix focus out of range

src/odemis/gui/comp/combo.py, src/odemis/util/img.py
The new versions of numpy only accepts ints for linspace().
So better be clear and force having width and height as int.
=> gui comp combo: getColorbar() only accepts ints

src/odemis/driver/xt_client.py
The metadata should be updated via the respective components (children) and not via the parents. This way the affects in the yaml file actually works correctly. Otherwise this should go via the parent object indirectly.
@pieleric EA is currenlty not available for testing I only tested this on the simple simulator on my computer, is that ok or do we want this also to be testen on real Hw?
=> Fix metadata upload of xt_client.py

src/odemis/acq/move.py, src/odemis/acq/test/move_test.py
When going to “Imaging” mode, align should go to align.MD_FAV_POS_ACTIVE.
Formerly we did it in the SecomAlign tab, but it makes more sense to have it in the move module.
=> ENZEL: Move lens aligner to its ACTIVE position on IMAGING

plugins/merge_RGB.py
* Once you open a new image a simple DataArray is used for the crop, shift functionality and to store the image directory.
* The plugin takes care to get a DataArray from the DataArrayShadow and assign the corresponding tint to it.
* Before this was supported only for 3D data.
=> Plugin merge_RGB is updated to read a DataArrayShadow properly

src/bugreporter/odemis_bugreporter.py
by inserting bytes into a string, it generated "b'...'".
Surprisingly, that's accepted as base64 by the server, which drops the
quotes.
=> Convert to a string before inserting.
=> bugreporter: fix incorrect encoding of attachments on Python 3

src/odemis/driver/smaract.py, src/odemis/driver/test/actuator_test.py
The test case failed because it *thought* that the position hasn't
changed. However, the driver does update the position, it's just that
the .position VA is updated *after* the .cancel() returns. That's what is causing the failure.
I think that could force cancel() to wait for the move function is complete, but that's hard to do, and probably would be annoying in some cases.
So let's just accept that it behaves as-is.
We can modify the test cases to wait a bit before reading the stage position, and then it works.
=> driver test actuator: wait a little after canceling a move to check the position

src/odemis/gui/conf/file.py
By default there is a fancy feature in ConfigParser to replace %xxx by
something else. We don't use it, and it prevents storing anything
containing % without escaping it.
In practice, if the user would put a % in the filename, the config file
couldn't be saved.
=> Disable the interpolation.
Also switch to just the Python 3 names, as we don't support Python 2
anymore. The SafeConfigParser will not work on newer versions of Python 3.
=> gui conf: disable interpolation from the configparser

src/odemis/driver/smaract.py
In case of timeout, it's clearer to raise a TimeoutError.
=> driver smaract 5DoF: report better errors during move

install/linux/usr/share/odemis/hwtest/piezomotor.odm.yaml, install/linux/usr/share/odemis/hwtest/pmd401.pmd.tsv, src/odemis/driver/__init__.py, src/odemis/driver/piezomotor.py, src/odemis/driver/test/piezomotor_test.py, util/pmconfig
**This is not ready to be merged**
I made a few changes to the stage driver, including
* a new referencing procedure (works differently with encoder, see comments in code)
* the use of a .tsv file to pass the parameters (it turns out that there are more of them then I thought).
* explicit passing of both the motorstep and encoder resolution (the indirect conversion with spc caused problems)
* a timeout factor for the z axis (z axis is attached through a different component, see docstring)
* a scan function and more explicit messages in pmconfig (sometimes it's hard to figure out which axis numbers there are)
* removed referencing in pmconfig, it's too dangerous (especially if there are problems with the limit switch)
I have not tested all the changes on the hardware yet. I expect that I …
=> piezomotor: referencing, bugfixes, scan function

src/odemis/driver/test/tfsbc_test.py
In previous PR, the order of the metadata has been modified. The testcases need to use the values in the right order as well, otherwise the transform doesn't work.
=> driver-tfsbc-test: fix testcase

src/odemis/driver/tmcm.py
When Odemis log level is set to DEBUG, python-canopen automatically
follows. That causes the log file to be flooded by information about
every CAN paket received.
=> driver tmcm: limit the log level of python-canopen to INFO

src/odemis/driver/piezomotor.py
For serial, we need to explicitly load the submodules.
=> driver piezomotor: add missing import

install/linux/lib/udev/rules.d/99-can0.rules
We only support 2 hardware via CAN, they both use 500Kbit/s by default.
So let's use that as default.
=> config: change default CAN bus bitrate to 500Kbit/s

src/odemis/driver/smaract.py
It didn't check the axes. Eventually, passing incorrect axes would fail,
but normally we immediately fail on the call.
=> driver smaract MCS2: check reference axes

src/odemis/driver/hamamatsurx.py
The data is first decoded to string, so all the other functions should
use string, not bytes.
It was not a big issue as the information was fully fetched, which is
the most important, and also logged. So the rest of the execution kept
going fine.
This solves such error:
2021-04-01 10:20:42,602	DEBUG	hamamatsurx:1188:	Received: '\nProduct number: C13440-20C\r\nSerial number: 301730\r\nFirmware: 4.20.B\r\nVersion: 4.20.B03-A19-B02-4.02\r'
2021-04-01 10:20:43,604	ERROR	hamamatsurx:1196:	Failure while decoding readout camera information.
File "/usr/lib/python3/dist-packages/odemis/driver/hamamatsurx.py", line 1190, in readCommandResponse
additional_info = additional_info.decode("latin1").split(b"\r")
TypeError: must be str or None, not bytes
=> driver hamamatsurx: fix error with Python 3 when decoding camera info

src/odemis/gui/comp/file.py
In order to distinguish between ome.tiff (TIFF) and 0.ome.tiff
(Serialized TIFF), we need to pick the longest extension.
That's already what we do in the rest of Odemis, like splitext() function.
So do it here too.
=> gui comp file: pick the format corresponding to the longest extension

src/odemis/acq/calibration.py, src/odemis/acq/test/calibration_test.py
Wrong variable name, due to copy/paste.
=> acq calibration: fix loading AR background when file contains multiple AR data

src/odemis/driver/technolution.py
The ASM only accepts integer as type. The VA was returning a numpy.int64. Modify setter to return int.
=> ASM API wrapper: fix bug in return type of resolution VA setter

src/odemis/acq/stream/_sync.py
Doing the live update has some cost. In particular, for the MDSEMStream,
it means we break down the acquisition in smaller regions.
Starting/stopping the acquisition takes a bit of time, and also might
cause some hardware to go to "idle" mode, which takes extra time to
start again.
The live update is there for the user to see there is something
happening, and that the data is still good. Doing it every 2s, instead
of 3 times per second, should be more than sufficient.
=> acq stream: reduce MDStream live update to 0.5 Hz

src/odemis/driver/technolution.py, src/odemis/driver/test/technolution_test.py
* cellTranslation, cellDigitalGain, cellDarkOffset should also accept lists as input type as this is the format that needs to be provided in the yaml files
* simplify setters for readability
* cellDigitalGain: int can be considered a special case of float; simulator accepts ints and floats
* some reformatting and adding docstring to tests
=> ASM API wrapper: allow lists as input for cell VAs

src/odemis/driver/andorcam2.py
The Excetion doesn't have any .strerr attribute, it's called .strerror.
This caused the acquisition to completely fail instead of trying again.
Typically, the log would look like:
2021-04-13 09:59:51,508	ERROR	andorcam2:2190:	Failure during acquisition
File "/usr/lib/python3/dist-packages/odemis/driver/andorcam2.py", line 2139, in _acquire_thread_synchronized
self.WaitForAcquisition(0.1)
File "/usr/lib/python3/dist-packages/odemis/driver/andorcam2.py", line 1147, in WaitForAcquisition
self.atcore.WaitForAcquisitionTimeOut(timeout_ms)
File "/usr/lib/python3/dist-packages/odemis/driver/andorcam2.py", line 288, in at_errcheck
(str(func.__name__), result, AndorV2DLL.err_code[result]))
odemis.driver.andorcam2.AndorV2Error: Call to WaitForAcquisitionTimeOut …
=> driver andocam2: fix error when trying to recover from error

src/odemis/acq/calibration.py, src/odemis/acq/test/calibration_test.py
Using just the first AR data work, but it's even better to use the
average, and not really more difficult.
=> acq calibration: if multiple AR background, average them

src/odemis/driver/technolution.py, src/odemis/driver/test/technolution_test.py
If an invalid name is provided raise an error which can be captured e.g. by the GUI. A warning in the backend, is not immediantly visible to the user. If the value is just overwritten, we end up overwritting an already acquired image. Raise an error, so the GUI e.g. can request a different name.
Remove ILLEGAL in name for characters as those are the actually allowed characters.
=> ASM API wrapper: modify filename VA to raise error when invalid name is provided

plugins/sparc_engage_warn.py
For systems where it can be dangerous (eg, other detectors possibly in
the path), we can add this plugin.
On every press of the "Mirror" button in the chamber a confirmation is
asked.
=> plugins: new plugin sparc_engage_warn to show message box before moving mirror

src/odemis/gui/cont/tabs.py, src/odemis/gui/util/__init__.py
Previously `enable_tab_on_stage_position` was taking the tab as parameter and enable/disable its panel on imaging position. But what was actually required is to enable/disable the tab buttons.
=> Enable Cryo tab buttons on imaging only

src/odemis/driver/test/pmtctrl_test.py
In the picoquant driver, the class got renamed, and I hadn't realised it
was used by some other code... breaking this test cases.
=> driver pmtctrl test: PH300RawDetector got renamed to RawDetector

src/odemis/driver/tmcm.py
Let's not stop all the devices on the CAN bus.
Some might not be controlled by Odemis, or at least, not by this driver.
=> driver tmcm CanOpen: on terminate(), only stop the device under control

src/odemis/gui/comp/buttons.py
All the wxPython components support Enable() == Enable(True).
So let's do it here too.
=> gui comp buttons TabButton: allow to call .Enable() without argument

src/odemis/gui/conf/data.py
10 ms is quite long, and some sample can do with much less. It should be
limited only by the hardware exposure time.
=> Put a 1 µs limit, which should work with pretty much any hardware.
=> gui conf data: don't arbitrarily limit the minimum spectrum exposure to 10ms

src/odemis/gui/cont/tabs.py
Localization tab `clear_data` used the overview stream controller's `clear` function to remove the 'old' streams from the views, but that resulted in removing them from the acquisition dialog as well. To fix this, `removeStream` is used instead.
Note that the old static streams still show on the panel, and it could be required to remove them from it to alleviate memory consumption.
=> ENZEL: Fix disappearing live streams on acquisition dialog 

src/odemis/gui/cont/streams.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/win/acquisition.py
Fix the dead listener bug on removing overview streams.
Also fix the issue of removing the stream panel when replacing old overview streams.
=> ENZEL: Handle clearing stream panel

src/odemis/acq/move.py
After referencing the sample stage, it tends to move to a position near the maximum axes range, and trying to move it back to the loading position using our safe method _(rx&rz followed by x&y followed by z)_ may result in an invalid/reachable position error -> For this special case move all linear axes together.
=> ENZEL: Fix 5DOF Invalid/Unreachable error

src/odemis/driver/pigcs.py
As the data contains \r, it's confusing in the log to get some extra
lines.
=> driver pigcs: add missing string escape

plugins/ar_spectral.py
The other streams already do it, but in this plugin we were taking shortcuts
and assumed that the CCD acquisition == exposure time.
However, with slow readout rates, and small exposure times, the readout
can take many time the exposure time. This caused the acquisition to
fail, because it timed out too early.
=> Use the same formula as the other streams.
=> plugins ar_spectral: take into account readout rate for time estimation

src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/overlay/view.py, src/odemis/gui/comp/overlay/world.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py, src/odemis/gui/model/__init__.py, src/odemis/gui/test/comp_overlay_test.py, src/odemis/gui/xmlh/delmic.py, src/odemis/gui/xmlh/xh_delmic.py
The overview image (acquired in SEM and FM) shows the entire sample (possibly with some gaps). The user needs to navigate through this “map” to (1) investigate whether a “site” is interesting, by using FM Z-stacks and (2) go back and forth between sites during milling. So the main goal is to allow the user to mark these sites on top of the  map, and be able to store the settings for each of this sites.
=> ENZEL: Feature Bookmarking

src/odemis/driver/smaract.py, util/saconfig
This is an updated calibration procedure for referencing the 3dof stage. It entails:
- Separate autozero referencing mode from normal mode.
- Set zero position directly to automatically adjust the logical scale offset.
=> Modify 3dof Stage referencing procedure

src/odemis/driver/test/xt_client_test.py
Setting via the internal command needs to use the 10⁶ factor.
=> driver xt_client: fix test_delta_pitch_VA

src/odemis/gui/cont/tabs.py
The new manual focus option allow to switch the detector. For now it
just select which stream plays. That's not enough as each detector is
selected by a mirror to switch the optical path.
=> Call the optical path manager to update move the mirror(s) to the
right position.
=> gui cont tabs SPARC2Align: also update the optical path when changing the detector

src/odemis/odemisd/start.py
Calling Odemis-start when Odemis is already started doesn’t restart the
backend. However, it restart the GUI.
That’s bad behaviour, as some customers have multiple icons of odemis.
In such case, it’s easy to call odemis-start by mistake, which kills the
GUI, and brings a new one. Really not fun if the GUI was in the process
of a long acquisition.
=> If GUI is already started, do not restart it.
=> odemisd start: do not close the GUI window if it's already opened

src/odemis/driver/semcomedi.py, src/odemis/driver/test/semcomedi_test.py
When the max_res wasn't square, the pixel size would be initialised
incorrectly to non-square value. On the first magnification update,
it would be set properly. As in almost every case the user has to change
the magnification, this is rarely noticeable. Still, it's good that
the pixelSize is always correct.
=> driver semcomedi: fix non-square pixel size on init

src/odemis/acq/stitching/_tiledacq.py, src/odemis/acq/stitching/test/tiledacq_test.py, src/odemis/gui/win/acquisition.py
These argument allow to adjust the exact behaviour of the tiling.
In particular, in some case we want to tile without overlap (because the
stage precisition is good enough). In such case, the default registrar
would get confused/sad. It'd fallback to IDENTITY, but generate a lot of
warnings on the way.
=> acq stitching tiledacq: add registrar and weaver arguments

src/odemis/cli/main.py, src/odemis/cli/test/main_test.py
Make the command line easier to type and read by ommitting the "--"
before an action, à la git.
The "--" are still allowed.
So now, instead of writting "odemis-cli --list", one can write
"odemis-cli list".
This only works for "actions", not the options, like "--machine".
=> cli: allow to pass the "action" without "--"

src/odemis/driver/zeiss.py
It doesn't make sense to ask to set the FoV to the same value as we
received it.
Probably some copy/paste error.
=> driver zeiss: don't set FoV when it changes

src/odemis/gui/comp/overlay/world.py, src/odemis/gui/cont/streams.py, src/odemis/gui/model/__init__.py
* The arrangement of the scintillators on the sample carrier differs from the one which was previously hardcoded
* There was some confusion related to the ltrb coordinates ("top" means minx (not maxx) in physical coordinates)
I decided to set the minx, miny origin at the bottom left of the entire sample carrier (not the first scintillator) to avoid negative coordinates for the background overlay.
The distance between scintillators has been confirmed to be 18 mm, not 18.5.
=> FastEM GUI: scintillator arrangement, bugfix coordinates

src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/driver/smaract.py, src/odemis/driver/test/smaract_test.py
Due to the physical constraints on the 5dof stage design, sometimes a move on one of its axes fails because the stage is close to the maximum range of its positions. This typically happens if a move or reference is cancelled (resulting in unknown position) and the stage is trying to retract back to its loading position. To mitigate this issue, an ordered fallback_submoves list is added, moving linear axes at the same time first, followed by rotational axes in case the typical submoves failed with this particular smaract exception.
Also the 5dof FakeMC driver is modified to simulate this behaviour.
=> ENZEL: Handle Smaract invalid unreachable position error

src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py
I'd like to make a call to the flash functions from the GUI, however, it's not very nice to use the blocking functions of the SEM directly. Can we extend the driver with these wrapper functions?
=> driver-xt_client: wrapper for flash functions

debian/odemis.dirs, debian/odemis.install, debian/odemis.links, install/linux/usr/share/bash-completion/completions/odemis-cli, install/linux/usr/share/bash-completion/completions/odemis-convert
Also complete "action" style arguments.
Provide odemis link to "odemis-cli", as a short-cut.
Move to "new" directory /usr/share/bash-completion/ (available since
Ubuntu 16.04).
Use new _have function
=> config: update bash completion

src/odemis/gui/comp/stream.py
It was used to add the "Fit to RGB" button. However, it's now replaced
by a special colourmap. So can be entirely removed.
=> gui comp stream: remove unused function/button

src/odemis/driver/technolution.py
The current ASM HW does not scan the very first field image correctly. This issue needs to be fixed in HW. However, until this is done, we need to "through away" the first field image and scan it a second time to receive a good first field image. To do so, just always scan the first image twice and overwrite on disc (external storage).
=> technolution driver: add hack to skip the first field image

src/odemis/gui/model/__init__.py, src/odemis/gui/model/test/model_test.py, src/odemis/gui/model/test/secom-sim-no-stage.odm.yaml
For the SECOM/SPARC/DELPHI, we have some basic expectations in the code
in terms of which component has to be present.
So far, if the user doesn't have this component in the microscope file
(or, more likely, the component role has a typo), very unclear messages
are shown, such as:
2021-06-04 10:44:24,114	ERROR	main:381:	Traceback (most recent call last):
File "/home/cryo-poc/development/odemis/src/odemis/gui/main.py", line 140, in OnInit
self.init_gui()
File "/home/cryo-poc/development/odemis/src/odemis/gui/main.py", line 237, in init_gui
self.tab_controller = tabs.TabBarController(tab_defs, self.main_frame, self.main_data)
File "/home/cryo-poc/development/odemis/src/odemis/gui/cont/tabs.py", line 5433, in __init__
tab_list, default_tab = self._create_needed_tabs(tab_defs, main_frame, …
=> gui model: give clear error messages when a required component is missing

src/odemis/driver/lakeshore.py
The script looks for commas in the error message. Usually this is a sign of a syntax error since arguments need to be passed by '%' instead of ','. However, in this case, the comma has a different meaning, so it's not an error. To avoid the false positive warning, just move the string to a variable.
=> driver-lakeshore: avoid false positive syntax error in runtest script

src/odemis/driver/pigcs.py, src/odemis/driver/smaract.py, src/odemis/driver/symphotime.py, src/odemis/driver/test/pigcs_test.py, src/odemis/driver/test/smaract_test.py, src/odemis/driver/test/symphotime_test.py, src/odemis/driver/test/technolution_test.py
We had managed to make sure all the exception were pickable, which is
necessary for the backend to transfer them to the client (via Pyro4).
However, it turns out that an object can be pickable, but not
unpickable... and we had not cheked for it.
This is because the unpickling mechanism is essentially a new
initialisation. So the arguments passed to it must be the same as the
one passed to the super (which stores them for picking).
In addition, with Futures, when an exception is raised, it's sent
back to the client as "one-way" call. So the backend wouldn't know
that unpickling the exception failed. That mained that not only the call
failed, but the client thought it was taking a very long time... and
block.
=> Fix all the exceptions which had this problem.
=> Add test cases to detect such …
=> driver: fix Exception non-unpicklable

src/odemis/gui/main.py
Commit 206595afa78 (FastEM GUI: overview tab) added support for a special version of the
MainGUIData, for the "mbsem". However, it broke the viewer, which has
no microscope.
=> gui main: fix standalone GUI not starting

src/odemis/acq/calibration.py, src/odemis/dataio/csv.py, src/odemis/dataio/test/csv_test.py
This is a known behaviour of the csv module of Python: the file gets
\r\r\n lines endings if not opening it with "newline=''". My
understanding is that it's due to the standard file wrapper to add a
newline, and the CSV writer also adding a newline.
See: https://docs.python.org/3.6/library/csv.html#id3
=> dataio/acq csv: fix extra new line on Windows

src/odemis/driver/piezomotor.py
Each axis has a different speed assigned. However, the speed assumed for
the move was shared between all axes. This meant that some of the
time-out values were incorrectly computed.
Also report the speed in the .speed VA, which is usefule for some time
estimations in client code.
=> driver piezomotor: fix same speed for all axes

src/odemis/gui/util/test/updater_test.py, src/odemis/gui/util/updater.py
The way to get the headers of the HTTPResponse have change in Python 3.
(It wasn't really anything official in Python 2).
Also modify a little bit the function to make it testable (on Linux)...
and add a test case.
=> gui util updater: fix download on Python 3

src/odemis/model/_vattributes.py
On Windows, we sometimes get errors like:
TypeError: Value '(5.615522460937501e-07, 6.356466064453125e-07)' must be a tuple only consisting of types (<class 'int'>, <class 'int'>, <class 'float'>).
It's extrermly hard to reproduce, and this has been going on for a year, with little extra findings.
Hopefully this information will hint us a little bit more.
=> model vattributes: in case the value is reject due to its type, indicate the type

src/odemis/driver/technolution.py
We scan the first field image twice due to HW restrictions. Remove the waiting time between the first and second scan as it is not needed. The scan_field call is blocking, meaning it waits until the scan is finished. Thus, we do not need to wait for the scan.
=> technolution driver: remove waiting time for fix, where we scan the first field image twice

src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py
Prevented the driver from working, and the tests from passing.
=> driver xt_client: fix typos

src/odemis/gui/cont/acquisition.py, src/odemis/gui/test/cont_acquisition_test.py
The output of a command is bytes, but the call to a command must be
string.
So if we take read the output of a command and pass it to another
command, we need to convert it.
Also fix the detection of screen names which contained a "-".
Also add small test cases.
=> gui cont acquisition: fix changing the screen brightness on Python 3

src/odemis/acq/stream/_live.py, src/odemis/gui/conf/data.py, src/odemis/gui/cont/tabs.py
Show a combobox control to select the scale (and indirectly the resolution). Display the pixelsize, which is adjusted with the scale.
=> fastem overview tab: show scale and scaled pixelsize

src/odemis/gui/comp/overlay/view.py
When activating the overlay with Ctrl+U, it would display the value only
after moving the mouse a bit. That's confusing, as it feels it didn't
get activated.
=> immediately read the mouse position, so that we can display the
value.
Also use cnvs.Refresh() instead of cnvs.request_drawing_update(),
as it avoid redrawing the whole buffer, while all we need is a repaint.
=> gui comp PixelValueOverlay: show value under cursor immediately after activating it

src/odemis/acq/align/spot.py, src/odemis/acq/align/test/spot_test.py, src/odemis/util/spot.py
- Sometimes it is necessary that the returned grid is a perfect grid, with equal scaling in x and y and no shear. With the possibility to select the similarity method this is now possible.
- Refactored the transformation calls to not use the deprecated call method, but use the apply method.
=> FindGridSpots: added transformation method selection.

src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/viewport.py
Now that we have the CAN_MOVE_STAGE ability, we can use it also
where we used to check if the view has a stage.
At init, if the view doesn't have a stage, drop the CAN_MOVE_STAGE.
Everywhere else, use CAN_MOVE_STAGE.
This is more than cosmetic: now if we have explicitly dropped
CAN_MOVE_STAGE, even if there is a stage, the canvas behaves
really as if there is no stage. That's important in fit_to_content()
and also allowing to drag when paused.
=> gui comp viewport/miccanvas: Fold view.has_stage() into CAN_MOVE_STAGE

src/odemis/driver/tmcm.py
Sometimes, moves did not start. The reason was that the "target reached" needs some time to be reset after a move has been requested. Otherwise, we would start a move and assume it's immediately finished because the bit was still set from the last move.
=> driver-tmcm: bugfix canopen driver

doc/develop/microscope.rst, install/linux/usr/share/odemis/sim/fastem-sim.odm.yaml, src/odemis/acq/align/delphi.py, src/odemis/acq/align/delphi_man_calib.py, src/odemis/acq/align/test/delphi_test.py, src/odemis/driver/orsay.py, src/odemis/driver/phenom.py, src/odemis/driver/simsem.py, src/odemis/driver/simulated.py, src/odemis/driver/tescan.py, src/odemis/driver/test/orsay_test.py, src/odemis/driver/test/phenom_test.py, src/odemis/driver/test/simsem_test.py, src/odemis/driver/test/simulated_test.py, src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py, src/odemis/gui/cont/microscope.py
This is a double edge PR. Firstly, it makes all the drivers and code use the axis "vacuum" on the chamber to control the vacuum level. Until now some drivers (orsay, xt_client) used "vacuum" while others (phenom, tescan, simulated) used "pressure". As they all only support a very limited set of positions, it makes more sense to call the axis "vacuum". There is a VA "pressure" to read the actual pressure.
Secondly, it extends the FASTEM simulator and fixes the GUI to work again together.
=> re-standardize the chamber axis to "vacuum"

src/odemis/driver/simcam.py
The image "andorcam2-fake-spots.h5" which can be used for the simulator has an integration time of 19.6 s. This causes an error to be raised since the range only accepts values up to 10. This is a simulator, so it shouldn't be a problem to increase the range to 20s even though such long exposure times are maybe not common in practice.
=> driver-simcam: increase range of exposure time

src/odemis/driver/piezomotor.py
For the absolute move, the steps need to be calculated based on the current position. Also, unlike the hardware only one axis can move at a time, so use twice the speed in the simulator.
=> driver: fix piezomotor simulator absolute move

install/linux/usr/share/odemis/sim/fastem-sim.odm.yaml, src/odemis/acq/fastem.py, src/odemis/model/_metadata.py, src/odemis/odemisd/mdupdater.py
The rotations will be specified as metadata to the e-beam component.
Is it ok to use default values or should we make the metadata required?
=> fastem: use different rotations for single and multi beam acqusition

src/odemis/gui/cont/acquisition.py, src/odemis/model/_futures.py
Also updated fastem acquisition to show the correct progress. Some considerations:
* I use a dict as an argument. Alternatively, a list of tuples might be possible to give the futures in order. However, this class also works independent of the order in which futures are started (future can run in parallel), so it doesn't matter.
* The regular ProgressiveFuture always raised a warning (starttime > endtime) every time a future was started after the expected endtime. Since many futures are initialized without endtime, the current time is used for both starttime and endtime, but if the future is started later (because the executor first had to finish another future), the starttime would update to a higher value, while the endtime remained the same (a value that is now in the past). That …
=> futures: batch future for time estimates of multiple ProgressiveFutures

src/odemis/cli/video_displayer.py, src/odemis/gui/comp/buttons.py, src/odemis/gui/comp/text.py, src/odemis/gui/xmlh/xh_delmic.py
Now that we exclusively support wxPython 4, let's not keep code to
handle old versions of wxPython.
=> gui: remove code for wxPython < 4

src/odemis/gui/cont/acquisition.py
Level doesn't have to be specified, default to None. Finishing an acquisition can be displayed with the "info" level (small "i" icon)
=> gui: bugfix status label

src/odemis/model/_futures.py, src/odemis/model/test/futures_test.py
Force the order of computation to reduce floating point error.
More importantly: fix test case which didn't pass anymore now that the
end time is updated immediately.
=> model futures: improve updating end time when starting a ProgressiveFuture

src/odemis/gui/model/__init__.py
PR #1803 introduced a check for the stage limits in the recenter_buffer function in miccanvas. This only works if the view has a stage. To make sure it doesn't fail, this case needs to be handled in the clipping function of the view.
=> gui: only clip stage position if stage is available

src/odemis/gui/comp/text.py
Commit db20de403cf (gui: remove code for wxPython < 4) removed the
wrapper class.
=> Use the wx.Validator class directly.
=> gui comp text: fix usage of old ValidatorClass

src/odemis/gui/cont/streams.py
=> gui: fastem project default name should not contain space

src/odemis/acq/stitching/_tiledacq.py, src/odemis/acq/stitching/test/tiledacq_test.py
Due to floating point errors, sometimes when requesting the acquisition
of an area exactly the multiple of the FoV (eg, 5x5 FoV), it would
acquire one extra tile (eg, 6x6 FoV). That would typically be due to
floating point errors. However, to make it more generic, we just round
down anything less than 1% of a tile.
Useful for the new overview acquisition window which allows the user to
specify the acquisition area in terms of FoV.
=> acq stitching: don't acquire extra tiles when area is a multiple of the FoV

src/odemis/acq/align/autofocus.py
The logging of the position and focus level in the autofocus code used %f, this only showed 6 digits after the dot.
For movements smaller than one um you could not read it in the logs.
Old log: Focus level at -0.000055 is 191563852251960608.000000
New log: Focus level at -5.476975e-05 is 1.915638e+17
=> Autofocus logging string formatting updated.

src/odemis/gui/win/test/acquisition_test.py
After the backend started was adjusted in #1912, no need to do the checks in the test cases. So directly call the backend starter and remove the checks.
=> simplify running the backend in test cases

src/odemis/util/test/util_test.py
After merging the meteor chamber PR, the roles become 'enzel' and 'meteor' explicitly, so having 'cryo-secom' role in the testing will always raise errors.
=> remove cryo-secom role from test files

src/odemis/acq/path.py, src/odemis/gui/cont/streams.py, src/odemis/model/_metadata.py, src/odemis/util/fluo.py, src/odemis/util/test/fluo_test.py
filter positions indicated as "pass-through" are actually no filter at
all.
So they don't fit for fluorescence microscopy. Essentially, they should
be skipped, or reported unfit.
=> util fluo: add support for pass-through filter

util/saconfig
We did compute the right value... but never store it.
So autozero behaved as a normal referencing.
=> util saconfig: really set auto-zero option

src/odemis/driver/technolution.py, src/odemis/driver/test/technolution_test.py
It turned out, that it is quite useful to adjust the flyback time during testing, debugging and also to find causes for the image artifacts. Make it a VA to be easy accessible. In practice later a "good" value will be found and will most likely be the same for all EA systems.
=> technolution driver: convert physical flyback time to VA

src/odemis/gui/cont/acquisition.py
We paused the streams just after starting the acquisition. In case a
stream was playing, this caused confusion as the acquisition code just
started the stream, which meant it would timeout.
=> gui cont acquisition Cryo: pause the streams *before* starting the acquisition

src/odemis/acq/test/move_test.py
Now that test.start_backend() automatically stop the current backend and
starts the right one, the code can be simplified a lot.
=> acq move test: simplify back-end startup

src/odemis/gui/cont/tabs.py
The target position is now on a separate line, instead of being cut
half-way. It's easier to review.
Also add extra digits to the position, to be extra clear.
=> gui cont tabs CryoChamber: Make METEOR confirmation move window easier to read

src/odemis/gui/model/__init__.py
Not every viewport supports it. So it should only be on the FeatureView
or FeatureOverviewView.
Mistake introduced in commit 01bdf242d9 (gui: add support for meteor in
chamber tab)
=> gui model: don't show feature toggle button on every view

install/linux/usr/share/odemis/sim/enzel-sim.odm.yaml
The FAV_POS_ACTIVE was not within the ACTIVE_RANGE, so couldn't reach
IMAGING mode.
Also add pass-through filter position.
=> config: fix ENZEL not reaching imaging mode

src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py
Probably due to some confusion with the Cryo interface, that viewport
got also converted to a "Overview" viewport.
That broke a bit the SECOM interface.
=> Revert.
=> gui main XRC: make the top-left SECOM normal again

src/odemis/util/filename.py, src/odemis/util/test/filename_test.py
timeshrt (eg, 1234) easily collided with the time, which annoyed users.
So drop it.
Also, for all the time pattern, check that it's within 5 min of the
current time.
=> util filename: remove timeshrt pattern and always check for time < 5min

src/odemis/gui/cont/streams.py
Introduced by commit 3d62376c37 (introduce official constant
model.BAND_PASS_THROUGH)... which missed one place to update.
=> gui cont streams: fix missing fluo.PASS_THROUGH

src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/viewport.py
If the client size is 0, the buffer could end up being 0 px image, which
cause some issues. => Make it at least 1.
Also handle the case where buffer size is 0 when updating the mpp, just
in case.
=> gui comp canvas: always make sure the buffer size >= 1

src/odemis/acq/move.py, src/odemis/acq/test/move_test.py
Reorder sample stage & aligner sub-movement for safer positioning.
Plus refactor the sub-moves sequence code to make it more readable.
=> Reorder ENZEL sub-moves

src/odemis/driver/xt_client.py
"auto" mode of blanker (value = None) can only be used if we know when
an acquisition is going on. So that only works if there is a detector.
No need to give hope to the user (code) when we cannot do that.
=> driver xt_client: don't provide "auto" mode on blanker if cannot be used

src/odemis/driver/andorcam2.py, src/odemis/driver/test/andorcam2_test.py, src/odemis/driver/test/cam_test_abs.py
Some cameras may support software trigger. In this case, it can save
around 20ms when starting the image. For short exposure times (eg, 20
ms), that's quite an improvement in frame rate.
One of the difficulty is that apparently on some cameras, not all
settings (cropping?) are compatible with the software trigger. So we
need to have some extra handling for this. Haven't seen such case yet
though...
So in total we have 3 modes now: non-synchronized, synchronized via
start/stop, and synchronized via software trigger.
To avoid code explosion, we first refactored to use a FSM style
(inspired by the avantes driver). It also supports switching between
synchronized/non-synchronized on the fly.
The garbage collector can take up to 20ms to run. It's not worthy to run
every time. On live mode, it …
=> driver andorcam2: Add support for using SW trigger

src/odemis/driver/smaract.py
As the `FakeMC_5DOF_DLL` range is hard coded, changes to the simulator range might result in "Position not in range error".
Plus some miscellaneous refactoring for `MC_5DOF, FakeMC_5DOF_DLL & MCS2` drivers
=> Smaract update 5DOF simulator range

src/odemis/model/_dataflow.py, src/odemis/model/_vattributes.py
In Python 3, __del__() can be called from the garbage collector. In
practice, it's a very common place for it to be called.
While running the garbage collector, other threads cannot run, so it's
not helpful to wait for it to react to the message. It just ends up
making the gc very slow, as it waits for 1s .
Anyway, in general, it's not useful to wait for the other thread to
finish __del__(). So let's just never wait.
=> model dataflow/vattribute: don't wait for the other thread in __del__()

src/odemis/gui/conf/data.py
Typically only 2 digits shown is sufficient. However, that gives some
odd behaviour, so as typing 235ms becoming 240 ms (displayed). Also, in
so (rare) case, the user cares about a very precise duration, and having
3 digits of control is needed.
In most cases, this changes should have no noticeable effect, as values
like 5s, or 12µs are always displayed the same. If the user types
a round value, it stays round.
=> gui conf data: increase time VA accuracy from 2 to 3

src/odemis/gui/cont/tabs.py
On the METEOR, it's now allows to access the tab when FM is not active
(just to look at the previous images acquired). However, as the focus
always slightly move, the position is updated, and that cause the
ACTIVE_POS to be updated to the (almost) DEACTIVE_POS.
Anyway, it's not a big deal to go back always to the safe ACTIVE_POS.
Ideally, the chamber tab (acq.move) will be extra clever and
store/restore it, if it's safe.
=> gui cont LocalisationTab: don't save focus ACTIVE_POS as soon as it moves

src/odemis/driver/technolution.py, src/odemis/driver/test/technolution_test.py
The scanGain defined the end of the scanning ramp (offset + amplitude). So whenever the user wanted to change the amplitude, they needed to add the offset. Or whenever the offset was changed, the gain needed to be changed accordingly. Redefine the scanGain to scanAmplitude. Change the behavior of the code, so that the scanAmplitude is truely independent of the scanOffset.
* rename scanGain to scanAmplitude
* split up the test cases to cover a single item
* improved/fixed some tests, comments and doc strings
* fixed typo in EXTERNAL_STORAGE
* added tests for calculation of scanner offset and gradient as defined in the asm
* reordered imports
* made bit range for descanner also global variable similar to volt range for scanner
* improved plotting test cases and changed import for matplotlib …
=> technolution driver: change definition of scanGain to scanAmplitude

src/odemis/driver/simcam.py
In some rare cases, mostly when the stage position is very large,
floating point errors would cause the top-left area position to be not
excatly 0, and slightly negative. This would be considered as a major
error, stopping the image generation.
Instead, just round and realise that it's all fine...
=> driver simcam: fix pixel coordinates computation sometimes failing

src/odemis/gui/util/img.py
The label of the top tick on vertical scale could go slightly off
screen.
=> Don't use arbitrary 2 px safety, but the actual size of the label:
label height.
=> gui util img: make sure that draw_scale() always fit text inside

src/odemis/driver/andorcam3.py
Copy-paste error.
This causes binnings like 4x1 to set the wrong resolution,
confusing the acquisition code, and preventing any image from being
received.
=> driver andorcam3: fix large horizontal binning not working

src/odemis/driver/smaract.py
Sometimes a move of 0 would be considered so fast that it would cause a
division by 0.
=> Add always some extra "overhead" time so that no move takes 0s.
Also take the opportunity to simulate better move duration.
=> driver smaract MCS2: fix simulator with move 0

src/odemis/gui/test/comp_canvas_cairo_test.py
test_reshape() wasn't testing anything, so remove it.
test_nanana() tests the mpp changes, which is sort of useful. Fix the VA
initialisation.
=> gui test comp_canvas_cairo: fix VA value out of range

src/odemis/gui/cont/tabs.py
As multiple overview maps can be acquired for different features, existing maps shouldn't be overwritten by new ones.
=> Localization tab: don't overwrite overview maps of the same stream

src/odemis/gui/win/acquisition.py, src/odemis/gui/win/test/acquisition_test.py
If the stage was at the wrong place, an error would be reported... and
then the rest would fail with an exception.
=> Now handle properly when area cannot be computed by setting .area to None
Also handle zlevels computation corner cases when it's near the focus
range.
Also rearange a little bit the function organization to make it clearer.
Also update the test cases to not depend on a simulator, and actually
pass. (got broken when the simulator was adjusted)
Also remove some unneeded code.
=> gui win acquisition OverviewAcquisitionDialog: improve area computation reliability

src/odemis/driver/actuator.py
The stage requires a set of axis to reference, while the axis were passed as dict keys. This commit ensures the axis are passed as a set.
=> Actuator: Fix DualChannelPositionSensor referencing.

src/odemis/acq/fastem.py
First image is top/left corner of megafield. As soon as stage-scan is used, movements need to be opposite order to fulfill this requirement.
=> fastem acqu manager: change the direction of stage move to match the requirements

src/odemis/driver/actuator.py
The matrix is now just called ".matrix".
=> driver actuator ConvertStage: fix RigidTransform API use

src/odemis/acq/fastem.py
The changes in commit 8a07a870b5ef88e33f22112dbaecf4a3fa89d356 caused problems with overview imaging. The commit removed copying the fastem stream object into a sem stream object.
Because a fastem stream object was used the overview image settings were overwritten with the live view image settings, this turned on the immersion mode and only a quarter of the overview image was acquired.
=> Fastem revert changes in overview imaging

src/odemis/gui/cont/streams.py
It was confusing to the user that when they added a second ROA in a new project the rectangle was red all of a sudden. To them it indicated something had gone wrong.
=> Fastem streams: make red the last color to be picked in the color order.

src/odemis/gui/cont/microscope.py
It is confusing, that when the chamber is pumped, an action "unload" is displayed as button label. It is more intuitive to display the state "loaded" when pumped and "unloaded" when vented. The ebeam button also indicates a state and not an action. The action for both buttons is defined in the corresponding tooltip.
=> Chamber tab: pump/vent button - display state instead of action as label

src/odemis/acq/fastem_conf.py, src/odemis/acq/test/fastem_conf_test.py
We pause the stream in between each acquired image, this already blanks the beam. Forcing blanking and subsequent unblanking of the beam caused it to blanked during acquisition sometimes.
In the fastem configuration set the blanking to False for live view and overview imaging, so it's unblanked during acquisition.
=> fastem: Unblank beam before live view and overview image acquisition

src/odemis/driver/test/pvcam_test.py
The static test doesn't need the real hardware, but it at least needs
libpvcam, which we don't have on normal computers (because only 32 bit
version exists)
=> driver pvcam test: skip every tests if TEST_NOHW

src/odemis/util/__init__.py, src/odemis/util/graph.py, src/odemis/util/random.py, src/odemis/util/registration.py, src/odemis/util/test/graph_test.py, src/odemis/util/test/registration_test.py, src/odemis/util/test/transform_test.py, src/odemis/util/transform.py
Goals:
- improving readability
- improving robustness
- improving test coverage
- bug-fix in handedness
Includes a module to work with graphs (structures made of vertices and edges).
This PR does not deprecate `FindGridSpots` as it is still in use by `/scripts/spot-grid.py` as well as multiple calibrations in `fastem-calibrations`
=> Refactoring of FindGridSpots and ancillary functions

src/odemis/driver/andorshrk.py
This unlikely case happens if the turret is unknown by the spectrograph.
It's handy to see a warning, so at least it'll clearer in the log that
something is wrong with the spectrograph.
=> driver andorshkr: add warning if the turret has no grating

src/odemis/driver/smaract.py
Commit 126021111 (5DOF simulator range should always fit requested
range) had a bug which essentially caused it to be a no-op.
Fix the range limit so that when passing a smaller range,
the axis range is really smaller that the initial range.
This fixes test case test_unreachable_position_error.
=> driver smaract: fix 5DoF sim not using requested ranges

src/odemis/gui/test/comp_settings_test.py
The test cases failed because there were more children then the test cases assumed.
add_readonly_field always adds 2 children, independent of whether a value is passed or not, while the test cases assumed only 1 child was added when no value was passed.
=> GUI comp settings test fixes for the number of children created.

src/odemis/model/_components.py
Provides a spotSize VA on a model.DigitalCamera instance. This is equivalent to the standard deviation of the Gaussian approximation of a fluorescence microscope point spread function, measured in no. of pixels of the camera.
The value can be used as a characteristic size parameter when filtering an image prior to spot detection.
Will be used to clean-up the code in `fastem-calibrations:/src/fastem_calibrations/pattern_calibration.py`
=> Added pointSpreadFunctionSize VA to model.DigitalCamera

install/linux/usr/share/odemis/hwtest/andor3-only.odm.yaml, src/odemis/driver/andorcam3.py, src/odemis/driver/test/andorcam3_test.py
For some applications, the chip area is too big. We just don't want the
user to ever have to know the chip is bigger, because outside of the
area, the signal is useless. So allow to clip the maximum resolution, to
behave as if it was the max res of the hardware.
=> driver andorcam3: add max_res argument to limit the maximum resolution

src/odemis/acq/fastem.py
In 0088f4e5f3baf8e51cae7c4e5dc71d499990c11f a fix was introduced to have a larger timeout for the first field.
Remove that fix and just make the timeout larger to catch everythin that might possibly cause the acquisition to succeed but take longer than usual.
=> Acq fastem: Make the timeout larger.

src/odemis/gui/conf/data.py
It's just a info useful for the optics nerds, but shouldn't be shown in the settings by default.
=> gui conf data: hide "point spread function size" info

src/odemis/gui/comp/overlay/view.py
If the cursor happens to be outside the FoV, quad_hover() returns (None, None).
In Python 2, this was not an issue as it's possible to compare None to
an int. It didn't do the right thing, but it ended up having roughly the
right effect. That's not true for Python 3, which complains loudly about such
comparison.
=> Explicitly check for None.
Drop the comparaison to max_len as anyway it should never happen.
=> gui comp DichotomyOverlay: fix error when cursor hovers out of FoV

src/odemis/acq/test/fastem_test.py
Fixed test_estimate_acquisition_time, test_stage_movement and test_pre_calibrate because they failed due to changes in the code.
Added the use of the fastem-sim-asm yaml file, for tests that need an asm component to run.
Minor changes to make the coding style consistent over the entire module.
=> Fastem acquisition test cases: fixes and code clean up.

src/odemis/acq/fastem.py
This ensures a better progress update on the progress bar in the GUI. tiledacq.py does not have a good time estimation yet. It updates the progress based on the original estimation and assumes a fixed duration per tile. After each tile it removes this fixed time per tile from the original estimation. However, if the estimation was wrong, the update is always wrong. Solution is to temporarily remove the connection to the sub-future and just show the progress in the GUI based on the estimated time, which simply counts down for now.
=> FASTEM overview acq: remove connection of progress of the underlying future to the main future

install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml
Normally the descanner scan gain is set during calibration, when simulating the hardware this is not possible. Since some code is dependent on this value it is now added to the fastem simulator yaml file.
=> Yaml fastem-simulator: add scan gain metadata to descanner.

src/odemis/model/_metadata.py
- use triple double quotes instead of triple single quotes for docstring
- make sure there are exactly two spaces between comments and code
- I did not clean up comments that extend the line length, because I think doing so would decrease readability
=> model metadata: changes to improve pep8 compliancy

src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py
During megafield acquisition it should be possible have the fields overlap by a certain factor. This commit adds an overlap argument to the ROA class.
calculate_field_indices has been updated to calculate the number fields when there is overlap. And get_abs_stage_movement has been updated to get the absolute stage movement for overlapping fields.
=> Acquisition fastem: add overlap argument to stage movement.

src/odemis/acq/test/move_test.py
If it's not a test, it shouldn't be called test_*, because otherwise
unittest automatically calls it... and it fails.
=> acq move test: fix function name to not start with test_

install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml
On the metadata of the MultiBeam Scanner the SCAN_OFFSET_CALIB and SCAN_AMPLITUDE_CALIB have been added.
Normally these are calculated in the calibrations but these calibrations do not run with the simulator.
=> fastem-asm-sim yaml: add calibrated metadata for simulator.

src/odemis/driver/test/kryoz_test.py
The driver doesn't really work yet anyway... and especially there is no
simulator, so let's not try to run it when no hardware is available.
=> driver kryoz test: don't run when no hardware

src/odemis/gui/model/__init__.py
It's a little bit confusing as these 2 metadata are quite a little bit
redundant, and not on the same component. So it's easy to update one
while forgetting to update the other one. Doing so would cause very odd
stage movement from the GUI.
=> Detect something is wrong early.
=> gui model: On METEOR, check that the stage.POS_ACTIVE_RANGE is within stage-bare.FM_IMAGING_RANGE

src/odemis/acq/align/fastem.py
In case fastem_calibration is missing, all calibrations are considered
None. So calling .estimate_calibration_time() doesn't work. We need to
explicitly check for it.
=> acq align fastem: don't completely fail time estimation if fastem_calibration is missing

src/odemis/gui/comp/miccanvas.py, src/odemis/gui/cont/tabs.py
Now that fit_to_bbox() has been moved to the main class, it's been
"improved" and doesn't fail if the scale would be too small.
However that meant the hack to detect that the resizing failed didn't
detect it anymore. Instead of hacking it even more, move the zoom out
request to the tab controller, which is more in charge of deciding when
the view should be changed any way. It allows to make it a little bit
hacky...
=> gui fastem cont/comp: move hack to zoom out canvas at init

src/odemis/acq/align/test/fastem_test.py
When updating the z position in the FAV_POS metadata on the diagnostic ccd, the x and y values were removed when using component.updateMetadata . Instead read MD first, use dict.update to add the z MD and then do component.updateMetadata.
=> fastem fix test: don't overwrite x and y in FAV_POS

src/odemis/gui/cont/streams.py
Autofocus and autostigmation is not working correctly yet, the functionality should be updated on the xtadapter side. Once that is done the buttons can be added again.
=> GUI fastem: comment autofocus and autostigmation buttons.

src/odemis/driver/actuator.py
The MD_POS_COR is used by the driver to adjust the 0 position. So there
are some specific constrains. The other metadata is completely free.
=> Explicitly check MD_POS_COR only.
This allows adding other metadata, such as MD_CALIB, for other purpose.
=> driver actuator RotationActuator: Only check the MD_POS_COR content

src/odemis/driver/smaract.py, src/odemis/driver/test/smaract_test.py
If referencing was cancelled and restarted just after, the simulator would sometimes think
that the second referencing is also cancelled.
=> Reset the flags when starting a new referencing procedure.
This fixes an intermittent test case failure.
=> driver smaract.Picoscale: simulate better cancelled referencing

util/pytest_log_filter.py, util/runtests.sh
This outputs the test cases results a bit cleaner and only shows the failed testcases. It still needs some refinement (removing extra new lines, 1 corner case where the entire testcase is outputted) but in general it is faster to produce a readable test report this way.
The script is based on the script runtests.sh and as little as possible is changed to make the results as identical as possible.
This is the layout this test report is as follows:
```
Running /home/testing/development/odemis/src/odemis/driver/test/tmcm_test.py...
ERROR: test_cancel (__main__.TestActuatorRelEnc)
File "/home/testing/development/odemis/src/odemis/driver/tmcm.py", line 2343, in _getCurrentPos
pos = startp + (endp - startp) * (now - startt) / (endt - startt)
ZeroDivisionError: float division by zero
Running …
```
=> Added pytest test report functionality

src/odemis/acq/test/flim_test.py, src/odemis/acq/test/path_test.py, src/odemis/acq/test/stream_test.py
The nikonc driver is not easily available for python3. When tests were run that required this driver the backend failed to start. In the setupclass it is now checked if the driver is available and otherwise the tests are skipped
=> Acquisition tests: skip test cases that require the nikonc driver.

src/odemis/__init__.py
We use git just to check the version number in case we are running from
the development branch (and so git repo).
If "git describe" returns an error, we used to completely fail.
Now just fallback to the standard way to detect the version number.
It might be not exactly the right version, but it's much better than not
starting at all.
Useful with the changes to git that prevents running it as a different
user. So running git as root (which is the case when staring the
backend) failed if the git repo was owned by the user.
=> init: handle better git error

src/odemis/acq/align/fastem.py, src/odemis/acq/align/test/fastem_test.py, src/odemis/acq/fastem.py, src/odemis/acq/fastem_conf.py, src/odemis/gui/__init__.py, src/odemis/gui/comp/miccanvas.py, src/odemis/gui/comp/stream.py, src/odemis/gui/cont/fastem_acq.py, src/odemis/gui/cont/project.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py, src/odemis/gui/model/__init__.py, src/odemis/gui/xmlh/xh_delmic.py
* add dark/gain to calibration manager
* make controller independent of each other
* make calibration controller using a prefix argument to be able to use same class for all calibration steps
* make the gauge having a fixed size in the GUI
* use short version for text label showing the progress
* fix: ROC size should be calculated based on multibeam resolution and pixelsize
* allow adding/removing ROCs
* synchronize gui with main model (active scintillators and calibration regions defined)
* remove unnecessary properties in tabs
=> fastem calibration 2: dark/gain calibration per scintillator

plugins/update_rot.py
Currently, when the SEM is scanned via a external card, but the controls
can be read/written via an API, the .rotation VA shows the rotation, but
the data doesn't have this information in the metadata.
That means that the image is always shown as if rotation is 0°. In many
cases that's fine. However, on the SECOM, that's not enough because the
fine alignment overlay looks at .rotation and assumes that MD_ROTATION
will be set. To compensate for it, it sets MD_ROTATION_COR on the
optical images. This causes the optical images to be incorrectly
rotated!
=> copy .rotation as MD_ROTATION & MD_ROTATION_COR. So the SEM image is
not rotated, and the fine alignement is aware of it, so it doesn't
rotate the optical image.
=> plugins: new update_rot plugin to connect ebeam rotation VA to metadata

src/odemis/acq/align/fastem.py
It's supposed to be fine to import even if fastem_calibration is not
available. However due to extra functions loaded, that wasn't the case
anymore.
=> acq align fastem: fix import when fastem_calibration is missing

src/odemis/model/_futures.py, src/odemis/model/test/futures_test.py
When the progress was set the start time was not correctly updated.
If the sub-future was cancelled, also cancel the batch future.
Add test cases for batch future.
=> progressive batch future: fix start time in progress update

src/odemis/gui/cont/fastem_acq.py
Update the estimated acquisition time displayed in the GUI when the ROA is resized or when the dwell time is changed.
=> fastem-update-acq-time

src/odemis/acq/align/fastem.py, src/odemis/acq/fastem.py, src/odemis/acq/fastem_conf.py, src/odemis/acq/test/fastem_test.py, src/odemis/gui/cont/fastem_acq.py, src/odemis/gui/cont/project.py
When acquiring an ROA we run a set of calibrations before each ROA. So far there was own code for this in the acquisition manager. However, now that we have the calibration manager, make use of it.
=> FASTEM: use calibration manager also during acquisition

src/odemis/gui/cont/fastem_acq.py, src/odemis/gui/cont/tabs.py
Now run all calibrations, but in the calibration module we make sure to only log the values for now.
=> fastem: run all calibrations

src/odemis/gui/comp/stream.py
In commit a8fec30dee4 (move cryo acquired streams control to the streambar
controller), I tried to "clean" the event removal. However, as the
control is destroyed, the event is automatically removed. In some cases,
this would even cause an error as we were accessing dead objects.
=> gui comp stream: remove "improvement" to event handler which broke closing streams

src/odemis/driver/andorcam3.py
Missing break in for loop caused every gain to be reported as "unhandled",
although everything worked fine.
=> driver andorcam3: fix incorrect warning

src/odemis/acq/align/fastem.py
The cell translation calibration is run for a specific set of values for the single field resolution and the cell complete resolution. Thus, for the acquisition it is necessary to also use this settings. As long as adjustable resolution and cell size are not supported in the calibration itself, also do not allow to use different value for the acquisition.
=> FASTEM: Return resolution and cell size for cell translation calibration

src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py, src/odemis/gui/cont/streams.py
For the overview imaging it is necessary to adjust the brightness and contrast beforehand.
Add a brightness and a contrast VA to allow setting these values.
=> driver xt_client: allow to set the brightness and contrast

src/odemis/gui/cont/tabs.py
It's possible to open multiple files simultaneously, but until now the user had to
select each file one at a time using the "From file..." button.
Now, it's directly possible to select multiple files. Either from the
"open" button, or from the "From file...".
Handy when trying to open quite a few files at the same time, like
tiles.
=> gui cont tabs: allows to select multiple files to open in analysis tab

src/odemis/dataio/hdf5.py, src/odemis/dataio/test/hdf5_test.py
It's quite handy metadata, to know which camera was used for imaging.
Of course we also store this info in MD_EXTRA_SETTINGS, but on systems
with multiple cameras, you have to guess which camera was used.
=> dataio hdf5: read/write MD_HW_NAME and MD_HW_VERSION

src/odemis/gui/conf/file.py, src/odemis/gui/cont/tabs.py
It can happen that the default project dir cannot be created, for
instance, it got unmounted, or permissions changed. Let's not completely
fail to start the GUI in such case.
=> fall back to the default project directory.
Also, add a "/" after the root project dir because it's actually supposed to
contain the *previous* project directory, and then the parent folder is
used. As it's directly the parent folder, we need to indicate that with
an extra "/".
=> gui conf: fallback to default project dir if impossible to create a new project folder

src/odemis/gui/cont/streams.py
HW VAs are mixed for the emitter and detector, but until now we only
used the emitter order. That meant that if the VAs came from the
detector, the order would be roughly random (except for the VAs who
share the same name).
=> use both orders, one after the other. It's not an issue if a VA is
listed several times, the first occurence will be used.
=> gui cont streams: fix display order of HW Detector VAs

src/odemis/gui/util/widgets.py
Probably we never tried (except when stopping the GUI).
Need to set the argument name explicitly, as for the VAConnector.
=> gui util widgets: fix error when disconnecting a AxisConnector

src/odemis/util/test/units_test.py, src/odemis/util/units.py
Avoids having values < 1ms represented as "0 s". The µs can still matter
a lot, depending on which time frame we care about.
=> util units: add also µsec display to the time display

src/odemis/gui/comp/file.py, src/odemis/gui/comp/settings.py, src/odemis/gui/comp/stream.py
By default the text fields are too small, at least with the default
Ubuntu theme. The bottom of letters like p or µ was hidden.
So reduce the margin and increase the text height. It
should actually take a few pixels *less* in total now.
=> gui comp: increase the text fields in height to ensure all characters are shown

src/odemis/gui/util/img.py
When exporting an image, some metadata in the legend was written like
"Exposure time: 1s" and other like "15 kV". The latter version was sort
of understandable, but not very much, and the mix was odd.
=> Put a label for all metadata.
=> gui util img: add label of each metadata in legend

install/linux/usr/share/odemis/sim/secom-sim-pretty.odm.yaml
Some time ago the CCD simulator must have adjusted the metadata, and
this caused the images to not overlay properly anymore.
It's now easier, we just put the original lens magnification.
=> config: fix secom-pretty sim to match the images again

src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/util/__init__.py
Do not change the position (mode) while the stage is moving. In
particular:
* The alignment and localization tab don't get temporarily enabled
half-way through a movement
* The position switch buttons don't get enabled during movement
Also change the METEOR buttons to turn orange during the move, and green
at the end of the move.
Also, on ENZEL, always report THREE_BEAMS instead of IMAGING.
Also, in case of cancellation, don't log an error.
Also clean-ups:
* ENZEL cryo tilt is not needed anymore
* ENZEL IMAGING is not needed anymore
* Don't use internal _state of Future, but just .done() or .running()
In general the change shouldn't have any effect on movement, but only on
the display of the current position.
=> acq/gui: Fix position display for ENZEL/METEOR

src/odemis/gui/win/acquisition.py
The estimated acquisition time is very rough. Rounding to 1s is more
than sufficient, instead of say "2 minutes, 3 seconds, 343 milliseconds,
123 microseconds".
=> gui win OverviewAcquisitionDialog: round up the estimated time

src/odemis/driver/andorcam3.py
Fix typo in message (in > it).
Shorter message.
Also catch error COMM, which can also be solved by power cycling the
camera.
Log the exact error in the log.
=> driver andorcam3: better handling of errors at init

src/odemis/driver/smaract.py
Now .reference() has to take an argument, to follow the standard API.
So need to update the internal caller too.
=> driver smaract: fix 5DoF ref_on_init failure

src/odemis/util/test.py
It's convenient to quickly know which axis is not equal.
=> util test: improve error message in assert_pos_almost_equal()

src/odemis/driver/avantes.py
The measurement timer could already be cancelled. In this case, no need
to stop it.
=> driver avantes: fix simulator sometimes failing during acquisition end

plugins/ext_spec_map.py, src/odemis/driver/andorcam2.py, src/odemis/driver/test/andorcam2_test.py, src/odemis/gui/conf/data.py
We already had a VA with the same meaning in the technolution driver.
Let's use the same name.
=> driver andorcam2: rename framePeriod -> frameDuration

src/odemis/gui/cont/menu.py
It was trying to reset the overview image on the current tab... but that
only works on the live tab. So just explicitly retrieve the live tab.
=> gui cont menu: fix "Reset overview image" when not on SECOM live tab

src/odemis/driver/tmcm.py, util/tmcmconfig
Mostly the same as the 3210, but with a single axis.
=> driver tmcm: add support for 1211

src/odemis/acq/align/delphi.py, src/odemis/acq/align/transform.py, src/odemis/driver/tfsbc.py
Since numpy 1.14, not specifying rcond causes a warning, because it
slightly changed behaviour.
I don't think we ever really cared on the "Cut-off ratio for small
singular values". So just explicitly use the new behaviour (None),
which is probably better.
=> avoid warning in numpy.linalg.lstsq()

src/odemis/gui/comp/stream.py
Make more space for the name (by removing extra margin on the right).
If the name still doesn't fit, show an ellipsis, to indicate it's
trunctated.
Always show the full name by hovering over the name.
=> gui comp stream: better handle long stream names

src/odemis/acq/align/delphi.py, src/odemis/acq/align/transform.py, src/odemis/driver/tfsbc.py
Commit 99e9bd2 (avoid warning in numpy.linalg.lstsq()) actually broke
code when using numpy 1.13 or older. That means it broke code on Ubuntu
18.04 (and before).
=> Using rcond=-1, which is compatible with old versions of numpy.
It even keeps the old behviour, so we are even more certain to not
break things due to the "cut-off ratio for small singular values".
=> fix numpy.linalg.lstsq(..., rcond=None) not working on Ubuntu 18.04-

install/linux/usr/share/odemis/sim/meteor-sim.odm.yaml, src/odemis/gui/cont/tabs.py, src/odemis/gui/model/__init__.py
We had requirement that stage.ACTIVE_RANGE is within
stage-bare.IMAGING_RANGE, but that doesn't really make sense as the
stages are in different referentials. In practice, on many systems, that
was fine because the change of referential didn't affect the value too
much, and IMAGING_RANGE can be quite wide.... but on some systems that
just doesn't work.
=> Move the check to when moving the stage to FM. At least, the first
position reached in FM should be a legal position!
=> gui model meteor: move stage range check

src/odemis/gui/test/comp_overlay_test.py, src/odemis/gui/test/dev_rotknob_test.py
They expected that the SparcARCanvas provides the overlay. However, it
doesn't do that anymore. In the GUI it's now created by the viewport ARLiveViewport.
=> instantiate a ARLiveViewport, and use the canvas + overlay created
there.
=> gui test: fix tests using MirrorArcOverlay

plugins/la_spec.py
For EK, the lens-switch now has positions as metadata, instead of
choices. => support both
=> plugins la_spec: fix when microscope file uses EK configuration

src/odemis/gui/comp/overlay/world.py, src/odemis/gui/model/__init__.py
Reading the pixel size was incorrect for two reasons:
* used X dim for both dimensions
* The binning was read from the metadata but some CCD don't provide the BINNING in .getMetadata()
It's always available on .binning
=> gui model: fix EK and pole position computation when binning > 1

src/odemis/odemisd/start.py, src/odemis/odemisd/test/start_test.py
Also made some basic test cases.
@pieleric Is this more or less what you had in mind to fix CSDM-888?
Adding a pop-up message is quite easy from here on. But maybe you envisioned a different implementation direction?
In response to:
https://delmic.atlassian.net/browse/CSDM-888
=> Return a different error code if the GUI fails to start in odemis-start. 

src/odemis/acq/stream/_sync.py
The default behaviour when there are multiple polarizations is to store
the average. That's not handy here, we want to store each one
individually.
The analysis tab doesn't show it in a great way, but it works. That's
enough for now.
=> acq stream sync SEMAngularSpectrumMDStream: if multiple polarizations, store them separately

src/odemis/dataio/csv.py, src/odemis/dataio/test/csv_test.py
In commit 1dc62698 the last line of the export function was adjust and it called the variable acq_types, but this doesn't exist, it should be acq_type. This commit fixes that and adds a test cases to check a value error is raised when an unknown acquisition type is passed.
=> csv export: fix bug with unknown acquisition type.

src/odemis/driver/simcam.py
Like all other CCD components.
=> driver simcam: store binning in metadata

src/odemis/odemisd/main.py
The execute bit on the mask doesn't really mean much for new files.
However, when creating directories, that allows to add files to the
directory... which is a very useful feature.
No driver seemed to depend on this, however on Ubuntu 20.04, some
libraries depend on OpenMPI, which creates some directories in the
background.
This prevented the backend from being started as a normal user on Ubuntu
20.04.
=> odemisd: extend the file mask to include the execute bit

src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py
Don't convert relatives moves directly to absolute moves. Let the SEM
do that. This has a couple of advantages:
* for rotation moves, less complexity with dealing with (fake) out of range,
and handling cases where going a small negative turn could be
converted  to a large positive turn.
* No need to read the current position first (and mistakenly force the
move to each axis).
* Simplify the code with range checking, by letting the xtadapter do
that.
=> driver xt_client: use the relative move call for relative moves

src/odemis/driver/smaract.py
moveAbs() was not using the inversion for the inverted axes.
This caused axes to go to the opposite position!
=> driver smaract SmarPod: fix inverted axis moveAbs()

src/odemis/driver/pmtctrl.py, src/odemis/driver/tmcm.py, src/odemis/gui/comp/canvas.py, src/odemis/gui/comp/overlay/base.py, src/odemis/gui/comp/overlay/world.py, src/odemis/gui/conf/file.py, src/odemis/gui/conf/util.py, src/odemis/gui/cont/microscope.py, src/odemis/gui/cont/streams.py, src/odemis/gui/cont/views.py, src/odemis/gui/dev/powermate.py, src/odemis/gui/util/__init__.py, src/odemis/gui/util/updater.py, src/odemis/gui/util/widgets.py, src/odemis/util/__init__.py, src/odemis/util/img.py
This old method name has been deprecated for a long time.
Using logging.warning() works since even longer.
=> This avoids warnings about using a deprecated function, and
helps make Odemis compatible with Python 3.10
=> logging.warn() -> logging.warning()

src/odemis/driver/rigol.py
The connection was sometimes timed out because the VM was too slow.
=> Wait a second to listen so the slower VM on the test machine can catch up.

src/odemis/util/spectrum.py
The error is by default discarded when calling the high-level functions
to load the metadata. In such case it just return "px" data.
It's handy to have a trace that something went wrong (and what).
=> also log the error.
=> util spectrum: log the error when metadata is not usable

src/odemis/gui/comp/combo.py, src/odemis/gui/util/img.py
On Windows, Bitmap.CopyFromBuffer() doesn't work. It generates an error
like:
RuntimeError: Failed to gain raw access to bitmap data.
Anyway, there is actually a better function for what we need: FromBuffer().
So let's use it. Actually use the code from gui.util.img, to avoid
duplicating code.
This fixes the display of the colourmaps in Windows.
=> gui: fix display of colourmap combo-box on Windows

src/odemis/gui/comp/foldpanelbar.py
Instead of manually converting the colour from float to int, badly, which is
implicitly converted to wx.Colour, call frgb_to_wxcol().
Especially this avoids warnings that a float is passed.
=> gui comp foldpanelbar: use more explicit colour conversion function

src/odemis/acq/move.py, src/odemis/acq/test/move_test.py
It's all very near, we cannot really distinguish the positions.
So concider them equivalent.
Also fix some test cases.
=> acq move: concidered ENZEL alignement position also part of the THREE_BEAMS position

src/odemis/driver/powerctrl.py, src/odemis/driver/test/powerctrl_test.py
Allows to disable the check for power on hardware not connected to any
EEPROM.
=> driver powerctrl: add check_power option

src/odemis/driver/actuator.py, src/odemis/driver/test/actuator_test.py
After moving to a position, the actual reported position might not be exactly the position requested. It’s can be because the stage has a quantized position (ie, number of steps) like the TMCM, or the stage has an encoder which keeps updating to positions very near-by.
When asking to move again to the “same” position, the FixedPositionActuator passes on the request. Usually, it has little effect, because it causes a very tiny move, which is either discarded, or very quick. However, in case of anti-backlash under it, there is 50% chance that it it thinks it’s in the “bad” direction, and causes a small step back, followed by a small step forward. That can be quite long.
=> In FixedPositionActuator, after moving to a position, remember where it arrived. Later on, when requested to move to a …
=> driver FixedPositionActuator method improvement and addition of testcase

install/linux/usr/share/odemis/sim/sparc2-ek-polarizer-sim.odm.yaml, install/linux/usr/share/odemis/sim/sparc2-polarizer-sim.odm.yaml, src/odemis/acq/path.py, src/odemis/acq/test/path_test.py, src/odemis/gui/cont/tabs.py
For ek-align, we used to just use the "ek" path. However, we want to
force the grating and the filter to be in "good" positions.
That'd be ugly to do in the GUI, so explicitly place it in the OPM.
It will force the axes everytime the stream starts. The GUI still allows
the user to change to different (and odd) positions while playing the
stream.
For the standard EK streams, the GUI takes care of setting the default
position of these streams when it's added by the user (and the user can
later override it).
Also extend the path test cases, to actually test a EK simulator.
Also found a bug in the Sparc EK polarizer simulator.
=> acq path: distinguish "ek" path and "ek-align" paths

install/linux/etc/odemis.conf, src/odemis/acq/align/delphi.py, src/odemis/driver/phenom.py, src/odemis/driver/simsem.py, src/odemis/driver/test/phenom_test.py, src/odemis/gui/cont/settings.py, src/odemis/gui/cont/tabs.py
The contrast brightness function is renamed to align functions in simsem and phenom with xt_client. 
Please check the two questions added as TODOs in the code.
Testing Method - Respective unit tests were run for all three of them. 
Output               - Tests ran properly for phenom and simsm(passed, ignored)
- one test in xt_client failed - TestMBScanner 
`    raise TypeError("XTtoolkit must be running to instantiate the multi-beam scanner child.")
TypeError: XTtoolkit must be running to instantiate the multi-beam scanner child.`
=> Renaming ContrastBrightness

src/odemis/driver/orsay.py, src/odemis/driver/test/orsay_test.py
We had already a VA called .shift for the same meaning (eg, in phenom,
and simsem). Later on, came xt_client which introduced beamShift, and we
picked that one up.
However, as it's on the scanner component, typically "shift" is clear
enough. It's also the oldest name. So let's use that one.
That should ensure that all client code can work on any hardware.
(Still need to rename the xt_client VA)
=> driver orsay: rename beamShift -> shift

src/odemis/acq/align/test/shift_test.py
acq/drift/test/shift_test.py was initially placed here because it uses the same images as the images used in the drift test cases. Move shift_test.py to acq/align/test and make sure to update the path to the test images. (don’t forget to run the test cases and make sure they still pass)
Testing :- passes 12/12 test cases after refactoring
=> Refactoring shift_test_case to align sub-directory

src/odemis/acq/test/stream_test.py
On the VM, sometimes the test cases fail. Most probably because we are
not waiting long enough. The time in the Event.wait() can be quite long,
as it's just the maximum time it can wait. As soon as the image is
ready, it'll finish anyway, so it's fine to put a relatively large
number.
=> acq test stream: give extra time

src/odemis/acq/drift/test/drift_test.py, src/odemis/acq/test/leech_test.py
Added test functions in the AnchoredEstimator for the following functions
1. estimateAcquisitionTime
2. acquire
3. estimate
4. _updateSEMSettings
**Simultaneously I am working on the following test cases which will be pushed later when completed.**
For AnchorDriftCorrector the function estimateAcquisitionTime is not tested. The functions with a * are used in the test case test_get_next_pixels, you have to verify whether they are only used in this test case or if their output is tested.
estimateAcquisitionTime
series_start*
series_complete*
start*
complete*
=> Add and verify test cases in drift_test.py and leech_test.py

src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py
SpectrumStreams are (now) misnamed as they support a lot of different
acquisition type. Including acquisitions without any spectrum. For
instance time-resolved (only) data is handled by the SpectrumStream too.
This confused the exported which cared about the spectrumBandwidth VA
(to update the metadata).
=> Don't use the type of the stream, and just explicitly check that the
VA is present.
=> gui util img: support SpectrumStreams without spectrum

src/odemis/driver/smaract.py, src/odemis/driver/test/smaract_test.py
The default behaviour of the SmarAct is to search for a reference mark in the positive direction, which is down (towards the sample). If the lens is in focus, this will reach very near the sample (there is a physical limit switch right before). It’s dangerous for the hardware.
=> change the referencing to start with negative direction.
Similarly to the tmcm.TMCLController, accept a (new) parameter param_file, which takes a filename as value. This file contains a list of parameters, their channel and their value.
The file extension should be .mcs2.tsv.  Similar format as for  the TMCM. Preferably, the values can be either decimal or hexadecimal (starts with 0x).
This file is read at init, and all the values are immediately set on the device. If setting some values fails, the initialisation …
=> Smaract driver parameter file update and testcases

src/odemis/driver/scanner.py, src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py, src/odemis/gui/conf/data.py, src/odemis/gui/cont/tabs.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1161
Unit tests results (ran locally):
- For [TestMicroscope](https://github.com/nandishjpatel/odemis/blob/c1fddc9b4308851f4faa2b10dbcbf096f9685988/src/odemis/driver/test/xt_client_test.py#L103), [TestMicroscopeInternal](https://github.com/nandishjpatel/odemis/blob/c1fddc9b4308851f4faa2b10dbcbf096f9685988/src/odemis/driver/test/xt_client_test.py#L596), [TestFIBScanner](https://github.com/nandishjpatel/odemis/blob/c1fddc9b4308851f4faa2b10dbcbf096f9685988/src/odemis/driver/test/xt_client_test.py#L1088), [TestDualModeMicroscope](https://github.com/nandishjpatel/odemis/blob/c1fddc9b4308851f4faa2b10dbcbf096f9685988/src/odemis/driver/test/xt_client_test.py#L1119) using [server_sim.py](https://bitbucket.org/delmic/xtlib-adapter/src/master/xtadapter …
=> Sdev 1161 rename xt client beamshift to shift

src/odemis/acq/test/stream_test.py
Updated the `util.test` as `util.testing` and used it as `testing.assert` instead of `test.assert` in the overlooked stream_test.py file.
=> Bugfix introduced in PR #2681

src/odemis/driver/test/tmcm_test.py, src/odemis/driver/tmcm.py
There were a couple of small issues when reading the version number:
* the IDENTITY was incorrectly clipped to 8 bits instead of 16 bits
* the SW_VERSION of the TMCM seems to contain NULL followed by garbage
(which is common on C code). => discard anything after the NULL
character to avoid confusing the output of swVersion.
=> driver tmcm: fix version number for CANopen device

src/odemis/driver/andorcam3.py, src/odemis/driver/xt_client.py
In two places the errors were raised with a comment like this raise Error("comment %s", value), however this is not the correct syntax for raising errors and will not put the value after the comment.
=> fix syntax errors in errors being raised in andorcam3 and xt_client

src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py
Whether the range is from 100 -> 1000 or 1000 -> 100, or -1000 -> -100,
the number of ticks and values should be the same (modulo the sign).
Also allow to have ticks near the border, as it's actually quite useful
when reading the graph, and now the code displaying the values do handle
properly the positioning of text next to the border.
=> gui util img: make calculate_ticks() symetrical

src/odemis/odemisd/start.py
If the backtrace is the last message, there is no message found to
indicate the end of the backtrace. => handle this speciall case.
Also reduce the number of maximum lines shown, to really fit a standard
screen.
=> odemisd start: handle log display when the backtrace is the last message

src/bugreporter/odemis_bugreporter.py
Until now, in case of error, we only showed a message saying "an error"
happened and explaining how to do a manual upload.
It's handy to also show a short summary of the error, so that if this
happens, we have some chance of understanding what went wrong (for
instance, no internet, API key not accepted, or weird character)
=> bugreporter: in case of error, show a summary of the error in the error message

src/odemis/acq/test/stream_test.py
One test case i.e  test_arpol_ss in [SWM-61](https://delmic.atlassian.net/browse/SWM-61?atlOrigin=eyJpIjoiMDliOTk1ZGU3OWZkNDRkNmE0OWIwZjc2NzY2YTZiN2YiLCJwIjoiaiJ9) fixed.
=> fix input arguments for stream_test.py::SPARC2PolAnalyzerTestCase::test_arpol_ss

src/odemis/gui/test/comp_text_test.py
On wxPython 4.0.7, the simulator seems to only work when it's run from
within Eclipse. From the terminal the tests always fail, because the
simulator doesn't actually do anything.
Should be working when switching to wxPython 4.1
=> gui test: skip tests using UIActionSimulator on wxPython 4.0.7

src/odemis/acq/align/delphi.py, src/odemis/acq/align/test/delphi_test.py
These testcases were failing in a Ubuntu 20.04 environment probably due to opencv/cv2 version difference.
Fixed the testcases by adding opencv version checks. For test_find_hole_center it was required to add a different outcome.
For test_find_lens_center only setting a cv2 version boolean upfront was enough.
=> fix failing find_hole_center and find_lens_center testcases for the Delphi

src/odemis/driver/test/picoquant_test.py
TestHH400_Shutters.test_shutters and TestPH300_Shutters.test_shutters were failing when running all the test cases in a class but not when runnning the test standalone. After unsubscribing in test_acquire_sub it takes a bit of time for the shutters to reset, therefore add a time.sleep at the end of that test case.
=> fix picoquant_test shutter test cases

src/odemis/acq/test/stream_test.py, src/odemis/model/_dataflow.py
Clean up according to new coding guidelines.
Fix reference being kept in logging call, ensuring the test case passes.
=> Stream test weak ref fix

src/odemis/gui/comp/legend.py
Following Deprecation Warnings Resolved ([SWM-70](https://delmic.atlassian.net/browse/SWM-70?atlOrigin=eyJpIjoiYWM0MzEzYmYxMTdmNDUzNzg0YTMzYTBhNDE1N2IwNTQiLCJwIjoiaiJ9)):
```
/home/testing/development/odemis/src/odemis/gui/comp/legend.py:457: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
self.lockBtn.SetPosition((self.ClientSize.x - self.ClientSize.x / 2 - 12, 0))
/home/testing/development/odemis/src/odemis/gui/comp/legend.py:539: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
self.SetMinSize((self._max_tick_width + 14, -1))
```
=> [SWM-70] convert float type to int in legend.py

src/odemis/gui/util/img.py, src/odemis/gui/util/test/img_test.py
fix bug introduced in 0df545dc (gui util img: make calculate_ticks()
symetrical).
Also add a test case to explicitly check for this corner case.
=> gui util img: fix calculate_ticks when passing empty client size

src/odemis/dataio/hdf5.py
Now that we don't support Python 2, we don't need to use these past
dependencies. This clarifies/simplifies a little bit the code.
=> dataio hdf5: remove "past" dependency

src/bugreporter/odemis_bugreporter.py, src/bugreporter/test/odemis_bugreporter_test.py
There is a new field on the tickets available in our osTicket database:
"installation". Let's make use of it. The hostname should normally
correspond to the installation name, so that's straightforward.
=> bugreporter: add hostname as installation name

debian/control, src/odemis/driver/test/xt_client_test.py, src/odemis/driver/xt_client.py
This PR should be reviewed together with 
- https://bitbucket.org/delmic/xtlib-adapter/pull-requests/70
- https://bitbucket.org/delmic/ubuntu-delmic/pull-requests/5
Flow (xtadapter release management):
- [xt_client line](https://github.com/nandishjpatel/odemis/blob/e864631d800198517d7aff99fc379242fbaeb095/src/odemis/driver/xt_client.py#L217): get the xtadapter version, type, bitness from the running application on Windows PC
- [xt_client line](https://github.com/nandishjpatel/odemis/blob/e864631d800198517d7aff99fc379242fbaeb095/src/odemis/driver/xt_client.py#L224): check if a newer package is available under `/usr/share/xtadapter` i.e. the directory where the zip files will be made available from the xtadapater debian package
- [xt_client …
=> Sdev 1181 implement updating xtadapter from ubuntu to windows

src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py, src/odemis/util/__init__.py, src/odemis/util/img.py, src/odemis/util/test/img_test.py, src/odemis/util/test/util_test.py
Add the functionality to be able to acquire non-rectangular or rotated rectangular regions of acquisition (ROA's). For now the previous method is still used for acquisition since the GUI still requires compatibility. Two utility functions were added for flood filling a ndarray, which is used for finding the inside of the polygonal ROA's and for finding the bounding box of a set of polygon coordinates.
=> Add fastem support for non-rectangular in the acquisition manager.

src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py
_get_intersected_field_indices() Assumes the y-axis as being positive in a downward direction. To convert this to the real world definition the acquired index array needs to be flipped over the x-axis.
=> Flip the y-axis to real world definition.

src/odemis/driver/orsay.py, src/odemis/driver/test/orsay_test.py, src/odemis/model/_vattributes.py, src/odemis/model/test/vattributes_test.py
This should mostly complete the support for imaging on the Orsay Physics FIB.
It also fixes a few other issues related to reliability found while testing the image acquisition. 
Now the Odemis GUI support playing the image, adjusting the acquisition setting, adjusting the focus.
There is still one bug in the FIB software which is not handle when changing the RoI up in Y. Still hoping that Orsay Physics can directly fix this issue instead of writing a workaround.
For the reviewers: I recommend checking commit per commit, as it might clarify the changes.
=> driver orsay: improve imaging reliability and more

src/odemis/odemisd/modelgen.py
The error messages for the !extend option should not mention !include.
=> odemisd modelgen: fix copy-paste error in error message

src/odemis/driver/test/cam_test_abs.py, src/odemis/driver/test/ueye_test.py, src/odemis/driver/ueye.py
The sensor of the uEye is sometimes too big compared to the image received. That means that on the border, there is no image. While on the live image it’s not a big issue, for tiling, it causes black line between each tile. 
To avoid this, we should have a way to crop the image. Probably the best is to use the same as for the andorcam3 (Zyla): add a max_res parameter to the component that restrict the maximum resolution reported by the driver. It’s always centered.
=> Extend ueye.Camera to support max_res (int, int).
This can be done by using the is_AOI() function.
See specification here: Technology Development/Software/Odemis/Specification uEye max_res argument.docx
https://docs.google.com/document/d/1iTjxhw3LBRfkOiASk4N_D_p9gXiU_BSG/edit?pli=1
=> Driver ueye crop image data

.gitignore, src/odemis/util/img.py, src/odemis/util/test/img_test.py
The following functions in odemis.util.img.py do not have a test case yet. Try to think of a simple test case for each one of them and add them to odemis/util/test/test_image.py. Note that there is also the module odemis.gui.util.img.py , this task is only about odemis.util.img.py.
tint_to_md_format
md_format_to_tint
getOutliers
guessDRange
getColorbar
tintToColormap
getYXFromZYX
ensure2DImage
Subtract
mergeMetadata
getTilesSize
getCenterOfTiles
getBoundingBox
assembleZCube
=> Addition of testcases for img.py for all methods which did not yet have testcases

src/odemis/model/_core.py, src/odemis/model/test/remote_test.py
fixed 5 failing test cases under `class ProxyOfProxyTest(unittest.TestCase):`
set the `BASE_DIRECTORY` using `tempfile.gettempdir()` to ensure the folder exist on both windows and linux operating systems.
=> fix failing test cases

src/odemis/gui/test/comp_legend_test.py
The test fails on the test VM, but passes on a standard computer.
It might be because it's too CPU intensive, and hence reaches the
30 s timeout (while typically it takes ~10s).
=> Update only 200/s instead of 2000s.
Also, in case of failure in the thread, log it, so that we know
more easily what's the issue.
=> gui comp legend test: make the test less CPU intensive

src/odemis/gui/test/__init__.py
Each test case class creates its own app. Sometimes that seems to cause
segfaults at the end of the test cases.
Explicitly deleting the App, to force some clean-ups early fixes the
issue.
=> gui test: avoid segfaults if multiple test app created in a row

src/odemis/gui/cont/project.py
When selecting and deselecting a region of calibration the coordinates of active but deselected scintillators can update unexpectedly. When the coordinates change all active scintllators are checked and re-drawn based on the coordinates. Because the coordinates had updated even the deselected boxes would be re-drawn. This fix makes sure that boxes are only drawn based on whether the calibration region box has been selected or de-selected.
=> SDEV-1247 fix calibration region overlay appearing when the button was deselected

src/odemis/model/_core.py, src/odemis/model/test/remote_test.py, src/odemis/util/test/testing_test.py, src/odemis/util/test/util_test.py, src/odemis/util/testing.py
Commit 6064bb32afe (model: if base directory is not available use a
temporary one) changed the way BASE_DIRECTORY is set.
This introduced two issues:
* As soon as odemis.model is imported, code is run, which is not a good behaviour.
In particular, it would call logging, possibly very early at startup,
which causes some odd logging configuration (everything is displayed in
the terminal).
* The standard BASE_DIRECTORY (/var/run/odemisd) *never* exists when
starting the backend. So it would always create a temporary directory.
Normally, create that directory is handled by the backend.
=> Remove the smartness of the BASE_DIRECTORY constant.
The backend takes care of creating that directory.
=> Create a new function testing.use_fake_backend_directory() for the
cases where we need a fake base …
=> model: do not automatically fallback to a different BASE_DIRECTORY

src/odemis/driver/smaract.py, src/odemis/driver/test/smaract_test.py
There are other ways to rename the axes, especially by using the
MutliplexActuator. However, this doesn't support the MD_PIVOT_POS.
=> Directly support renaming the axes to whichever name.
This also keeps the microscope files simpler.
=> driver smaract SmarPod: add option to rename the axes

src/odemis/acq/align/spot.py
Returned translation value was the initial estimation, not the refined value.
=> Bugfix in odemis.acq.align.FindGridSpots

src/odemis/driver/orsay.py, src/odemis/driver/test/orsay_test.py
The probe current cannot be changed directly. Instead, this is done by
loading a specific preset. To know what preset corresponds to which
probe current, we rely on a name following a specific template.
=> driver orsay: support changing the probeCurrent

src/odemis/gui/util/test/updater_test.py
The real Odemis App has a ._is_standalone attribute, so let's imitate
that.
It didn't matter much, as it'd automatically fallback to doing the
"standard" thing (ie, not Delphi), but it's nice to not see that error
in the test logs.
=> gui util updater test: avoid warning about missing _is_standalone

install/linux/usr/share/odemis/sim/mimas-orsay-sim.odm.yaml, src/odemis/acq/move.py, src/odemis/acq/path.py, src/odemis/acq/test/move_test.py, src/odemis/acq/test/path_test.py, src/odemis/driver/actuator.py, src/odemis/driver/smaract.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/model/__init__.py, src/odemis/util/__init__.py, src/odemis/util/test/util_test.py
Add the 4 defined positions in MIMAS to the acq.move module, similarly to ENZEL and METEOR.
Then also add support for the OPM to switch automatically between FM and FIB based on the streams.
We also introduce a fix for the SmarPod simulator, and add a new MIMAS simulator using the Orsay simulator.
=> Add support for moving to defined position in MIMAS, including the optical path manager

src/odemis/acq/orsay_milling.py, src/odemis/acq/test/orsay_milling_test.py
MillingActivationState sometimes goes at init to 1, then 0, and then
back to 1. Finally, at the end it becomes 0 again.
That meant that sometimes the detection of the end would be triggered
just before the actual acquisition.
=> Use .Target (as recommanded by Orsay Physics) and CurrentMillingPoint
to be really certain the milling is stated & finished.
Also generalise the parameter logger.
=> acq orsay_milling: detect better end of milling

src/odemis/acq/test/orsay_milling_test.py
Quick fix of the failing test case due to incorrect setting of TEST_NOHW default value.
=> fix TEST_NOHW default value

src/odemis/driver/test/zeiss_test.py, src/odemis/driver/zeiss.py
Added some small changes to the test cases for the 6-axes movement testing of the stage. Notably adding a starting position to return to later and changed moves to under- and overflow moves for Rm. Also renamed axis Rz to Rm and added a small correction in relative move regarding under- and overflow.
=> Added some small changes to the testcases for Zeiss driver for 6-axes movement

src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py
It used the ENZEL icon instead of the simple optical icon.
=> gui xrc: fix MIMAS optical grey icon

src/odemis/gui/comp/overlay/world.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/cont/tabs.py, src/odemis/gui/main.py, src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py, src/odemis/gui/model/__init__.py, src/odemis/gui/test/comp_overlay_test.py
Shows the (theoretical) position of the samples based on the YAML
metadata into the view, as blue wireframe.
It could almost work for METEOR, but the metadata is in the SEM stage
(stage-bare) referential, while we need to have it in the FM referential
(stage).
=> gui comp: add SampleBackgroundOverlay for MIMAS

src/odemis/util/comp.py, src/odemis/util/test/comp_test.py
MD_POS_ACTIVE_RANGE is a dict of the format axis -> tuple. However, the
code assumed that it would just be a tuple.
=> Look explicitly for the "z" axis.
=> util comp: fix use of MD_POS_ACTIVE_RANGE in generate_zlevels()

src/odemis/acq/millmng.py
The milling is cut in N passes. For each pass, the milling would mill
for N * duration. It should be just 1 * duration.
=> acq millmng: fix milling with drift correction milling too long

src/bugreporter/odemis_bugreporter.py
We upload JSON data, so it should be marked as JSON. Typically, the
content-type doesn't matter. At least osTicket doesn't care.
However, the HTTP server has new security rules that check that content,
and automatically rejected POST requests which, by default, reported
x-www-form-urlencoded.
So this fixes the issue that some users are facing when reporting a bug
and it indicates Error 400.
=> bugreporter: set POST request content-type as JSON

src/odemis/gui/comp/overlay/base.py, src/odemis/gui/comp/overlay/world.py
Fixed an NoneType error in src > odemis > gui > comp > overlay > base.py and world.py. If both of the values returned by get_width and get_height is None the max() method in stop_selection will raise a NoneType error.
Now an int() conversion is applied with a default int value of 0.
=> Fixed a NoneType error in overlay selection base.py and world.py

src/odemis/driver/orsay.py, src/odemis/driver/test/orsay_test.py
Simplifies the code by relying on the generic class.
No behaviour change.
=> driver orsay: use more OrsayParameterConnectors

src/odemis/util/graph.py, src/odemis/util/registration.py, src/odemis/util/test/graph_test.py, src/odemis/util/test/registration_test.py
`estimate_grid_orientation` and `estimate_grid_orientation_from_img` no longer raise an IndexError when providing (an image of) a single point as input
=> Bugfix of estimate_grid_orientation

src/odemis/acq/fastem.py
The stage precision was set to 1e-6 for tiles of 1024 px in width this resulted in less than 1px overlap. The stage currently seems to have a much lower precision, therefore the stage precision has been increased to 29e-6 which corresponds to ~20px overlap.
=> fastem overview acquisition: increase the overlap between tiles

src/odemis/driver/lakeshore.py
Updated the minimum temperature in the range of target temperature to avoid errors. The target temperature is set to 0 Kelvin(-273.15 Celsius) by Lakeshore temperature controller when the output is not defined and our previous range was -273 Celsius.
=> hotfix-lakeshore-driver-target-temperature

src/odemis/acq/stitching/test/tiledacq_test.py
Fix for the failing test case tiledacq_test.py::CRYOSECOMTestCase::test_refocus
=> fix test_refocus

src/odemis/util/test/img_test.py
fixed TestGetColorBar.test_get_colorbar in src>odemis>util>test>img_test.py
this method was failing when running test cases in an Ubuntu18 environment
=> cm.get_colormap('cividis') changed to cm.get_colormap('autumn')
=> fixed TestGetColorBar.test_get_colorbar test case in img_test for ubuntu18 compatibility

src/odemis/driver/smaract.py
It's not very realistic that after referencing the position is the same.
=> Go to some arbitrary position. That makes it easier to see in the GUI
if after the referencing some axes are left as-is.
=> driver smaract SmarPod: simulator should explicitly go to different position after referencing

src/odemis/driver/orsay.py, src/odemis/driver/test/orsay_test.py
This is a temporary work-around while the Orsay Server adjusts its
access rights code. By default the connection runs as "Python", at the
lowest level, which forbid reading/modifying presets.
=> driver orsay: connect using "admin" level to access all the presets

doc/develop/plugins.rst
The part of the plugin loaded when Odemis starts was not aligned with the SPARCv2 manual. Now these are more or less similar.
=> small change to the plugins section of the odemis developer manual

src/odemis/gui/conf/data.py, src/odemis/gui/cont/fastem_acq.py, src/odemis/gui/cont/tabs.py
Ticket: https://delmic.atlassian.net/browse/SDEV-1457
Changes:
- Have the Contrast slider above the Brightness slider (same setup as the TFS UI)
- Either display, “System not calibrated, please run Optical Autofocus“ or remove this warning and allow the user to acquire Overview Image without running Optical Autofocus
- Handle disabling of calibration buttons when necessary. Disable the calibration buttons when acquiring Overview Image, and when running each calibration disable the other calibration buttons
=> Sdev 1457 implement overview tab changes based on feedback after testing on ea1

src/odemis/gui/cont/tabs.py
SDEV-1460 Execute the image rotation pre-alignment before the scan rotation and scan amplitude pre-alignments. The latter two calibrations only work if the pattern is roughly aligned with the diagnostic camera x-axis (+/- 5 degrees). The image rotation pre-alignment is independent of the scan rotation pre-alignment, the descan gain alignment and the scan amplitude alignment, therefore it can be moved in front of those three.
=> fastem: change order of calibration 1

src/odemis/driver/tmcm.py
This was suggested in the warning msg in src/odemis/driver/tmcm.py.
`/home/testing/development/odemis/src/odemis/driver/tmcm.py:2392: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.`
=> fixed a DeprecationWarning: tostring() and changed it to tobytes()

src/odemis/gui/util/widgets.py
src/odemis/gui/test/util_widgets_test.py::ConnectorTestCase::test_pf_connector
2023-06-15T23:21:26.0013799Z   /home/testing/development/odemis/src/odemis/gui/util/widgets.py:365: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
=> explicitly find an int value

install/linux/usr/share/odemis/sim/mimas-sim.odm.yaml, src/odemis/acq/test/move_test.py
We changed the behaviour of COATING, which now just engages the GIS arm.
However, the test was left as-is.
=> Remove the "COATING" position from the microscope file, and just
check that moving to COATING engages the GIS.
=> acq test move: fix mimas move to coating failure

src/odemis/gui/test/comp_viewport_test.py
The test machine has a small virtual monitor, therefore increasing size of the window by a factor 2 automatically decreased the window again because it did not fit the monitor size. This fix uses 1.5 as a scaling factor so that the inceased window size fits the monitor.
=> Fix test_resize

src/odemis/acq/align/keypoint.py
Changed this user warning to a FIXME so we dont get a warning message in the report of the test cases:
`/home/testing/development/odemis/src/odemis/acq/align/keypoint.py:64: UserWarning: Please be aware that the FindTransform function does not work reliably at the moment `
=> Changed the UserWarning to a FIXME in the FindTransform method.

src/odemis/gui/test/comp_overlay_test.py
The test case was failing because the gui was not refreshed after drawing the features, so the buffer did not contain the added features.
=> Fix cryo_feature_overlay test case

util/pituner
Needed to work with the latest C885 controller, which now uses master = 1.
Also fix an issue in Python 3.
=> util pituner: add master option

src/odemis/acq/test/stream_test.py
The live updater period has been increased from 0.5s to 2s. The test
case relied the fact that after receiving one live image, it would
update at least one more time. That meant the acquisition needed to last
at the very list 3s.
=> Make the acquisition a little longer (now 6s)
Also explicitly check the acquisition is still going on before acquiring
the images, to detect such error more easily.
Also convert the test case to the new style of starting the backend,
avoind to stop it after finishing the test cases. Easier for debugging.
=> acq stream test: fix SPARC2StreakCameraTestCase.test_streak_acq_live_update

src/odemis/gui/win/acquisition.py
Commit ca419d9a changed the overview imaging interface if multiple grids were available. To do this it added an attribute self._grids if multiple grids were avalable. This attribute was always called at the start and at the beginning of an overview image, causing the overview imaging to fail on the Meteor (see: [jira](https://delmic.atlassian.net/browse/SDEV-1325?focusedCommentId=15488)). With the error:
```
2023-06-28 10:45:11,426 ERROR   main:414:       Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/wx/core.py", line 3285, in <lambda>
lambda event: event.callable(*event.args, **event.kw) )
File "/home/pals/development/odemis/src/odemis/gui/win/acquisition.py", line 1295, in on_acquisition_done
self._resume_settings()
File …
```
=> [FIX] Meteor overview imaging failed to start

src/odemis/util/linalg.py
6Z /home/testing/.local/lib/python3.8/site-packages/numpy/core/function_base.py:120: in linspace num = operator.index(num) TypeError: 'numpy.float64' object cannot be interpreted as an integer
=> [fix] Convert float to int type in numpy.linspace

src/odemis/driver/tescan.py, src/odemis/driver/test/tescan_test.py
Since we do not yet support installing a METEOR on a TECAN SEM it is necessary to adjust the current driver to be able to handle controlled stage rotation to be able to align METEOR and the CCD properly.
Right now there is no support for axis other than for linear axis therefore the existing driver should be extended. The addition to the existing driver is only support for moving with the rotational axes.
Basic requirements are that the user will be able to control the stage through Odemis for moving all possible axes installed.
In addition test cases are written to test the  added functionality with moving the 2 newly added axes rx and rz.
=> Extend the TESCAN driver to support rotational axes

src/odemis/acq/test/move_test.py
Running /home/testing/development/odemis/src/odemis/acq/test/move_test.py:
FAILED move_test.py::TestMimasMove::test_cancel_loading - AssertionError: 0 == 0
=> [fix] Error in move_test.py

install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml
[config] correct the miny, maxy of POS_ACTIVE_RANGE's y; y  values of SAMPLE_CENTERS; miny and maxy values of SAMPLE_BACKGROUND as per the latest CAD drawing
=> [SDEV-1553] move scintillator parameters from source code to microscope yaml file 1

src/odemis/driver/test/tescan_test.py
fixed an import of output_window.py which did not exist in addition and re-organized the lines of import code according to our standards.
=> [FIX] Invalid import in tescan_test.py

plugins/spike_remove.py
Fix the assertion error that is raised when the provided image squeezed down to less than 3 dimensions.
**The error:**
```
File "/home/USER/.local/share/odemis/plugins/spike_remove.py", line 225, in removespikes_spec
assert specdat.ndim == 3
AssertionError
```
Related Jira issue: [[CSDM-1008](https://delmic.atlassian.net/browse/CSDM-1008)]
[CSDM-1008]: https://delmic.atlassian.net/browse/CSDM-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [fix] spike removal tool

src/odemis/acq/move.py
The rotational axes are updated when target is moved using GRID 1 and GRID 2.
With the old workflow. when the stage is moved from Loading to GRID 1 position (default SEM mode), then the resultant stage position will not be updated in rx and rz but only in x, y, z. The current changes, update rx and rz.
=> [fix] add rotational axes for Thermofisher when switching using grid mode 

src/odemis/util/conversion.py
Test case test_tint_to_colormap_unexpected_input in /util/test/img_test.py was failing on Ubuntu 18.04. 
The expected ValueError was not raised in this case.
On Ubuntu 18.04 RGB values in tuples higher than 255 are somehow accepted or forced in between the range of 0-255.
The root of this reason is not easily traced as the code is distributed over multple .py files and/or classes.
To make sure the ValueError exception is raised a check is added to /util/conversion.py rgb_to_frgb method to make 
sure all the values in the tuple are within the range of 0-255.
=> [SWM-129] Fix img_test.py/test_tint_to_colormap_unexpected_input

src/odemis/driver/xt_client.py
[fix] additional scanner VA values to be set for configuring scanner can now be passed as kwargs
Having the option to pass kwargs, the dwellTime VA value can be correctly set for OVERVIEW_MODE after the external VA is set
=> [SDEV-1518] dwell time slider does not work for overview imaging - UMCG

src/odemis/dataio/hdf5.py, src/odemis/dataio/test/hdf5_test.py
Sometimes when reading strings from hdf5 files bytes are returned instead of a string. This fix ensures that if bytes are returned they are always converted. The code has been refactored to move the function read_str out of the for-loop it was in and to it's own function.
On Ubuntu 22.04 the following test case failed:
FAIL: testMetadata (hdf5_test.TestHDF5IO)
checks that the metadata is saved with every picture ---------------------------------------------------------------------- Traceback (most recent call last):
File "/home/runner/work/odemis/odemis/src/odemis/dataio/test/hdf5_test.py", line 423, in testMetadata
self.assertEqual(metadata[model.MD_DESCRIPTION], desc)
AssertionError: 'tÉst' != b't\xc3\x89st'
=> [fix] hdf5: decode all strings from hdf5 files when they are bytes

src/odemis/acq/stream/_static.py
Currently only StaticCLStream supported the read-only emission field which show the band wavelength used in the analysis. When analyzing AR in the analysis tab the user would find the right MD under the button metadata. Therefore  the StaticARStream emission metadata is now updated to show as a RO VA on the stream panel.
=> [CDSM-1094] updated the StaticARStream to contain emission metadata

src/odemis/acq/fastem.py
TypeError: __init__() missing 1 required positional argument: 'colour'
=> [fix] rasied TypeError by passing default colour value during FastEMROC class init

src/odemis/gui/win/acquisition.py
Increase the overlap from 5 to 10 percent during tiled acquisition to hide rectangular gap between stitched tiles.
=> [METEOR-798] [fix] Hide black rectangles in overview acquisition 

src/odemis/gui/test/log_test.py
The following warning was raised in the test cases because the test used logging.warn. 
```
2023-10-26T13:31:28.6860663Z src/odemis/gui/test/log_test.py::TestLogWindow::test_log_window
2023-10-26T13:31:28.6861263Z   /home/testing/development/odemis/src/odemis/gui/test/log_test.py:48: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
2023-10-26T13:31:28.6861389Z     random.choice(LOG_FUNCTIONS)("WEEEEEE %d" % i)
```
=> [SWM-136] fix: log_test fixed to use logging.warning instead of logging.warn

src/odemis/gui/cont/tabs.py, src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py
Hide hardware settings in the Localization tab when viewing a static stream and show in live stream
=> [METEOR-520] [fix] Hide hardware settings in the Localization tab when viewing a static stream 

src/odemis/acq/test/fastem_test.py
The stage was not mocked because it previously was not called in the test cases. Commit a1baa166 added the use of guessActuatorMoveDuration to estimate the duration of a move. This checks if the stage object is an actuator. Since it was not mocked at all and it was just None, the following error was raised: ValueError: The component None should be an actuator, but it is not. Now the stage is also mocked and the check if it is an actuator passes.
=> [fix] Mock the stage in the fastem mocked test cases.

src/odemis/acq/fastem.py, src/odemis/driver/technolution.py
raise a ValueError when the overlap results in an effective field size of 6400. The default overlap has been updated to be 6%, this is currently used on all systems so is a reasonable default.
=> [fix] technolution driver does not support an overlap of 0%

src/odemis/driver/xt_client.py
In commit c4b4f0723949748a71f6675b8703405fb3017acc initialization errors in the xtclient were adjusted to report them with more precision. However the OSError was except as `except OSError:` not `except OSError as err`, since `err` was not assigned this caused a problem when an OSError was raised.
=> [fix] xtclient correctly raise hardware error with message

scripts/odemis-start-turret.py
Useful to workaround if a spectrograph fails to read the turret ID.
Note that shrkconfig --turret alsmost does the same thing, but it's not
able to turn on the spectrograph in a SPARCv2. This script does that
trick too.
=> [feature] add odemis-start-turret to automatically turn on and change turret of a spectrograph

.github/workflows/unit_tests_cloud.yml, src/odemis/acq/test/fastem_test.py
[fix] fastem test cases fixed after being broken due to overlap and scan-stage updates
Commit 0c32be368bd491b416d5973abefba227b62367da fixed that the overlap is not allowed to be zero in the technolution API. The commit also updated the default value of the overlap to be 0.06 instead of 0.0. The test cases were written for an overlap of 0.0 and failed because of this.
Commit 9f40d9af143c305871a172ee0ff5581ffa397836 added the scan-stage as an input argument for the acquire function and the AcquisitionTask, but the test cases that called these functions were not updated.
Because of these commits the test cases were failing, this has now been fixed by using an overlap of 0.06 in the test cases and using the scan-stage.
[add] fastem test case for expected stage location with rotation …
=> [SDEV-1356] fix fastem test cases

install/linux/usr/share/odemis/sim/sparc2-streakcam-sim.odm.yaml, src/odemis/acq/stream/__init__.py, src/odemis/acq/stream/_helper.py, src/odemis/acq/test/stream_test.py, src/odemis/gui/comp/stream.py, src/odemis/gui/cont/streams.py
add test cases with SE, CL and EBIC acquisitions
validate to have SE, CL and EBIC acquisitions simultaneously
remove unnecessary `children` from sparc2 streak cam sim microscope file
=> [TRCL-10] validate SE, CL and EBIC simultaneous acquisition

src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py
Renames references to FEI to ThermoFIsher (TFS) in the metadata parser for consistency with other code. 
Refactors camelCase to lower_case for consistency with other metadata parsers
=> [REFACTOR] Rename FEI to ThermoFisher (TFS) and change to lower_case for consistency. 

src/odemis/gui/cont/streams.py
broken by commit 5420cab9e Show relevant static streams in stream panel based on the view selected by the user in the Localisation Tab
=> [fix] add stream button works again on Meteor

src/odemis/acq/path.py, src/odemis/gui/test/comp_overlay_test.py
https://github.com/delmic/odemis/pull/2589 adds a pipeline for checking syntax errors, this commit fixes the errors related to old style classes.
=> [fix] remove use of parenthesis in class definitions that do not use inheritance.

src/odemis/gui/model/__init__.py
The scan amplitude calibrations where disabled, because they gave strange values every now and then. We have now monitored the calibrations for over 2 months and it has been consistend over that period. This commit removes the scan amplitude pre-alignment from Calibration set 1 and the user will need to run this calibration every month.
=> [fix] fastem remove scan amplitude pre-align from calib 1

src/odemis/gui/cont/tabs.py, src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py
Add a tooltip to the button use current z
=> [fix][METEOR-521] disable the "use current z" button if live view is not selected

src/bugreporter/odemis_bugreporter.py
The fastem calibrations image, specifically the cell translation plot, gives information about the quality of the multiprobe pattern. It is added to help with a quicker first diagnosis of problems.
=> [SDEV-1745] feat: add fastem calibrations image to odemis bug reporter

src/odemis/driver/test/smaract_test.py
core is no longer used, instead si is used which is the fake or actual smaract.si module
=> [fix] failing smaract testpicoscale test position testcase

src/odemis/acq/stream/_live.py
power slider updates its range even when the stream is paused and shows the correct power range for the selected excitation.
=> [fix] [METEOR-848] update the power slider range when excitation is changes

src/odemis/driver/test/actuator_test.py
[fix] core is no longer used for Picoscale sensor, instead si is used  which is the fake or actual smaract.si module
=> [fix] failing test dual channel position sensor testcases

src/odemis/acq/stitching/_registrar.py, src/odemis/acq/stitching/test/registrar_test.py
[fix] ShiftRegistrar._compute_registration a position in pixels was compared to a position in meters
[refactor] Renaming of registered_positions to registered_positions_m and addition of registered_positions_px
[refactor] Let GlobalShiftRegistrar inherit from the ShiftRegistrar class.
[fix] shift registrar synthetic test case
=> [SDEV-1692] Fix and refactor registrar classes

src/odemis/acq/fastem.py, src/odemis/util/registration.py
[fix] catch the raised ValueError when setting beamshift VA value goes out of range and instead log the error for now
By doing so the ROAs acquisition can still continue
=> [SDEV-1767] disable failure of roa acquisition when beamshift correction fails

src/odemis/acq/acqmng.py, src/odemis/acq/stream/_helper.py, src/odemis/acq/test/acq_test.py, src/odemis/gui/cont/acquisition.py, src/odemis/gui/main.xrc, src/odemis/gui/main_xrc.py
Add folding of the CL intensity and EBIC streams for SPARC if the dwell time, repetition, roi values are the same and the detectors are different
Add an info text on the GUI as well that lets the user know the acquisitions will be folded(merged)
Add test cases with different dwell time, repetition, roi combinations for the folding
Lastly, fix small PEP-8 incompatibilities
=> [TRCL-55] add folding of the streams

src/odemis/gui/cont/tabs.py
Revert type annotations to use typing module instead of type
```
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/pals/development/odemis/src/odemis/gui/main.py", line 40, in <module>
import odemis.gui.cont.tabs as tabs
File "/home/pals/development/odemis/src/odemis/gui/cont/tabs.py", line 1766, in <module>
class CorrelationTab(Tab):
File "/home/pals/development/odemis/src/odemis/gui/cont/tabs.py", line 1885, in CorrelationTab
def load_tileset(self, filenames: list[str], extend: bool = False) -> None:
TypeError: 'type' object is not subscriptable
```
=> Fix type annotations for python 3.8

src/odemis/acq/align/test/fastem_test.py
Skip the test case because, in the latest technolution asm simulator the simulated images have changed and the dark gain test case fails.
=> [fix] skip test_image_dark_gain because it fails for the latest TNL simulator

install/linux/usr/share/odemis/sim/sparc2-4spec-sim.odm.yaml, src/odemis/acq/test/stream_test.py, src/odemis/util/testing.py
Addition of a fake scan-stage test case in stream_test as a separate class. Consists of testing of the wrapper through a big configuration file containing the new wrapper actuator type. In addition contains a method to test for ccd-type detector only. Also made the roi_to_phys method a global one to use for other test cases.
=> [NSRPARMA-16] Add test case for scan-stage actuator wrapper

src/odemis/dataio/test/generate_test_metadata.py, src/odemis/dataio/test/multi_tiff_test.py
This pull request adds:
- A writer for writing image metadata to test case format.
- A test case for testing the parsers for multiple manufacturers on multiple images
=> [METEOR-881] Add test case for multiple images from multiple manufacturers

scripts/meteor-recalibrate-movement.py, src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/util/driver.py
Adds support for stage movement between SEM and METEOR without rotation for Thermo FIsher systems. 
**Implementation**
- Check if the current and target rotation (rz) are close to each other (~2.5  deg  tolerance)
- If they are close, move with translation only.
- If they are not close, move with previous rotation based movement. 
**Adds**
- Checks for required transformation to use
- Implementation of no rotation move
- Calibration script for manually adjusting the calibration data while odemis is running.
=> [METEOR-880] Add support for stage movement with no rotation

scripts/analyse-timelapse-secom.py, src/odemis/acq/align/autofocus.py, src/odemis/acq/align/test/autofocus_test.py, src/odemis/acq/stitching/_tiledacq.py, src/odemis/util/focus.py
to avoid circular import
MeasureSpotsFocus will need to be re-used in the fastem-calibrations code, but because that gets imported in odemis/acq/align/fastem.py it is causing a circular import. Since the functions are more utility functions of the autofocus code, I moved them to odemis/util/focus.py
relates to: https://bitbucket.org/delmic/fastem-calibrations/pull-requests/143
=> [SDEV-1770] refactor: Move focus metrics from acq/align/autofocus.py 

src/odemis/gui/cont/features.py
Currently, users can press the go to feature button while under the SEM and odemis will move directly to the stage + objective position without any safety controls or checks which are implemented as part of the CryoSwitchPosition method. We should prevent this, until we explicitly support moving to the feature under the SEM
=> [FIX][METEOR-933] Prevent move to feature while under SEM

src/odemis/acq/align/fastem.py, src/odemis/driver/xt_client.py, src/odemis/gui/conf/file.py, src/odemis/gui/cont/acquisition/fastem_acq.py
New autostigmation functionality is available and has been added to the xt_client. The new autostigmation should run during the pre_calibrations of an ROA and run every n sections. The frequency with which to run the autostigmation can be set through the acquisition config.
=> [SDEV-1770] feat: Add new autostigmation to precalibrations and xt_client

plugins/spectrum_arbscor.py
Allow to acquire a spectrum acquisition where the beam doesn't scan in
the standard order (ie, fast X, then slow Y). The plugin scans by
default along a checkboard pattern, but the idea is that the user can
change the patter to his/her liking by adding a different function.
=> [feature] new plugin for SPARC spectrum acquisition with arbitrary scan order

src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/cont/project.py
For idx 0 even if the autostig period was set to 0 it would still run the extended pre-calibrations. Additionally it should not run for idx 0, only for subsequent indices.
=> [fix] autostig period for idx 0 behaved incorrectly

src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_correlation.xrc
Based on user feedback increase limits for pixel size scaling in the correlation tab.
=> [fix] increase pixel scaling step size limits in correlation tab

src/odemis/gui/cont/correlation.py
Correctly disable the arrow key based correlation shortcuts when flag is toggled. Previously did not disable, and caused repeated calls to canvas callback. Now keyboard events are passed through (skipped).
=> [fix] correlation tab should passthrough arrow controls when correlation enabled is unchecked

src/odemis/dataio/tiff.py
Specific TFS SEM images were failing to parse correctly due the duplicate metadata keys in the metadata (e..g MultiGISGas parameters). These keys are not used by odemis, and can be discarded, but we need to disable strict parsing mode to do so.
=> [fix] allow duplicate metadata keys in tfs metadata

.github/workflows/self_hosted_runner.yml
Due to the removal of the HDMI dongle from the server it is not needed to pass this environment variable to VBoxManage anymore.
This is currently causing this issue:
Qt WARNING: could not connect to display :0
Qt FATAL: This application failed to start because no Qt platform plugin
could be initialized. Reinstalling the application may fix this problem.
=> [fix] self_hosted_runner.yml remove display env variable

src/odemis/dataio/tiff.py
Users reporting all images are flipped 180 degrees. This is due to scan rotation metadata being inconsistent with idemis display. 
This PR disables (set to zero) scan rotation metadata to make displayed odemis images consistent with acquired images.
=> [fix] disable scan rotation metadata for tfs

.github/workflows/self_hosted_runner.yml
The name still revered Ubuntu 18 and 20, while we are now also testing Ubuntu 22. Remove the reference to Ubuntu versions, so we also do not forget to update the name at a later stage.
=> [ci] Update name of self hosted runner

src/odemis/acq/fastem.py, src/odemis/acq/fastem_conf.py
Now that we are not running the scan amplitude pre-alignment in calibration 1, but have moved it to monthly maintenance, the calibrated value is not automatically set on the VA. This PR ensures that we are running the acquisition with the calibrated scan offset and amplitude.
@nandishjpatel I'm not sure if this is the best way to fix this, maybe we should rethink how to store calibrated values, now that we want to move some stuff to monthly maintenance.
=> [SDEV-1807] configure multibeam

src/odemis/gui/cont/correlation.py
The displayed stream in the movable combobox was not correctly 'selected' automatically. This PR fixes the automatic selection by forcing the event
=> [fix] automatically select movable stream on load images

install/linux/usr/share/odemis/sim/sparc2-4spec-sim.odm.yaml, src/odemis/acq/stream/_sync.py, src/odemis/acq/test/stream_test.py, src/odemis/driver/simsem.py, src/odemis/gui/cont/tabs/sparc_acquisition_tab.py
After recent testing of the stage scanning feature on a real SEM with a stage scan wrapper it turned out a few fixes were needed:
- there needed to be made a few distinctions for automatic moving conditions of the stage, in general with a real stage we do not want to move when starting Odemis or to go back to the center position.
- correction for stage shift when acquiring
- added shift stage translation fake data to simsem detector class
=> [FIX] PARMA stage scanning fixes

src/odemis/model/_metadata.py
This pull request extends the existing metadata to represent the full state of a fibsem system. This should allow decoupling of different metadata components, and separate the system metadata from the metadata used for display (e.g. MD_POS vs MD_STAGE_POSITION). All metadata represents the state of the system that was used to acquire the image.
- MD_STAGE_POSITION: The standard 5 dimensional stage position (x, y, z, r, t)
- MD_STAGE_POSITION_EXT: Extended stage position metadata for representing additional axes (e.g. zeiss m, alpha/beta tilt stages)
- MD_STAGE_PRE_TILT: The pre-tilt of the stage / shuttle used. 
- MD_BEAM_SCAN_ROTATION: the scan rotation of the beam
- MD_BEAM_STIGMATOR: the stigmator values of the beam
- MD_BEAM_SHIFT: the beam shift values of the beam
- …
=> [feat] extend metadata for fibsem specific parameters

src/odemis/acq/stream_settings.py, src/odemis/acq/test/stream_settings_test.py, src/odemis/gui/cont/stream_bar.py, src/odemis/gui/cont/tabs/localization_tab.py
Display most recently used settings (MRU) in the combo box of add stream button in the localisation tab.
Things left to do:-
1. **Add the tint settings** - It is a bit tricky to add tint. When it is in tuple format of 3 floats, it is easy to save it. But, when the tint value is of type LinearSegmentedColormap which is a custom color map, I am still exploring how to save such a type and read it. - **DONE**
2. **Test cases for the gui** - the testing for the full process i.e. save the setting of the stream controller and reading to checking the values in the json file and also vice-versa i.e. check the values of the recently used setting with the settings displayed in the gui. For both the workflows, I am not sure if it can be tested in the unit testing. 
3. **Review of Specifications …
=> [METEOR-589][feature] display the most recently used settings of stream panels 

src/odemis/dataio/hdf5.py, src/odemis/util/spectrum.py
It's not possible to remove metadata from the component. So if there is
no MD_WL_LIST, the best we can do is to make it None or a empty list.
So don't try to save the MD_WL_LIST if it's empty (ex, for AR data), and
so don't warn that it's not possible to store it.
=> [fix] dataio hdf5: don't warn it's not possible to save MD_WL_LIST if it's empty

src/odemis/acq/align/fastem.py, src/odemis/acq/align/test/fastem_test.py, src/odemis/gui/conf/file.py, src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/cont/tabs/fastem_overview_tab.py
SEM autofocus has been added to fastem-calibrations and is now integrated in the pre-calibrations.
* A constant has been added to define how often to run SEM autofocusing (every n ROAs).
* The SEM autofocus button in the GUI now points to the new autofocusing ** For SEM autofocus and autocontrastbrightness also disable the button of the autofunction that is running, as these cannot be cancelled
=> [feat] integrate SEM autofocusing in the pre-calibrations

src/odemis/gui/comp/stream_panel.py
When switching to a different tint colormap after having acquired an overview a C/C++ runtime error is generated referring to wrapped object:
File "/usr/lib/python3/dist-packages/odemis/gui/comp/stream_panel.py", line 422, in _on_colormap_value
self.combo_colormap.SetClientData(self._colormap_customtint_idx, colour)
RuntimeError: wrapped C/C++ object of type ColorMapComboBox has been deleted
This runtime error does not seem to affect the colormap selection or anything GUI related but does however show an Error in the Odemis-gui.log. This error is now being addressed in a way that if the stream panel would be destroyed the tint is unsubscribed.
=> [fix][METEOR] resolve C/C++ wrapper runtime error when selecting custom colormap

src/odemis/driver/simcam.py
This is only needed for the SONA camera due to mechanical differences.
When max_res is less than the full resolution of the sensor, still allow to set a .translation VA != 0,0 , so that the image can be shifted.
We should then validate that the METEOR GUI doesn’t reset/change .translation when binning  (or other settings) is changed. If it does, either the GUI should be adjusted, or we should find a different way to apply translation.
-> validation was done on a real SONA and did not need modifications to the code.
-> changes are only to the simcam to better simulate the real camera.
=> [MPM-45] SONA validate off-centre clipping with Andorcam3

src/odemis/acq/fastem.py
The pre-calibrations used to be executed at the top left of the the top-left field of the ROA, which was the (-1, -1) field. Now that ROAs can be rotated the top left field sometimes has index (10, 0), therefore doing the calibrations at the field with index (-1, -1) does not make sense anymore.
=> [feat] change location of fastem pre-calibrations

src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_fastem_overview.xrc
In Ubuntu 22.04 it looked like this
Now
=> [fix] calibration button label text and colour

src/odemis/driver/simcam.py
This fix addresses the wrong index numbers of self._img.shape used in the _setTranslation function which causes the translation to be calculated wrong. The index of self._img.shape should be YXC so always select X and Y for the translation.
=> [fix] correct image shape index in _setTranslation in simcam.py

src/odemis/driver/simsem.py
There was stage shift correction added to the detector class in simsem.py. This was to simulate stage scanning behavior in the acquired image. As there is no convenient way to check for a scan stage this code is removed here. The same code for simulating this is already in simcam.Camera, so that instead can be used in similar cases.
=> [fix] removed stage shift correction from simsem detector as it would incorrectly simulate stage scanning shift when there is no stage

src/odemis/gui/cont/tabs/fastem_main_tab.py
For the fast-em systems the users requested that they get a pop up when trying to close Odemis. Often it takes some time to set up an acquisition and if then the user accidentally clicks close, they have to redo all of that.
=> [feat] show pop up when trying to close the GUI

src/odemis/gui/comp/stream_panel.py
User's are getting confused about the remove stream functionality, as it is mismatched with the OS. Typically the - symbol means minimise, and X means close. This PR changes the icon to be consistent with the OS
=> [fix][METEOR-1015] Change remove stream icon from a dash to an X.

src/odemis/acq/feature.py, src/odemis/gui/cont/tabs/cryo_chamber_tab.py, src/odemis/gui/main_xrc.py, src/odemis/gui/win/acquisition.py, src/odemis/gui/xmlh/resources/panel_tab_cryosecom_chamber.xrc
Adds the button to reload project data for the meteor.  Data is loaded into the data model and in each gui tab where required.
Loaded data consists of:
- Overview Streams
- Features (including streams)
Handles cases where no project data is in the directory.
=> [FEAT][METEOR-1102] Reload METEOR Project Data

install/linux/usr/bin/odemis-select-mic-start
If the backend is already running, show the current active configuration (microscope) name in the user dialog window.
=> [feature][meteor] show active microscope name in dialog window when backend is already started when using odemis-select-mic-start

.github/workflows/unit_tests_cloud_ubuntu24.yml
The unit tests do not pass yet on Ubuntu 24.04. This ci-workflow can be used to figure out what we need to test and verify fixes. It will not send a notification for a failed run, but if you click on the specific github action you will see a failure for the specific build. I created a separate workflow, because it is not possible to integrate in the regular workflow such that you get a notification for failures on Ubuntu 20/22 but not on Ubuntu 24.
=> [ci] Add cloud hosted CI on Ubuntu 24.04

src/odemis/gui/cont/correlation.py, src/odemis/gui/cont/menu.py, src/odemis/gui/cont/tabs/analysis_tab.py, src/odemis/gui/cont/tabs/correlation_tab.py, src/odemis/gui/cont/tabs/tab_bar_controller.py, src/odemis/gui/main_xrc.py, src/odemis/gui/model/main_gui_data.py, src/odemis/gui/model/tab_gui_data.py, src/odemis/gui/xmlh/resources/frame_main.xrc
Users have requested the ability to use the correlation tools (stitching and correlating) overviews in the odemis viewer without being connected to a microscope. This PR adds:
Features:
- Enable the use of the correlation tab in the odemis viewer.
=> [FEAT] add correlation tab to odemis viewer

debian/control
The driver of the Diligent MCC DAQ board depends on these two libraries:
python3-hid 
python3-libusb1
=> [support] added dependencies for the Diligent MCC DAQ driver

src/odemis/gui/cont/correlation.py
Currently Odemis assumes that all SEM images are 2D grayscale. However, recently we have encountered SEM images that are stored as 3D RGB images. This causes errors when they are imported in the correlation tab as they do not have the correct metadata or classification.
This PR adds support for converting these 3D RGB SEM Images into standard 2D Static SEM Streams to work with the correlation controls. This is a temporary fix until the full import pipeline can be updated to support this new data structure. 
More details: https://docs.google.com/document/d/1jtvdAykCm8G37IuthWWaEK0OSU1qRZIX-5LEJGtTh_4/edit#heading=h.xjiyqw33io4d
=> [FIX] [METEOR-1126] Add support for importing RGB SEM Images

src/odemis/acq/stitching/__init__.py, src/odemis/acq/stitching/_tiledacq.py, src/odemis/acq/stitching/test/tiledacq_test.py, src/odemis/gui/main_xrc.py, src/odemis/gui/win/acquisition.py, src/odemis/gui/win/test/acquisition_test.py, src/odemis/gui/xmlh/resources/dialog_overview_acq.xrc
The previous overview acquisition code was fairly hardcoded for specific fm based imaging and coupled to the gui. The main components are:
**Utilities**:
- Move overview acquisition utils from gui methods into generic utilities allowing them to be used outside the user interface.
- Added test cases for tiling utilities.
**GUI**
- Added support for a acquiring overviews with FIB/SEM, and hide unused settings (e.g. z-stacks) for each mode.
- Allow using AcquireOverview task without autofocus
- Allow multi-area acquisitions without autofocus.
- Consolidate different code paths when using autofocus vs not.
- Removed direct call to AcquireTiledArea task, all paths now go through AcquireOverview.
=> [REFACTOR] [METEOR-1119] Refactor overview / tiled acquisition code

src/odemis/dataio/test/stiff_test.py, src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py
When saving z-stacks additional images (groups) were being created in the metadata. This is because the check assumed all data was 5D (CTZYX) or 2D (YX) and only checked shape[0] assuming it was the channel dim, for if the group could be merged.
Since the z-stacks are 3D (ZYX) they were being added as a separate group, with incorrect channel information (TheC, FirstC) which caused problems with downstream readers (bio-formats).
When images were re-imported, they are reshaped into 5D, so when re-exporting them, the image was 'fixed'. This only occurred for multi-channel z-stacks, as the other checks caught other cases.
=> [fix] [METEOR-1030] Prevent additional image groups in metadata being created for multi-channel z-stacks

src/odemis/gui/test/comp_foldpanelbar_test.py
FoldPanelBarTestCase.test_scrollbar_on_collapse,  FoldPanelBarTestCase.test_scrollbar_on_resize already has false positive warning. Adding it to FoldPanelBarTestCase.test_foldpanel_manipulation because it fails sometimes and it is not easily debugged.
=> [fix] add warning to foldpanelbar test cases to indicate false positives

src/odemis/acq/stitching/test/registrar_test.py
This PR changes 
- the dtype in `registrar_test.py` to use `uint` over `int`.
- the `random.randint` call to be in bound for an image of the `uint8` dtype.
To exemplify: before the suggested change, the `high` argument was set to 256, which allows integers above 127 (which is the upper bound of int8). This triggered a warning for the latest Numpy version compatible with Ubuntu 24. Now `high` is set to 255, which is the upper bound of `uint8`.
=> [test] [SWM-145] Fix numpy deprecation warning

src/odemis/acq/test/path_test.py
the brightlight-ext, spec_selector and spec_ded_det_selector are no longer controlled from the OPM. 
changed the brightlight-ext power check and removed the spec_selector and spec_ded_det_selector checks.
=> [fix] test_set_path is now adjusted to the latest changes for the FSLT in the OPM

src/odemis/acq/stitching/__init__.py, src/odemis/acq/stitching/_tiledacq.py, src/odemis/acq/stitching/test/tiledacq_test.py, src/odemis/gui/win/acquisition.py, src/odemis/gui/win/test/acquisition_test.py
This PR proposes a solution to resolve the bounding box related bug found during integration testing. After inspection, the bug was always there, but it only reached the surface after Patrick's PR (https://github.com/delmic/odemis/pull/2798).  Changes:
- The `get_tiled_areas` function is now too convoluted in my opinion (it has two responsibilities), making it unnecessarily complex to read it and to unit test it. My proposal is to separate concerns, and split the original function into two functions and handle the paths on a higher level. 
- The original fallback was heuristic. I removed the fallback and raise an error instead, so the developer will be forced to investigate if the bounding box is applicable to the specific use case and set it accordingly (like @nandishjpatel did in …
=> [refactor] tiled area code to have more separation of concerns

install/linux/usr/bin/odemis-select-mic-start
Now also log errors from the executed python script and saves the output in $HOME/.local/share/odemis/log/odemis-select-mic-start-parse.log. Errors happening this way will display an error in the start window. This is to trace issues when the content of the config file is incorrect.
=> [feature][meteor] now also log errors from the executed python script and log the output when using odemis-select-mic-start

src/odemis/driver/xt_client.py
- read raw coordinates instead of linked coordinates
- correct for offset in x and y such that the coordinated read by TFS and odemis is same in raw coordinate system
- This change requires v1.12.0 of xtadapter on support PC
=> [feature][METEOR-590] Implement reading raw coordinates of TFS stage

install/linux/usr/bin/odemis-select-mic-start, install/linux/usr/share/odemis/sim/odemis-select-mic.desktop, setup.py
The goal of this PR is to make Odemis easier to access on the Application Specialist's PC. Therefore I introduce the following changes:
- Add Odemis version selector
- Progress bar for validating microscope files
- Added a `.desktop` application file, so that there is an easy-to-access shortcut to the script
Screen to select version of Odemis
Progress bar (old version, text is different now)
Follow up screen (`/usr/share/odemis/sim/sparc2*` argument)
=> [feature] Add desktop entrypoint for mic selector

src/odemis/acq/stitching/_tiledacq.py, src/odemis/gui/main_xrc.py, src/odemis/gui/win/acquisition.py, src/odemis/gui/xmlh/resources/dialog_overview_acq.xrc
Allow the user to change the distance between autofocus for overview acquisition. 
Previously this was hardcoded at 450um, which meant that for overviews smaller than that only a single autofocus in the centre of the image was done. This was particularly bad on systems with 100x mag
=> [METEOR-1163][FEAT] Add changeable autofocus distance for overview acquisition

src/odemis/gui/main_xrc.py, src/odemis/gui/win/acquisition.py, src/odemis/gui/xmlh/resources/dialog_overview_acq.xrc
Hide the optical stream panel for METEOR overview acquisition as it is never used and contains a misleading message "No streams available". 
I think it was accidentally re-enabled in the overview refactor
=> [FIX] Hide optical stream panel for meteor overview acq

src/odemis/acq/stream/_base.py, src/odemis/acq/stream/_projection.py, src/odemis/dataio/test/tiff_test.py, src/odemis/gui/cont/correlation.py, src/odemis/util/img.py, src/odemis/util/test/img_test.py
User's reported that they were not able to correlate fm overview images, and that the images would not move.  They also reported that some overviews wouldn't load. These two issues were interrelated:
1. [METEOR-1210](https://delmic.atlassian.net/browse/METEOR-1210) Tiled imaged reads were failing for specific resolution / tile size combinations due to inconsistencies and rounding issues in the tile calculation. Made all tile reads use the same code, and fixed the rounding issues. 
2. [ METEOR-1209](https://delmic.atlassian.net/browse/METEOR-1209) The data projection for overview images uses a cache to efficiently read/display tiled images. However, the projection assumed the image would never 'move', and there was no direct way to invalidate the cache to recompute the image. 
This PR adds …
=> [METEOR-1210][FIX] Fix image pyramid tile read calculation and projection cache invalidation 

src/odemis/acq/feature.py, src/odemis/gui/cont/acquisition/cryo_acq.py, src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_localization.xrc
This PR adds the option to the user interface to run autofocus before running multi-feature acquisition. This was requested by a user and is on the roadmap for future. Assuming the autofocus works correctly, we should be able to select acquisition sites without having to move and focus beforehand. At the very least, it should serve as an initial coarse screening.
This also contains a small refactor of the zlevels calculation for the multi feature acquisition. Previously, the zlevels were calculated before starting acquisition which meant they were constant for all the features (even if they had different focus positions). Now, instead of passing in the zlevels directly, we pass in the parameters required to calculate zlevels (zmin, zmax, zstep and focus.position). 
This was also required …
=> [METEOR-1202][FEAT] Add option to autofocus before acquiring at feature positions

src/odemis/gui/cont/acquisition/cryo_acq.py
Change the odemis advanced flag to be read from a config file, rather than hardcoded in the code. This allows us to easily enable this for specific users without having to adjust the code (which requires installing a development version). 
This is temporary while we are testing the functionality which is hidden behind the flag
=> [FEAT] Add config file for odemis-advanced mode

scripts/reformat_ome_metadata.py, src/odemis/dataio/ij_tiff.py, src/odemis/dataio/test/stiff_test.py, src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py, src/odemis/util/conversion.py, src/odemis/util/test/conversion_test.py
Previous metadata exporter was not valid ome-2016. This PR fixes the ome.tiff exporter so it complies with the standard and can be used in external programs. 
Need to also make sure other systems SPARC, FastEM still work the same.
=> [METEOR-1026][FIX] Export valid OME-2016 metadata

src/odemis/gui/model/main_gui_data.py
For reasons unknown it can happen that the image translation pre-alignment does not fully center the pattern on the mppc. The result is that when we try to run the image rotation alignment, not all squares are visible in the image and the fit fails (see image below). By first running the image translation alignment we ensure that all squares are visible in the image. But because the image rotation does not rotate the pattern exactly around the center of the pattern we will have to run the image translation again afterwards. So the order will be: image translation → image rotation → image translation.
=> [fix] Run image translation before and after running image rotation

plugins/fastem_set_factory_values.py
During debugging or service actions it can be necessary to be able to load the factory settings of the descanner. This will make sure the pattern is visible on the diagnostic camera. This plugin adds an option in the help dropdown that will show a pop-up before loading the factory settings.
=> [feat] Add plugin to load FAST-EM factory settings from a dropdown menu

src/odemis/gui/cont/acquisition/cryo_acq.py
There is a race condition on the is_acquiring/_on_acquisition callback, if the stream is playing, the callback has to wait for the main ui thread to be available to start, while the acquisition can just start. the callback will pause the stream, and the acquisition will timeout. We add a synchronous pause of the streams to prevent this from occurring. synchronously here. 
Currently this completely breaks imaging on the meteor, so needs to be fixed urgently
=> [fix][METEOR] prevent race condition if acquiring while streams are live

src/odemis/gui/cont/tabs/cryo_chamber_tab.py
Make the message for creating /loading a project agnostic for meteor / enzel
=> [fix] Make project load message product agnostic

src/odemis/acq/align/autofocus.py
Fix an issue in the binary autofocusing algorithm that caused the optical autofocus to fail.
=> [fix] Fast-EM optical autofocus tests

src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py, src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_fastem_acqui.xrc
For some samples the beam damage is minimal when the beam is left unblanked during stage moves. As beam blanking and unblanking takes ~0.16 s, this feature makes beam blanking optional to increase throughput.
=> [feat] make fastem beam blanking in between fields optional

src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_fastem_acqui.xrc
Expanding the log panel caused the acquisition START button to disappear. Using option as 1 along with wxEXPAND flag for pnl_projects and its sizer's allows the acquisition tab to share available space
=> [fix] set pnl_projects and its sizeritem's option as 1 to share available space

src/odemis/dataio/test/tiff_test.py, src/odemis/dataio/tiff.py
=> [METEOR-1230][fix] store power correctly for each channel in metadata

src/odemis/model/_futures.py, src/odemis/model/test/futures_test.py
make use of _is_cancel_triggered flag to cancel only once the ProgressiveBatchFuture and all its sub-futures when an exception occurs or CancelledError is raised for a sub-future
=> [fix] stack overflow python error for ProgressiveBatchFuture having large number of sub-futures

src/odemis/acq/fastem.py, src/odemis/driver/technolution.py, src/odemis/gui/comp/fastem_roa.py, src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/cont/tabs/fastem_project_settings_tab.py, src/odemis/model/_futures.py
make use of acq_dwell_time arg to correctly calulate the fieldscan time using getTotalFieldScanTime()
In the vEM GUI projects can have their own acquisition dwell time. This is now taken into account and the acquisition time is estimated correctly for dwell time slider change.
=> [fix] estimate acquisition time calculation

src/odemis/gui/comp/fastem_project_manager_panel.py
current_project va callback
- Enable the project related pnls based on len of current project
- Enable the project related btns based on len of current project and active project tab not being project settings tab
is_acquiring va callback
- Enable the project related pnls based on acquiring flag
- Enable the project related btns based on acquiring flag and active project tab not being project settings tab
=> [fix] project pnl and btn enabling in current_project and is_acquiring va callbacks

src/odemis/gui/conf/data.py
Change the label for the Max Intensity Projection toggle to MIP (based on app specialist feedback)
=> [fix] Change label for max intensity projection to MIP

install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml
[feat] make use of mppc's MD_CALIB metadata to decide whether to adjust the dark gain correction based on min max values of the acquired image or not
percntl_im_rng and percntl_dyn_rng are params used when adjusting the dark gain correction
Supporting PR on bitbucket: https://bitbucket.org/delmic/fastem-calibrations/pull-requests/163
=> [SDEV-1939] make cell translation work with without adjusting dark gain correction

install/linux/usr/share/odemis/sim/meteor-tfs2-sim.odm.yaml, src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/model/_metadata.py
Read raw z coordinate system in TFS systems and image on fixed plane when performing FM imaging.
- add new posture manager
- add new test functions in move_test.py
https://bitbucket.org/delmic/xtlib-adapter/pull-requests/83
Switch from reading to linked Z coordinated to stage-bare Z coordinate for TFS  xt_client.py driver.
Tested:
- The stage bare Z is always be read with these commit changes irrespective of how TFS software reads Z. The TFS software can read Z as linked Z or stage bare Z depending on the user's workflow.
- SEM to FM switching works
- FM to SEM does not work as shift in y is observed on hardware. Now it is corrected and tested on simulation, needs to be tested on hardware
=> [fix][METEOR-590] TFS Posture Manager which reads FM features at a fixed imaging plane

src/odemis/gui/cont/stream.py, src/odemis/gui/cont/tabs/fastem_main_tab.py, src/odemis/gui/cont/tabs/fastem_project_settings_tab.py, src/odemis/gui/cont/tabs/fastem_setup_tab.py, src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_fastem_acqui.xrc, src/odemis/gui/xmlh/resources/panel_tab_fastem_setup.xrc
Fixed:
In xrc file `<bg>#4D4D4D</bg>` (The bg of CaptionBar and acq button was missing)
In xrc file `<border>` (No calibration run text was cropped)
Settings dwell time (The slider was cropped)
Immersion mode cbox (the cbox position not aligned properly)
=> [SDEV-1938] make v em gui compatible with ubuntu 22

src/odemis/gui/cont/tabs/sparc2_align_tab.py
During spectorgraph focusing, the slit image is a single line over a complete black background.
That line represents a small propotion of the pixels, so the standard
outliers percentage (1/256) could sometimes end-up hiding a part of the line.
=> Reduce the outlier percentage to highlight the line.
This doesn't change the autofocus behaviour, but helps manual
calibration.
=> [feat] SPARC alignment slit overlay hightlight low signal

src/odemis/driver/xt_client.py
Now it correctly takes into account if the requested move is relative or not, to compare the axes
=> [fix] correct the check to find which axes are requested to move. 

src/odemis/gui/comp/fastem_project_manager_panel.py, src/odemis/gui/cont/fastem_grid_base.py, src/odemis/gui/cont/fastem_project_tree.py, src/odemis/gui/cont/tabs/fastem_project_ribbons_tab.py, src/odemis/gui/cont/tabs/fastem_project_roas_tab.py, src/odemis/gui/cont/tabs/fastem_project_sections_tab.py
[perf] optimize ProjectManagerImportExport's _apply_project_data function to import projects data faster
The following high level changes have been made:
- Extend tab_data shapes list and set the update value without notifying to avoid unnecessary subscriber's callback
- Add child to a node without sorting; instead call tab_data.projects_tree.sort_children_recursively() in the end
- Separate creating/gathering all projects data and adding grid rows/children of all projects, because the later takes more time because it has functions which have wx.PostEvent triggering GUI changes
- Created a smart way of switching ribbons, sections, roas grid for projects, the projects grid data is now stored in a A dict where key is the project name and value is the project grid's data, the project's grid …
=> [SDEV-1937] support importing greater than 2000 roas

src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py, src/odemis/gui/__init__.py, src/odemis/gui/comp/overlay/fastem.py, src/odemis/gui/comp/settings.py, src/odemis/gui/comp/viewport.py, src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/main_xrc.py, src/odemis/gui/model/main_gui_data.py, src/odemis/gui/xmlh/resources/panel_tab_fastem_setup.xrc
[feat] restructured calibration panel layout
Changes
- Calibration 1 also has a box
- Calibration 1, 2, 3 colour are choosen keeping colour blindness in mind
- Individual calibration Run button replaced with individual calibration checkbox and finally a single RUN button to run the checked and enabled calibrations
- Single cancel button to cancel running calibrations
=> [SDEV-1945] restructure calibration panel layout

src/odemis/gui/cont/acquisition/cryo_acq.py, src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_localization.xrc
Previously, the automatic feature acquisition was an all or nothing process. It would acquire at every feature, and there was no way to select a subset. This PR adds a checklist box for selecting features to acquire and moves all 'automation' features to a separate fold panel for better organisation.
=> [feat] add checklist box for feature selection in acquistion

src/odemis/dataio/csv.py
On Windows, the default newline character is "\n" for exporting rows with csv writer.
Explicitly overwrite the newline character to be empty. This behavior never occurred on Linux due to a different newline convention.
Example of current behavior in Windows:
=> [fix] newlines in ar csv export (Windows)

src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/cont/tabs/fastem_setup_tab.py
[fix] issues related to SEM stream panel
Fixed:
- Allow cancelling of Auto brightness / contrast and SEM autofocus buttons
- Correctly enable/disable buttons and panels when an autofunction or an acquisition is running is running
- Pause the stream at the start of an autofunction and replay it once its finished running if the stream was playing before the start
=> [SDEV-1946] fix issues related to sem stream panel

install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml, scripts/spot-grid.py, src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py, src/odemis/util/peak_local_max.py, src/odemis/util/registration.py, src/odemis/util/spot.py, src/odemis/util/test/spot_test.py
[perf] Improve spot finding in when distance between spots >> spot size
Improved spot finding and grid fitting accuracy in `estimate_grid_orientation_from_img` and `find_spot_positions` by:
- Using a configurable minimum distance between spots during local maxima finding. This addresses issues when the intensity difference between spots is high and single bright spots could be detected twice, while less bright spots were not detected.
- Splitting `min_distance` and `len_object` parameters in `peak_local_max` and `find_spot_positions` to refine spot size calculation and edge exclusion relative to minimum spot distance.
=> [perf] Improve spot finding in estimate_grid_orientation_from_img

install/linux/usr/share/odemis/sim/fastem-sim-asm.odm.yaml, src/odemis/acq/fastem.py, src/odemis/acq/stitching/__init__.py, src/odemis/acq/stitching/_tiledacq.py
Fix includes:
- correctly estimating the stage movement time and adding it to the total time
- keeping the overhead time separate to overview acquisition time and stage time
=> [SDEV-1947] estimating overview image tiled acquisition time

src/odemis/acq/test/acq_test.py
commit e0424ae90a51 (acq_test: adjust acqmng.acquire() API usage) made
the code more explicit for receiving the errors, but didn't adjust the
follow up code. So that broke the test.
=> now that the two return values data & exp are separate, "data" can be
accessed directly.
=> [fix] acq_test test_metadata failed

src/odemis/acq/align/tdct.py, src/odemis/acq/align/test/tdct_test.py
Implementation of the 3DCT wrapper to allow running multi-point correlation from odemis. Includes a parser to read correlated position from file, and z-targeting utility for multi-channel images.
3DCT package now only has two dependencies for the core workflow (excluding user interface and image readers), which are already included in odemis (numpy, scipy). Packaging will be done later. [Source Repository](https://github.com/patrickcleeve2/3DCT/tree/refactor)
Subtasks: 
- [METEOR-1128](https://delmic.atlassian.net/browse/METEOR-1128?atlOrigin=eyJpIjoiZDU4MWM2ZGJiZjhjNDMxODhlZWU5NzZjM2IxZmNlYzQiLCJwIjoiaiJ9)
- [METEOR-1251](https://delmic.atlassian.net/browse/METEOR-1251?atlOrigin=eyJpIjoiNWZkYmUwNGNkZGZjNDlkMWFiMTk0NmQ5Zjk0NGExZGIiLCJwIjoiaiJ9)
Specifications:
- [Multi-Point …
=> [feat][METEOR-1128] TDCT Odemis Wrapper

src/odemis/acq/stitching/_tiledacq.py, src/odemis/gui/comp/overlay/rectangle.py, src/odemis/gui/conf/data.py, src/odemis/gui/cont/stream_bar.py, src/odemis/gui/cont/tabs/localization_tab.py, src/odemis/gui/main_xrc.py, src/odemis/gui/model/__init__.py, src/odemis/gui/model/_constants.py, src/odemis/gui/model/stream_view.py, src/odemis/gui/model/tab_gui_data.py, src/odemis/gui/win/acquisition.py, src/odemis/gui/xmlh/resources/panel_tab_localization.xrc, src/odemis/model/_metadata.py
Minor GUI modifications in preparation for FIBSEM controls and automated workflow
=> [METEOR-960] FIBSEM GUI Preparation

src/odemis/acq/test/stream_overlay_test.py
Commit ea08ee662e (Support for partial SPARC acquisition) changed the
return type of .acquire(). The OverlayStream was updated to match this,
but not the test case.
=> [fix] test_overlay_stream failed due to change in API

src/odemis/acq/fastem.py, src/odemis/acq/test/fastem_test.py, src/odemis/gui/comp/settings.py, src/odemis/gui/cont/acquisition/fastem_acq.py, src/odemis/gui/cont/fastem_project_tree.py, src/odemis/gui/main_xrc.py, src/odemis/gui/xmlh/resources/panel_tab_fastem_acqui.xrc
NOTE: This PR depends on https://github.com/delmic/odemis/pull/2972
[feat] allow skipping roa acquisition in case of failure
Updates:
- The status text in the ROA window of the project tree will show "Open", "Skipped", "Failed" and respective colour
- Added autostigmation and autofocus period in the Acquisition panel; previously it was in the acquisition.config file
- Added a checkbox `Stop acquisition on failure` which helps is skipping roa acquisition in case of failure
Cancelled
Stop acquisition on failure checked (Exception is raised in autostigmation)
Stop acquisition on failure un-checked (Exception is raised in autostigmation)
=> [SDEV-1916] fix pre calibration failure stops the acquisition

.github/workflows/unit_tests_cloud.yml, src/odemis/acq/drift/__init__.py, src/odemis/acq/milling/milling_tasks.yaml, src/odemis/acq/milling/millmng.py, src/odemis/acq/milling/patterns.py, src/odemis/acq/milling/plotting.py, src/odemis/acq/milling/tasks.py, src/odemis/acq/milling/test/patterns_test.py, src/odemis/acq/milling/test/tasks_test.py, src/odemis/driver/autoscript_client.py
This PR contains the new milling structures and functions, and migrates the old mimas code to separate files.
=> [METEOR-960] Milling Structures and Functions

install/linux/usr/share/odemis/sim/meteor-tfs3-sim.odm.yaml, src/odemis/acq/move.py, src/odemis/acq/test/move_test.py, src/odemis/gui/model/main_gui_data.py, src/odemis/model/_metadata.py, src/odemis/util/transform.py
Adds:
- TFS3 posture manager for multi-posture imaging functionality.
- SampleStage virtual component
[JIRA: METEOR-996](https://delmic.atlassian.net/browse/METEOR-996?atlOrigin=eyJpIjoiMTZkZWQ3MzExZmRmNDE1ODk3ZDUxNTA0M2Q3NjIxN2YiLCJwIjoiaiJ9)
[Specification]( https://docs.google.com/document/d/1uDZrg1up0wrbu5ODU1uDm9iSeUZNYJitedxlhfMYfZk/edit?pli=1&tab=t.0#heading=h.b8qus0izsixj)
=> [feat][METEOR-996] Add TFS3 posture manager for multi-posture imaging

src/odemis/driver/tescan.py, src/odemis/driver/test/tescan_test.py, src/odemis/gui/conf/data.py
Use SetBeamCurrent/GetBeamCurrent over the deprecated SetPCIndex API method. As a consequence, we don't have to do list index handling and we can have a continuous VA. Since the current range is device specific, a default value is introduced that is over-writable via the yaml.
And separately, I also introduced a log scale, since there was otherwise no differentiation on the slider for smaller values.
Tescan Sim
Odemis
=> [fix] [METEOR-1347] Tescan e-beam current API use

src/odemis/driver/tfsbc.py
In the latest version of pymodbus the location of ModbusSerialClient has changed. This commit fixes the import such that it works with old and new versions of pymodbus.
=> [fix] Update pymodbus import for compatibility with latest version

src/odemis/driver/technolution.py
Previously we set the filename of calibration data to .calibrations to ensure that the calibration data did not get post processed. In v3.0 Technolution added support for disabling the offloading of data to the storage server
Also removed 2 TODOs in a separate commit in this PR, since the TODOs have been implemented by now.
=> [feat] FVEM-40 Disable offloading of calibration data to the technolution storage server

.github/workflows/unit_tests_cloud.yml, src/odemis/acq/stitching/_tiledacq.py, src/odemis/acq/stitching/test/tiledacq_test.py, src/odemis/gui/comp/fastem_roa.py, src/odemis/util/raster.py, src/odemis/util/test/raster_test.py
The code changes are similar to that of FASTEM ROA which is represented by points. One difference is that `TiledAcquisitionTask` supports both a bound box and points as an input region and is backwards compatible.
Attached an image for overview image acquisition of a rotated rectangle
=> [SDEV-1958] extend tiled acquisition code to be able to acquire non rectangular shapes

src/odemis/acq/milling/milling_tasks.yaml, src/odemis/acq/milling/openfibsem.py, src/odemis/acq/milling/patterns.py, src/odemis/acq/milling/test/openfibsem_millmng_test.py, src/odemis/acq/milling/test/openfibsem_test.py, src/odemis/acq/milling/test/patterns_test.py
Integrate openfibsem milling manager for cross-platform milling
Requires:
- https://github.com/delmic/odemis/pull/3000
=> [feat] Integrate OpenFIBSEM Milling

src/odemis/acq/milling/test/millmng_test.py
E   OSError: Failed starting backend with '['/usr/bin/python3', '/home/testing/development/odemis/src/odemis/odemisd/main.py', '--log-level=2', '--log-target=testdaemon.log', '--daemonize', '/home/patrick/development/odemis/install/linux/usr/share/odemis/sim/meteor-fibsem-sim.odm.yaml']' (returned 1)
=> [fix] error starting millmng_test.py due to hardcoded path

util/axes-odometer
ERROR:root:Failed to parse b"Updated position to {'s': 0.0029690275, 'l': 0.0505179063}" Traceback (most recent call last):
File "/home/dev/development/odemis/./util/axes-odometer", line 78, in add_distances
pos = read_pos(l)
File "/home/dev/development/odemis/./util/axes-odometer", line 64, in read_pos
m = RE_UPD_POS.search(line)
TypeError: cannot use a string pattern on a bytes-like object Distance: {}
=> [SWM-182][fix] axes-odometer util to read log lines as a string and not a byte

plugins/fastem_save_full_cell_images.py, plugins/fastem_set_factory_values.py
Both single and multi-beam acquisition are now supported in the detailed overview image gui. The previous acquisition tab is now the multi-beam tab.
=> [fix] make use of the multi-beam tab given the detailed overview image gui layout

src/odemis/acq/test/stream_test.py
Because the test cases is based on the backend sparc2-nidaq-sim.odm.yaml, which relies on nidaqmx which is not supported on Ubuntu 20.04 or lower.
=> [fix] Skip SPARC2HwSyncTestCase if is 20.04 or lower

install/linux/usr/share/odemis/sim/meteor-fibsem-sim.odm.yaml, src/odemis/driver/autoscript_client.py, src/odemis/driver/test/autoscript_client_test.py
Run backend of xtadapter and autoscript on different ports 4242, 4243 respectively.
Tested on the simulator for autoscript on port 4243
- one test is failing (working on the PR) but it is not related to change in the port number
=> [fix] change the port number for autoscript backend from 4242 to 4243

src/odemis/driver/technolution.py
There was a fault in the hardware, this caused the very first field of a megafield to not be recorded at all. This is now fixed in the hardware, therefore the fix can be removed.
=> [fix] Technolution driver remove scanning first field twice

src/odemis/gui/cont/correlation.py, src/odemis/gui/cont/stream_bar.py, src/odemis/gui/cont/tabs/cryo_chamber_tab.py, src/odemis/gui/cont/tabs/fibsem_tab.py
When the sem overview streams are acquired in the fibsem tab, they are also added in the correlation tab and the localizaton tab. If the streams are updated in the correlation tab, they are also updated in the localization and the fibsem tabs. The update means addition of a new stream, deletion of the existing stream, modification in the correction metadata and lastly the reset of the correction metadata.
Other related fixes -
1) It (This PR)  also fixes [METROR-1438] by updating the SEM overview metadata correctly when the correction metadata is changed. 
2) It correctly loads the overviews from the cryo_chamber tab in the three tabs -> correlation, fibsem and localization. Earlier, the overviews were duplicating in the correlation tab as the overviews from fibsem and localization were …
=> [METEOR-1587][fix] show acquired sem overview stream panel

src/odemis/acq/stitching/_weaver.py
This is a temporary fix to read tiles with scan rotation applied and perform movement in SEM/FIB live imaging. But it does not work properly with turning off the scan rotation and moving the stage in SEM/FIB live imaging.
Without scan rotation
- the stage in FIB/SEM moves in the opposite direction when double clicking/dragging in live imaging.
=> [fix] read SEM tiles with scan rotation applied

src/odemis/gui/comp/fastem_roa.py
count_stage_moves raises IndexError: too many indices for array when there are no tiles, return early if there are no tiles to acquire
=> [fix] if there are no TOA tiles to acquire return 0 for estimate_acquisition_time

src/odemis/gui/win/acquisition.py
Add subscribe to pixel size VA, so the settings are updated when changing HFW or magnification (and thus the area is recalculated).
See how to "Tiled area size" value updates after changing the HFW.
=> [METEOR-1653] [fix] Update area value after updating HFW

src/odemis/dataio/tiff.py
It is not that useful to know and it clogs up the logs
=> [refactor] Remove debug logging for skipped TIFF metadata tags

src/odemis/acq/align/autofocus.py, src/odemis/acq/align/test/fastem_test.py
Sometimes, the fast-em autofocus test case fails, because the min/max is
the same as the current position. Hard to reproduce, so let's try to get
more information via the logs.
=> [fix] Improve log for fast-em autofocus

src/odemis/acq/align/test/roi_autofocus_test.py, src/odemis/acq/milling/test/patterns_test.py, src/odemis/dataio/test/ij_tiff_test.py, src/odemis/driver/test/autoscript_client_test.py, src/odemis/util/test/interpolation_test.py
by calling unittest.main() at the bottom of the files
=> [ci] Ensure all tests are runnable

src/odemis/driver/test/cam_test_abs.py
Add timeout buffer for pending CCD acquisitions in sync test.
**Problem**: The test_basic method in `VirtualTestSynchronized` was experiencing random test failures with `AssertionError: 1 != 0` due to a race condition where the test checked `self.ccd_left == 0` before all CCD image acquisition callbacks finished executing.
**Solution**: Added a polling timeout mechanism that waits up to 2x (exposure + readout) time for any pending CCD acquisitions to complete before performing the final assertion.
**Result**: This eliminates the random test failures while preserving the core functionality of validating SEM-CCD trigger synchronization.
=> [fix] TestSimStreakCamGenericCamSynchronized test_basic

debian/odemis.install, install/linux/usr/share/dbus-1/services/org.freedesktop.Notifications.service
By doing so the service will be installed during odemis install/update
=> [fix] move org.freedesktop.Notifications.service dependency to odemis.install

src/odemis/gui/comp/fastem_user_settings_panel.py
The current message is a bit too friendly, this does not convey the warning that voltage adjustment should only be done by a trained user.
=> [refactor] FAST-EM Update voltage adjustment pop-up

src/odemis/acq/milling/test/millmng_test.py
- Added more explicit move to SEM position, the make sure not to start from an UNKNOWN posture.
- Added use of `deepcopy` over shallow `.copy()`, as the latter was not sufficient for the nested `self.features`:
```
from copy import deepcopy
features_shallow = self.features.copy()
features_deep = deepcopy(self.features)
self.features[0].status
<odemis.model._vattributes.StringVA object at 0x7055dd149180>
self.features[0].status.value
'Ready to Mill'
features
[<odemis.acq.feature.CryoFeature object at 0x7055dd189150>, <odemis.acq.feature.CryoFeature object at 0x7055dd14bfa0>]
features_deep[0].status.value
'Ready to Mill'
features_deep[0].status.value = "123"
features_deep[0].status.value
'123'
self.features[0].status.value
'Ready to Mill'
features_shallow[0].status.value = "123" …
```
=> [test] Guard against mutation millmng tests

src/odemis/driver/technolution.py
To shift the setpoints by a shift-factor the numpy array is rolled by that factor multiplied by the number of setpoints. `round` was used to convert to an integer value to roll by, however in old versions of python/numpy round can return a float instead of an int, this could lead to numpy.roll failing with the error
TypeError: slice indices must be integers or None or have an __index__ method
FVEM-184
=> [fix] Technolution convert phase shift to int

src/odemis/driver/test/semnidaq_test.py
If python version is less than 3.9.0, skip the file
=> [fix] skip semnidaq test case

util/runtests.sh
The status of calling the test case from bash was logged in the full test report, but nothing was done with it. Now if the status is not 0 (OK) it is also copied to the summary. Especially for timeouts this is usefull to know, because if test cases time out failures can get hidden.
=> [ci] Add logging timeouts and other errors to runtests.sh

src/odemis/gui/cont/menu.py, src/odemis/gui/cont/tabs/cryo_chamber_tab.py
disabled/removed the menu entry for calibration for all the systems which are not METEOR and does not have CALIB in the stage metadata
=> [fix] delete edit meteor configuration menu item

src/odemis/gui/cont/menu.py, src/odemis/gui/cont/tabs/cryo_chamber_tab.py
The definition of stage changed from stage-bare to sample stage which led to the conditions for enabling the pop up to fail. Now the conditions are checking metadata in stage-bare and not in stage.
=> [METEOR-1717][fix] pop up of edit meteor calibration works
